### ISSUE TITLE
Change to different linter (`golint` is no longer supported)

### ISSUE THREAD

**Issue by krishnan-mani** [rebuy-de/aws-nuke#1002]
- Please see [accepted proposal](https://github.com/golang/go/issues/38968#issuecomment-638331245)
- The current make [target for `lint`](https://github.com/rebuy-de/aws-nuke/blob/58736c8eb2778a345bc28fc0735a492550abab79/golang.mk#L43) still references `golint`
- Attempting to install `golint` causes clashes with package versions

**Comment by ekristen** [comment]
@krishnan-mani the [active managed fork of aws-nuke](https://github.com/ekristen/aws-nuke) now uses a highly tailored golangci-lint configuration. 

----

Please see the copy of the notice from the README about the deprecation of this project. Sven was kind enough to grant me access to help triage and close issues and pull requests that have already been addressed in the actively maintained fork. Some additional information is located in the [welcome issue](https://github.com/ekristen/aws-nuke/issues/276) for more information. 

> [!CAUTION]
> This repository for aws-nuke is no longer being actively maintained. We recommend users to switch to the actively maintained fork of this project at [ekristen/aws-nuke](https://github.com/ekristen/aws-nuke).
> We appreciate all the support and contributions we've received throughout the life of this project. We believe that the fork will continue to provide the functionality and support that you have come to expect from aws-nuke.
> Please note that this deprecation means we will not be addressing issues, accepting pull requests, or making future releases from this repository.
> Thank you for your understanding and support.
