### ISSUE TITLE
Sagemaker not deleting properly

### ISSUE THREAD

**Issue by eitancohen2023** [rebuy-de/aws-nuke#1004]
When I have a sagemaker instance open and running with user profiles, ecs, and efs I guess that the EFS is getting deleted first and then the ECS but when it tries to delete the Sagemaker domain it fails because it needs the EFS. Anyone else having this issue?

**Comment by aleksandar-babic** [comment]
Very similar thing happening for me, Sagemaker domain failing to delete due to dependencies on assigned Apps.

**Comment by ekristen** [comment]
Many sagemaker resources are now supported in v3 at https://github.com/ekristen/aws-nuke. Please give it a try and let me know if you run into any issues over there.

----

Please see the copy of the notice from the README about the deprecation of this project. Sven was kind enough to grant me access to help triage and close issues and pull requests that have already been addressed in the actively maintained fork. Some additional information is located in the [welcome issue](https://github.com/ekristen/aws-nuke/issues/276) for more information. 

> [!CAUTION]
> This repository for aws-nuke is no longer being actively maintained. We recommend users to switch to the actively maintained fork of this project at [ekristen/aws-nuke](https://github.com/ekristen/aws-nuke).
> We appreciate all the support and contributions we've received throughout the life of this project. We believe that the fork will continue to provide the functionality and support that you have come to expect from aws-nuke.
> Please note that this deprecation means we will not be addressing issues, accepting pull requests, or making future releases from this repository.
> Thank you for your understanding and support.
