### ISSUE TITLE
Ability to delete virtual clusters launched by EMR containers

### ISSUE THREAD

**Issue by pankajkoti** [rebuy-de/aws-nuke#1012]
I do not see a resource type listed to nuke the virtual clusters launched by AWS EMR containers.
Will it be possible to support nuking this resource type?

I also have posted a repost.aws questions here: https://repost.aws/questions/QUk_8WEMNrT7m4p6n_7icbuA/how-to-delete-aws-emr-container-virtual-clusters-via-the-console-or-via-aws-nuke

**Comment by ekristen** [comment]
tracked via https://github.com/ekristen/aws-nuke/issues/352
