### ISSUE TITLE
Previous report as an input

### ISSUE THREAD

**Issue by kagarlickij** [rebuy-de/aws-nuke#1020]
Is it possible to make `aws-nuke` to audit only those resources that were marked for deletion during previous run and ignore new resources? 
I need to give colleagues a chance to properly tag resources before they are deleted

**Comment by npellegrin** [comment]
This issue is similar to #755 

Regarding your particular usecase, I would have recommended [Resource Groups & Tag Editor](https://docs.aws.amazon.com/whitepapers/latest/tagging-best-practices/implementing-and-enforcing-tagging.html#enforcement). Is there a particular reason for using aws-nuke for tag remediation ?

**Comment by ekristen** [comment]
I love the idea of a nuke plan similar to a terrform plan and apply. I even have it listed for request for comment on this fork. I'm closing this issue now to help with cleanup as this repo is now deprecated, please if you are in support of this feature head over to https://github.com/ekristen/aws-nuke/issues/85 and give it a thumbs up and leave any feedback.

----

Please see a copy of the notice from the README about the deprecation of this project. Sven was kind enough to grant me access to help triage and close issues and pull requests that have already been addressed in the actively maintained fork. Some additional information is located in the [welcome issue](https://github.com/ekristen/aws-nuke/issues/276) for more information. 

> [!CAUTION]
> This repository for aws-nuke is no longer being actively maintained. We recommend users to switch to the actively maintained fork of this project at [ekristen/aws-nuke](https://github.com/ekristen/aws-nuke).
> We appreciate all the support and contributions we've received throughout the life of this project. We believe that the fork will continue to provide the functionality and support that you have come to expect from aws-nuke.
> Please note that this deprecation means we will not be addressing issues, accepting pull requests, or making future releases from this repository.
> Thank you for your understanding and support.
