### ISSUE TITLE
CloudFront Functions are not supported

### ISSUE THREAD

**Issue by npellegrin** [rebuy-de/aws-nuke#1027]
It appears CloudFront functions are not currently deleted by aws-nuke.

Announce: https://aws.amazon.com/fr/blogs/aws/introducing-cloudfront-functions-run-your-code-at-the-edge-with-low-latency-at-any-scale/
Documentation: https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/cloudfront-functions.html
SDK: https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/cloudfront#Client.DeleteFunction

**Comment by Neckster** [comment]
+1 to the issue above. Also the CloudFront OAC is not supported as well.

**Comment by npellegrin** [comment]
I opened #1019 and an corresponding PR for CloudFront OAC as well :)
