### ISSUE TITLE
About the latest release

### ISSUE THREAD

**Issue by chenrui333** [rebuy-de/aws-nuke#1033]
👋 it looks like the 2.23.0 did not get labeled correctly, create this issue for some awareness. Thanks!

relates to https://github.com/Homebrew/homebrew-core/pull/134309

![image](https://github.com/rebuy-de/aws-nuke/assets/1580956/c2caf3da-e264-4525-8d7e-76075a5fcc25)
![image](https://github.com/rebuy-de/aws-nuke/assets/1580956/60e39e4a-7c77-4c97-b2dc-4f42601b15c2)

**Comment by chenrui333** [comment]
cc @der-eismann

**Comment by npellegrin** [comment]
Looks like #1032 is also not merged

**Comment by chenrui333** [comment]
but somehow the tag is in place?

**Comment by der-eismann** [comment]
Interesting, never had to check that box before. 
![screenshot-20230626-113706](https://github.com/rebuy-de/aws-nuke/assets/10406217/9ce59afb-35c3-4e3d-aaae-d69965c82253)

Should be fixed now, sorry for the late reply!

**Comment by chenrui333** [comment]
Thanks @der-eismann, that is exactly what I was looking for!
