### ISSUE TITLE
AWS Nuke not deleting code star hosts

### ISSUE THREAD

**Issue by kbdevops** [rebuy-de/aws-nuke#1034]
Hi guys, 

So we noticed its actually deleting the connection but not the hosts, this is problematic because there is always a security group attached to code * hosts to it which will have a dependency with the other networking resources. Can we please look at fixing this bug - many thanks :) 

![image](https://github.com/rebuy-de/aws-nuke/assets/81782091/c588797b-aac8-4f94-ba8f-0f64d56ab662)

**Comment by der-eismann** [comment]
Hi @kbdevops, that is not really a bug - the resource simply doesn't exist yet in aws-nuke. We currently have `CodeStarConnection`, `CodeStarNotificationRule` & `CodeStarProject` as supported resources. Feel free to add a resource for it, you can take the [codestar-connections.go](https://github.com/rebuy-de/aws-nuke/blob/main/resources/codestar-connections.go) as an example.

**Comment by kbdevops** [comment]
Thanks mate, I will look into this @der-eismann

**Comment by ekristen** [comment]
The latest version of aws nuke at https://github.com/ekristen/aws-nuke has these resources supported.

----

Please see the copy of the notice from the README about the deprecation of this project. Sven was kind enough to grant me access to help triage and close issues and pull requests that have already been addressed in the actively maintained fork. Some additional information is located in the [welcome issue](https://github.com/ekristen/aws-nuke/issues/276) for more information. 

> [!CAUTION]
> This repository for aws-nuke is no longer being actively maintained. We recommend users to switch to the actively maintained fork of this project at [ekristen/aws-nuke](https://github.com/ekristen/aws-nuke).
> We appreciate all the support and contributions we've received throughout the life of this project. We believe that the fork will continue to provide the functionality and support that you have come to expect from aws-nuke.
> Please note that this deprecation means we will not be addressing issues, accepting pull requests, or making future releases from this repository.
> Thank you for your understanding and support.
