### ISSUE TITLE
Wildcard Filters

### ISSUE THREAD

**Issue by littlelegs** [rebuy-de/aws-nuke#1043]
Can we use a wildcard on the filters? As an example rather than using

filters:
EC2Instance:

Could we use

filters:
*:

**Comment by danbdo** [comment]
I would like that as well. Like: "On any resource type that supports tags, if a resource has tag xyz -> filter it"

**Comment by mark-pendlebury-bjss** [comment]
+1 this, 

in our use case, we have similar named resources in an account per region, for example, and s3 bucket in eu-west-1 and us-east-2 named like this:

`config-eu-west-1-lambda`
`config-us-east-1-lambda`

it would be nice when creating a nuke config across both regions to filter something like

```
S3Object:
    - "config-*-lambda
```
 
or even better:
```
S3Object:
    - "config-${REGION}-lambda"
```

**Comment by ekristen** [comment]
@littlelegs @danbdo the now active and primary fork of aws-nuke has implemented [global filters](https://ekristen.github.io/aws-nuke/config-filtering/#global)

If you run into any issues, please open an issue over on the forked project repository.

--

Please see a copy of the notice from the README about the deprecation of this project. Sven was kind enough to grant me access to help triage and close issues and pull requests that have already been addressed in the actively maintained fork. Some additional information is located in the [welcome issue](https://github.com/ekristen/aws-nuke/issues/276) for more information. 

> [!CAUTION]
> This repository for aws-nuke is no longer being actively maintained. We recommend users to switch to the actively maintained fork of this project at [ekristen/aws-nuke](https://github.com/ekristen/aws-nuke).
> We appreciate all the support and contributions we've received throughout the life of this project. We believe that the fork will continue to provide the functionality and support that you have come to expect from aws-nuke.
> Please note that this deprecation means we will not be addressing issues, accepting pull requests, or making future releases from this repository.
> Thank you for your understanding and support.
