### ISSUE TITLE
--assume-role-arn  flag does not work in opt-in regions

### ISSUE THREAD

**Issue by bassjompi** [rebuy-de/aws-nuke#1062]
Hello,
im trying to nuke non-standard AWS regions in my aws account uisng the command:

 aws-nuke -c $NUKE_TEMPLATE --force --assume-role-arn $ROLE_TO_ASSUME

This works as expected in the standard regions, but in opt-in regions such as eu-south-1 im receivinf the message:
**UnrecognizedClientException: The security token included in the request is invalid**

I believe this is caused because of these regions are not compatible with the global sts endpoint. Is there a way on how to solve this?
maybe a --endpoint_url flag as in  assume_role CLI command?

thanks

**Comment by ekristen** [comment]
@bassjompi please test out the [active managed fork of aws-nuke](https://github.com/ekristen/aws-nuke) and if the issue still persists open an issue there.  All regions, even opt-in should be supported and it should select the correct STS endpoint, but if not I'll do my best to look into it.

----

Please see the copy of the notice from the README about the deprecation of this project. Sven was kind enough to grant me access to help triage and close issues and pull requests that have already been addressed in the actively maintained fork. Some additional information is located in the [welcome issue](https://github.com/ekristen/aws-nuke/issues/276) for more information. 

> [!CAUTION]
> This repository for aws-nuke is no longer being actively maintained. We recommend users to switch to the actively maintained fork of this project at [ekristen/aws-nuke](https://github.com/ekristen/aws-nuke).
> We appreciate all the support and contributions we've received throughout the life of this project. We believe that the fork will continue to provide the functionality and support that you have come to expect from aws-nuke.
> Please note that this deprecation means we will not be addressing issues, accepting pull requests, or making future releases from this repository.
> Thank you for your understanding and support.
