### ISSUE TITLE
Assistance on a Golang Coding Issue

### ISSUE THREAD

**Issue by tomvachon** [rebuy-de/aws-nuke#107]
@svenwltr 

Can you help here? https://gist.github.com/tomvachon/35a481b7b418daf63e80009d648807bb#file-gistfile1-txt-L46

The classifer type is a nested object.  I cant seem to figure this one out...  I need the name of N types but becasue its not an interface I can use .(type)

**Comment by svenwltr** [comment]
Do you get a `nil pointer dereference`? You also have to check if `classifier.GrokClassifier` is not `nil`. It could be `nil`, since it is a pointer. And if it is `nil` accessing `Name` will give you an error.

Does this help or is there another problem?

**Comment by tomvachon** [comment]
The way I have it now I get 

ERRO[0002] Listing with resources.ResourceLister failed. Please report this to https://github.com/rebuy-de/aws-nuke/issues/new.
    !!! runtime error: invalid memory address or nil pointer dereference

Any time the Classifer object isnt the first if statement

**Comment by svenwltr** [comment]
Try this:

```
if classifier.GrokClassifier != nil && classifier.GrokClassifier.Name != nil {
```

**Comment by tomvachon** [comment]
OK, I dont know what I did or did not do, but I fixed it.  I think I had a left over .Name when I was just checking for the object type....

**Comment by tomvachon** [comment]
```
		for _, classifier := range output.Classifiers {
			if classifier.GrokClassifier != nil {
				resources = append(resources, &GlueClassifier{
					svc:  svc,
					name: classifier.GrokClassifier.Name,
				})
			} else if classifier.JsonClassifier != nil {
				resources = append(resources, &GlueClassifier{
					svc:  svc,
					name: classifier.JsonClassifier.Name,
				})
			} else if classifier.XMLClassifier != nil {
				resources = append(resources, &GlueClassifier{
					svc:  svc,
					name: classifier.XMLClassifier.Name,
				})
			}
		}
```

This is what I have now.  I would have rather done it in a switch but this seems ok
