### ISSUE TITLE
rds instances are named neptune instance

### ISSUE THREAD

**Issue by f3lang** [rebuy-de/aws-nuke#1094]
when you perform and plan a nuke of an account, rds instances are listed as Neptune instances. This is buried in the fact, that the neptune api may return rds and docdb instances as well. 
Can we build a filter into the logic to filter out only actual neptune instances, as this will delete rds instances at the moment even though rds is blacklisted?
https://docs.aws.amazon.com/neptune/latest/userguide/api-instances.html#DescribeDBInstances

**Comment by sulabhk** [comment]
➕  to the above observation, but this is probably to do with the underlying AWS API and not nuke  (or its filters). I keep facing the same issue in that I see RDS instances being referred to as `NeptuneInstances` in the nuke output log.

**Comment by ekristen** [comment]
@f3lang @sulabhk 

I've opened https://github.com/ekristen/aws-nuke/issues/301 on what is now the actively managed fork of aws-nuke. I've confirmed your observations by looking at the API docs. I'll try and see about replicating and getting a fix in as soon as possible.

----

Please see the copy of the notice from the README about the deprecation of this project. Sven was kind enough to grant me access to help triage and close issues and pull requests that have already been addressed in the actively maintained fork. Some additional information is located in the [welcome issue](https://github.com/ekristen/aws-nuke/issues/276) for more information. 

> [!CAUTION]
> This repository for aws-nuke is no longer being actively maintained. We recommend users to switch to the actively maintained fork of this project at [ekristen/aws-nuke](https://github.com/ekristen/aws-nuke).
> We appreciate all the support and contributions we've received throughout the life of this project. We believe that the fork will continue to provide the functionality and support that you have come to expect from aws-nuke.
> Please note that this deprecation means we will not be addressing issues, accepting pull requests, or making future releases from this repository.
> Thank you for your understanding and support.
