### ISSUE TITLE
Deleting Cloudwatch Event Rules

### ISSUE THREAD

**Issue by fergoid** [rebuy-de/aws-nuke#1124]
If you have more than 100 rules in a bus the API call only returns the first 100 and rest are ignored for the purposes of nuking.

if you see “NextToken” in the result JSON that is an indicator that there are more than 100 results.

**Comment by ekristen** [comment]
This is being implemented via https://github.com/ekristen/aws-nuke/pull/329

----

Please see the copy of the notice from the README about the deprecation of this project. Sven was kind enough to grant me access to help triage and close issues and pull requests that have already been addressed in the actively maintained fork. Some additional information is located in the [welcome issue](https://github.com/ekristen/aws-nuke/issues/276) for more information. 

> [!CAUTION]
> This repository for aws-nuke is no longer being actively maintained. We recommend users to switch to the actively maintained fork of this project at [ekristen/aws-nuke](https://github.com/ekristen/aws-nuke).
> We appreciate all the support and contributions we've received throughout the life of this project. We believe that the fork will continue to provide the functionality and support that you have come to expect from aws-nuke.
> Please note that this deprecation means we will not be addressing issues, accepting pull requests, or making future releases from this repository.
> Thank you for your understanding and support.
