### ISSUE TITLE
Unable to delete IAMRoles and IAMPolicies

### ISSUE THREAD

**Issue by Ranjith-ankam** [rebuy-de/aws-nuke#1138]
Below is my nuke config file:
regions:
  - us-east-1
  - us-west-2

account-blocklist:
  - "XXXXXXXXXX" # production

resource-types:
  targets:
  - IAMPolicy
  - IAMRole
  - IAMRolePolicyAttachment

accounts:
  XXXXXXXXX:   #nukingaccount
    filters:
      IAMPolicy:
      - type: regex
        value: "br_tssdev_csgsmtnuking_backup_policy"
      IAMRole:
      - type: regex
        value: "br_tssdev_csgsmtnuking_backup_role"
      IAMRolePolicyAttachment:
      - type: regex
        value: "br_tssdev_csgsmtnuking_asgnet_ec2_role"
I am trying to delete IAMRoles and IAMPolicies in my account using this config file but I am unable to do so. This is what the below output: 
<img width="497" alt="image" src="https://github.com/rebuy-de/aws-nuke/assets/149522053/e3977c01-fecc-4ba5-8e63-001f2ed0048f">
Please help me to resolve this.

**Comment by Ranjith-ankam** [comment]
Still the issue is not resolved, any help would be appreciated.

**Comment by rfrerebe-stx** [comment]
You probably need to add `global` in your regions to list IAM objects as they are not linked to a particular region.

**Comment by twaslowski** [comment]
@rfrerebe-stx Ran into the same issue, adding `global` fixed it.
