### ISSUE TITLE
Several SDK Services - Credential Scope Issues

### ISSUE THREAD

**Issue by tomvachon** [rebuy-de/aws-nuke#114]
I'm unable to add cleanup for the autoscalingplans API

ERRO[0003] Listing with resources.ResourceLister failed. Please report this to https://github.com/rebuy-de/aws-nuke/issues/new.
    !!! InvalidSignatureException: Credential should be scoped to correct service: 'autoscaling-plans'.
    !!! 	status code: 400, request id: 5dbf75f6-217c-11e8-8a21-5b29c4644711
ERRO[0003] Listing with resources.ResourceLister failed. Please report this to https://github.com/rebuy-de/aws-nuke/issues/new.
    !!! InvalidSignatureException: Credential should be scoped to correct service: 'autoscaling-plans'.
    !!! 	status code: 400, request id: 5dda299d-217c-11e8-a778-f18a042972d7
ERRO[0003] Listing with resources.ResourceLister failed. Please report this to https://github.com/rebuy-de/aws-nuke/issues/new.
    !!! InvalidSignatureException: Credential should be scoped to correct service: 'autoscaling-plans'.
    !!! 	status code: 400, request id: 5e0f437a-217c-11e8-9aff-8bbaa412de1c
Scan complete: 0 total, 0 nukeable, 0 filtered.

My code is here if you see something: https://github.com/tomvachon/aws-nuke/blob/feature/autoscalingplans/resources/autoscalingplans-scalingplans.go

**Comment by svenwltr** [comment]
This looks like a bug in the AWS SDK, since we are not touching anything signature related. It is all done by the SDK.

It looks like something like this: https://github.com/aws/aws-sdk-go/issues/1009, but this one is already merged. It will take some time to figure out what is wrong here.

**Comment by tomvachon** [comment]
OK, ill move to the next service for now

**Comment by tomvachon** [comment]
mobile does too..

ERRO[0002] Listing with resources.ResourceLister failed. Please report this to https://github.com/rebuy-de/aws-nuke/issues/new.
    !!! InvalidSignatureException: Credential should be scoped to correct service: 'AWSMobileHubService'.
    !!! 	status code: 403, request id: fbf0ff1d-2216-11e8-8184-b1af4e143a3a

**Comment by tomvachon** [comment]
MediaStoreData is broken too

**Comment by svenwltr** [comment]
This is a hard one. Maybe a SDK update resolves the issues: #149.

**Comment by tomvachon** [comment]
@svenwltr looks like MediaStoreData is a bug.  I opened a Enterprise Support ticket and they are working with the service team now

**Comment by tomvachon** [comment]
@svenwltr confirmed, they have a bunch of bugs: https://github.com/aws/aws-sdk-go/issues/1850

That workaround should be ok and should be non-breaking to keep when they fix them too

**Comment by tomvachon** [comment]
I'm going to close this out, there isnt anything we can do
