### ISSUE TITLE
aws-nuke resource-types not reporting all known resource types

### ISSUE THREAD

**Issue by danbdo** [rebuy-de/aws-nuke#1145]
I was piping `aws-nuke resource-types` into `sed` to create a comprehensive filter config for all known resource types. I noticed that the call apparently doesn't actually report all known resource types. For example I see RDSSnapshot in the resource-types output. However, a nuke dry-run shows RDSClusterSnapshot resources that it would remove, which wasn't part of the resource-types output

**Comment by ekristen** [comment]
@danbdo try [this fork](https://github.com/ekristen/aws-nuke) and see if the problem still persists and open an issue over there if it does. `RDSClusterSnapshot` is definitely listed via `resource-types` command.

----

Please see the copy of the notice from the README about the deprecation of this project. Sven was kind enough to grant me access to help triage and close issues and pull requests that have already been addressed in the actively maintained fork. Some additional information is located in the [welcome issue](https://github.com/ekristen/aws-nuke/issues/276) for more information. 

> [!CAUTION]
> This repository for aws-nuke is no longer being actively maintained. We recommend users to switch to the actively maintained fork of this project at [ekristen/aws-nuke](https://github.com/ekristen/aws-nuke).
> We appreciate all the support and contributions we've received throughout the life of this project. We believe that the fork will continue to provide the functionality and support that you have come to expect from aws-nuke.
> Please note that this deprecation means we will not be addressing issues, accepting pull requests, or making future releases from this repository.
> Thank you for your understanding and support.
