### ISSUE TITLE
ERRO[0972]

### ISSUE THREAD

**Issue by juancho386** [rebuy-de/aws-nuke#1165]
Help
During the run, after the account alias verification I am getting only hundreds of errors like the following:
```
ERRO[0972] Listing IAMUserGroupAttachment failed:
    RequestError: send request failed
    caused by: Post "https://iam.amazonaws.com/": dial tcp: lookup iam.amazonaws.com on 172.21.128.1:53: read udp 172.21.143.172:35399->172.21.128.1:53: i/o timeout
```

my yaml file is like this
```
regions:
- eu-central-1
- global

account-blocklist:
- "999999999999" # fake-production because I don't have one

accounts:
  "003434343434": {} # my-account-dev
```
I am running an Ubuntu 20.04 into a WSL
I installed aws-nuke-v2.25.0-linux-amd64 as in [here](https://github.com/rebuy-de/aws-nuke#example-for-linux-intelamd)

What am I doing wrong?

**Comment by ekristen** [comment]
DNS queries are timing out on your machine. It's nothing really to do with the tool.
