### ISSUE TITLE
How to filter a resources using 2 property

### ISSUE THREAD

**Issue by yashasbc23** [rebuy-de/aws-nuke#1171]
Hello Team,

I am looking to use 2 filter pattern on single resource. Can you help me how to do this.
I want to filter IAMRole with tag:Owner and also filter with name. Because some of the IAMRole resource does not have tag:Owner which I wan to keep(Exclude from destroying).

Please let me know if you need more information.

Thanks

**Comment by ekristen** [comment]
filters are `OR` together by default, so basically if you specify 2 filters if either one matches, it'll get excluded, currently there is no way to `AND` filters together.
