### ISSUE TITLE
GO error

### ISSUE THREAD

**Issue by agroyz** [rebuy-de/aws-nuke#1180]
Hi, I have aws-nuke setup running on dedicated ec2 instance. its been working for a while now. But recently it has started with failing with the exception below.  I've watched it fail. It stops at different steps and times out. 

fatal error: runtime: out of memory

runtime stack:
runtime.throw({0x5818d81?, 0x2030?})
        /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/panic.go:1077 +0x5c fp=0xc0000f5df8 sp=0xc0000f5dc8 pc=0x438e1c
runtime.sysMapOS(0xc0db400000, 0x400000?)
        /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/mem_linux.go:142 +0x116 fp=0xc0000f5e40 sp=0xc0000f5df8 pc=0x41a2b6
runtime.sysMap(0x7f3aa8afc000?, 0x42eea0?, 0xc0000f5e60?)
        /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/mem.go:149 +0x34 fp=0xc0000f5e70 sp=0xc0000f5e40 pc=0x419d34
runtime.(*mheap).grow(0x9373d80, 0x36?)
        /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/mheap.go:1533 +0x236 fp=0xc0000f5ee0 sp=0xc0000f5e70 pc=0x42bd36
runtime.(*mheap).allocSpan(0x9373d80, 0x36, 0x0, 0x5f?)
        /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/mheap.go:1250 +0x1b0 fp=0xc0000f5f80 sp=0xc0000f5ee0 pc=0x42b450
runtime.(*mheap).alloc.func1()
        /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/mheap.go:968 +0x5c fp=0xc0000f5fc8 sp=0xc0000f5f80 pc=0x42aedc
runtime.systemstack()
        /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/asm_amd64.s:509 +0x4a fp=0xc0000f5fd8 sp=0xc0000f5fc8 pc=0x468cea

goroutine 1375 [running]:
runtime.systemstack_switch()
        /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/asm_amd64.s:474 +0x8 fp=0xc001d41858 sp=0xc001d41848 pc=0x468c88
runtime.(*mheap).alloc(0x6c000?, 0x36?, 0x80?)
        /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/mheap.go:962 +0x5b fp=0xc001d418a0 sp=0xc001d41858 pc=0x42ae3b
runtime.(*mcache).allocLarge(0x7f3aa8b1c108?, 0x6c000, 0x1?)
        /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/mcache.go:234 +0x85 fp=0xc001d418e8 sp=0xc001d418a0 pc=0x418f05
runtime.mallocgc(0x6c000, 0x0, 0x0)
        /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/malloc.go:1123 +0x4f6 fp=0xc001d41950 sp=0xc001d418e8 pc=0x410116
runtime.growslice(0xc0db344000, 0x1?, 0x1?, 0x0?, 0xc001d41a38?)
        /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/slice.go:266 +0x4cf fp=0xc001d419c0 sp=0xc001d41950 pc=0x45048f
github.com/rebuy-de/aws-nuke/v2/pkg/util.IndentBytes(...)
        /home/runner/work/aws-nuke/aws-nuke/pkg/util/indent.go:14
github.com/rebuy-de/aws-nuke/v2/pkg/awsutil.DumpResponse(0xc001d41a68?)
        /home/runner/work/aws-nuke/aws-nuke/pkg/awsutil/util.go:44 +0x165 fp=0xc001d41a38 sp=0xc001d419c0 pc=0x3b34885
github.com/rebuy-de/aws-nuke/v2/pkg/awsutil.(*Credentials).NewSession.func2(0xc0d5868f00?)
        /home/runner/work/aws-nuke/aws-nuke/pkg/awsutil/session.go:192 +0x1a fp=0xc001d41a90 sp=0xc001d41a38 pc=0x3b3497a
github.com/aws/aws-sdk-go/aws/request.(*HandlerList).Run(0xc0d5869150, 0xc0d5868f00)
        /home/runner/work/aws-nuke/aws-nuke/vendor/github.com/aws/aws-sdk-go/aws/request/handlers.go:267 +0x96 fp=0xc001d41b20 sp=0xc001d41a90 pc=0x8166d6
github.com/aws/aws-sdk-go/aws/request.(*Request).sendRequest(0xc0d5868f00)
        /home/runner/work/aws-nuke/aws-nuke/vendor/github.com/aws/aws-sdk-go/aws/request/request.go:611 +0xf2 fp=0xc001d41bd8 sp=0xc001d41b20 pc=0x819a32
github.com/aws/aws-sdk-go/aws/request.(*Request).Send(0xc0d5868f00)
        /home/runner/work/aws-nuke/aws-nuke/vendor/github.com/aws/aws-sdk-go/aws/request/request.go:555 +0x125 fp=0xc001d41c60 sp=0xc001d41bd8 pc=0x8192a5
github.com/aws/aws-sdk-go/service/s3.(*S3).ListObjectVersions(0xc0a1880000?, 0xc000514b00?)
        /home/runner/work/aws-nuke/aws-nuke/vendor/github.com/aws/aws-sdk-go/service/s3/api.go:6522 +0x1d fp=0xc001d41c88 sp=0xc001d41c60 pc=0x30f2d1d
github.com/rebuy-de/aws-nuke/v2/resources.ListS3Objects(0xc0005106c0?)
        /home/runner/work/aws-nuke/aws-nuke/resources/s3-objects.go:42 +0x17b fp=0xc001d41df0 sp=0xc001d41c88 pc=0x3b16e9b
github.com/rebuy-de/aws-nuke/v2/cmd.(*scanner).list(0xc000446290, 0xc0005106c0, {0x57e2aa7, 0x8})
        /home/runner/work/aws-nuke/aws-nuke/cmd/scan.go:60 +0x19d fp=0xc001d41fb0 sp=0xc001d41df0 pc=0x3b9279d
github.com/rebuy-de/aws-nuke/v2/cmd.(*scanner).run.func1()
        /home/runner/work/aws-nuke/aws-nuke/cmd/scan.go:37 +0x2c fp=0xc001d41fe0 sp=0xc001d41fb0 pc=0x3b925cc
runtime.goexit()
        /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc001d41fe8 sp=0xc001d41fe0 pc=0x46aae1
created by github.com/rebuy-de/aws-nuke/v2/cmd.(*scanner).run in goroutine 50
        /home/runner/work/aws-nuke/aws-nuke/cmd/scan.go:37 +0x33

goroutine 1 [chan receive, 1 minutes]:
runtime.gopark(0x1?, 0x1?, 0x0?, 0x0?, 0x4092a20?)
        /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/proc.go:398 +0xce fp=0xc0000f93c0 sp=0xc0000f93a0 pc=0x43bc4e
runtime.chanrecv(0xc0003fd380, 0xc000425578, 0x1)
        /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/chan.go:583 +0x3cd fp=0xc0000f9438 sp=0xc0000f93c0 pc=0x4099ad
runtime.chanrecv2(0xc0000aab00?, 0xc002b1c4c0?)
        /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/chan.go:447 +0x12 fp=0xc0000f9460 sp=0xc0000f9438 pc=0x4095d2
github.com/rebuy-de/aws-nuke/v2/cmd.(*Nuke).Scan(0xc0000aab00)
        /home/runner/work/aws-nuke/aws-nuke/cmd/nuke.go:166 +0x89a fp=0xc0000f9780 sp=0xc0000f9460 pc=0x3b8f57a
github.com/rebuy-de/aws-nuke/v2/cmd.(*Nuke).Run(0xc0000aab00)
        /home/runner/work/aws-nuke/aws-nuke/cmd/nuke.go:61 +0x325 fp=0xc0000f9978 sp=0xc0000f9780 pc=0x3b8e3e5
github.com/rebuy-de/aws-nuke/v2/cmd.NewRootCommand.func2(0xc000344800?, {0x57e047d?, 0x4?, 0x57e0481?})
        /home/runner/work/aws-nuke/aws-nuke/cmd/root.go:92 +0x613 fp=0xc0000f9d20 sp=0xc0000f9978 pc=0x3b91ff3
github.com/spf13/cobra.(*Command).execute(0xc0002c2300, {0xc0000b6010, 0x6, 0x6})
        /home/runner/work/aws-nuke/aws-nuke/vendor/github.com/spf13/cobra/command.go:940 +0x87c fp=0xc0000f9e58 sp=0xc0000f9d20 pc=0x3b7ef1c
github.com/spf13/cobra.(*Command).ExecuteC(0xc0002c2300)
        /home/runner/work/aws-nuke/aws-nuke/vendor/github.com/spf13/cobra/command.go:1068 +0x3a5 fp=0xc0000f9f10 sp=0xc0000f9e58 pc=0x3b7f745
github.com/spf13/cobra.(*Command).Execute(0xc0000061a0?)
        /home/runner/work/aws-nuke/aws-nuke/vendor/github.com/spf13/cobra/command.go:992 +0x13 fp=0xc0000f9f28 sp=0xc0000f9f10 pc=0x3b7f2f3
main.main()
        /home/runner/work/aws-nuke/aws-nuke/main.go:10 +0x18 fp=0xc0000f9f40 sp=0xc0000f9f28 pc=0x3b94df8
runtime.main()
        /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/proc.go:267 +0x2bb fp=0xc0000f9fe0 sp=0xc0000f9f40 pc=0x43b7fb
runtime.goexit()
        /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc0000f9fe8 sp=0xc0000f9fe0 pc=0x46aae1

goroutine 2 [force gc (idle), 1 minutes]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/proc.go:398 +0xce fp=0xc000062fa8 sp=0xc000062f88 pc=0x43bc4e
runtime.goparkunlock(...)
        /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/proc.go:404
runtime.forcegchelper()
        /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/proc.go:322 +0xb3 fp=0xc000062fe0 sp=0xc000062fa8 pc=0x43bad3
runtime.goexit()
        /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc000062fe8 sp=0xc000062fe0 pc=0x46aae1
created by runtime.init.6 in goroutine 1
        /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/proc.go:310 +0x1a

goroutine 3 [GC sweep wait]:
runtime.gopark(0x1?, 0x0?, 0x0?, 0x0?, 0x0?)
        /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/proc.go:398 +0xce fp=0xc000063778 sp=0xc000063758 pc=0x43bc4e
runtime.goparkunlock(...)
        /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/proc.go:404
runtime.bgsweep(0x0?)
        /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/mgcsweep.go:321 +0xdf fp=0xc0000637c8 sp=0xc000063778 pc=0x427c9f
runtime.gcenable.func1()
        /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/mgc.go:200 +0x25 fp=0xc0000637e0 sp=0xc0000637c8 pc=0x41cd85
runtime.goexit()
        /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc0000637e8 sp=0xc0000637e0 pc=0x46aae1
created by runtime.gcenable in goroutine 1
        /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/mgc.go:200 +0x66

goroutine 4 [GC scavenge wait]:
runtime.gopark(0x3b9d19af?, 0x3b9aca00?, 0x0?, 0x0?, 0x0?)
        /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/proc.go:398 +0xce fp=0xc000063f70 sp=0xc000063f50 pc=0x43bc4e
runtime.goparkunlock(...)
        /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/proc.go:404
runtime.(*scavengerState).park(0x935b9c0)
        /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/mgcscavenge.go:425 +0x49 fp=0xc000063fa0 sp=0xc000063f70 pc=0x425489
runtime.bgscavenge(0x0?)
        /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/mgcscavenge.go:658 +0x59 fp=0xc000063fc8 sp=0xc000063fa0 pc=0x425a39
runtime.gcenable.func2()
        /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/mgc.go:201 +0x25 fp=0xc000063fe0 sp=0xc000063fc8 pc=0x41cd25
runtime.goexit()
        /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc000063fe8 sp=0xc000063fe0 pc=0x46aae1
created by runtime.gcenable in goroutine 1
        /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/mgc.go:201 +0xa5

goroutine 17 [finalizer wait]:
runtime.gopark(0x0?, 0xc001b5b698?, 0x60?, 0xe1?, 0x1000000010?)
        /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/proc.go:398 +0xce fp=0xc00051fe28 sp=0xc00051fe08 pc=0x43bc4e
runtime.runfinq()
        /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/mfinal.go:193 +0x107 fp=0xc00051ffe0 sp=0xc00051fe28 pc=0x41be07
runtime.goexit()
        /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc00051ffe8 sp=0xc00051ffe0 pc=0x46aae1
created by runtime.createfing in goroutine 1
        /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/mfinal.go:163 +0x3d

goroutine 50 [select, 1 minutes]:
runtime.gopark(0xc00066df28?, 0x2?, 0x85?, 0x48?, 0xc00066dedc?)
        /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/proc.go:398 +0xce fp=0xc00066dd80 sp=0xc00066dd60 pc=0x43bc4e
runtime.selectgo(0xc00066df28, 0xc00066ded8, 0x938bc60?, 0x0, 0x410225?, 0x1)
        /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/select.go:327 +0x725 fp=0xc00066dea0 sp=0xc00066dd80 pc=0x44b605
golang.org/x/sync/semaphore.(*Weighted).Acquire(0xc0006482d0, {0x5f76518, 0x938a800}, 0x10)
        /home/runner/work/aws-nuke/aws-nuke/vendor/golang.org/x/sync/semaphore/semaphore.go:60 +0x314 fp=0xc00066df58 sp=0xc00066dea0 pc=0x3b8d574
github.com/rebuy-de/aws-nuke/v2/cmd.(*scanner).run(0xc000446290, 0xc0005106c0, {0xc00009e000?, 0x1a5, 0x0?})
        /home/runner/work/aws-nuke/aws-nuke/cmd/scan.go:41 +0x131 fp=0xc00066dfa8 sp=0xc00066df58 pc=0x3b92531
github.com/rebuy-de/aws-nuke/v2/cmd.Scan.func1()
        /home/runner/work/aws-nuke/aws-nuke/cmd/scan.go:22 +0x30 fp=0xc00066dfe0 sp=0xc00066dfa8 pc=0x3b923d0
runtime.goexit()
        /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc00066dfe8 sp=0xc00066dfe0 pc=0x46aae1
created by github.com/rebuy-de/aws-nuke/v2/cmd.Scan in goroutine 1
        /home/runner/work/aws-nuke/aws-nuke/cmd/scan.go:22 +0x11f

goroutine 28 [GC worker (idle)]:
runtime.gopark(0x392a5d02e37?, 0x2?, 0x25?, 0x59?, 0x0?)
        /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/proc.go:398 +0xce fp=0xc00005f750 sp=0xc00005f730 pc=0x43bc4e
runtime.gcBgMarkWorker()
        /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/mgc.go:1293 +0xe5 fp=0xc00005f7e0 sp=0xc00005f750 pc=0x41e905
runtime.goexit()
        /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc00005f7e8 sp=0xc00005f7e0 pc=0x46aae1
created by runtime.gcBgMarkStartWorkers in goroutine 12
        /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/mgc.go:1217 +0x1c

goroutine 13 [GC worker (idle)]:
runtime.gopark(0x392a5d046ec?, 0x3?, 0x35?, 0x77?, 0x0?)
        /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/proc.go:398 +0xce fp=0xc000064750 sp=0xc000064730 pc=0x43bc4e
runtime.gcBgMarkWorker()
        /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/mgc.go:1293 +0xe5 fp=0xc0000647e0 sp=0xc000064750 pc=0x41e905
runtime.goexit()
        /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc0000647e8 sp=0xc0000647e0 pc=0x46aae1
created by runtime.gcBgMarkStartWorkers in goroutine 12
        /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/mgc.go:1217 +0x1c

goroutine 3302 [IO wait]:
runtime.gopark(0xbe8c5adfc36e5f03?, 0xb?, 0x0?, 0x0?, 0x3?)
        /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/proc.go:398 +0xce fp=0xc0000355c8 sp=0xc0000355a8 pc=0x43bc4e
runtime.netpollblock(0x47ead8?, 0x407de6?, 0x0?)
        /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/netpoll.go:564 +0xf7 fp=0xc000035600 sp=0xc0000355c8 pc=0x434777
internal/poll.runtime_pollWait(0x7f3a61d36a50, 0x72)
        /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/netpoll.go:343 +0x85 fp=0xc000035620 sp=0xc000035600 pc=0x465885
internal/poll.(*pollDesc).wait(0xc00038ec00?, 0xc0da400000?, 0x0)
        /opt/hostedtoolcache/go/1.21.0/x64/src/internal/poll/fd_poll_runtime.go:84 +0x27 fp=0xc000035648 sp=0xc000035620 pc=0x4a1347
internal/poll.(*pollDesc).waitRead(...)
        /opt/hostedtoolcache/go/1.21.0/x64/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc00038ec00, {0xc0da400000, 0xa000, 0xa000})
        /opt/hostedtoolcache/go/1.21.0/x64/src/internal/poll/fd_unix.go:164 +0x27a fp=0xc0000356e0 sp=0xc000035648 pc=0x4a263a
net.(*netFD).Read(0xc00038ec00, {0xc0da400000?, 0xc0da40000d?, 0x113?})
        /opt/hostedtoolcache/go/1.21.0/x64/src/net/fd_posix.go:55 +0x25 fp=0xc000035728 sp=0xc0000356e0 pc=0x5aab65
net.(*conn).Read(0xc0d89f82e0, {0xc0da400000?, 0x9ff3?, 0xc0da400005?})
        /opt/hostedtoolcache/go/1.21.0/x64/src/net/net.go:179 +0x45 fp=0xc000035770 sp=0xc000035728 pc=0x5b77a5
net.(*TCPConn).Read(0xc000035808?, {0xc0da400000?, 0xc0da3a9da0?, 0x18?})
        <autogenerated>:1 +0x25 fp=0xc0000357a0 sp=0xc000035770 pc=0x5c6cc5
crypto/tls.(*atLeastReader).Read(0xc0da3a9da0, {0xc0da400000?, 0xc0da3a9da0?, 0x0?})
        /opt/hostedtoolcache/go/1.21.0/x64/src/crypto/tls/conn.go:805 +0x3b fp=0xc0000357e8 sp=0xc0000357a0 pc=0x60273b
bytes.(*Buffer).ReadFrom(0xc00011ed28, {0x5f1fd20, 0xc0da3a9da0})
        /opt/hostedtoolcache/go/1.21.0/x64/src/bytes/buffer.go:211 +0x98 fp=0xc000035840 sp=0xc0000357e8 pc=0x4fde98
crypto/tls.(*Conn).readFromUntil(0xc00011ea80, {0x5f1fda0?, 0xc0d89f82e0}, 0xa000?)
        /opt/hostedtoolcache/go/1.21.0/x64/src/crypto/tls/conn.go:827 +0xde fp=0xc000035880 sp=0xc000035840 pc=0x60291e
crypto/tls.(*Conn).readRecordOrCCS(0xc00011ea80, 0x0)
        /opt/hostedtoolcache/go/1.21.0/x64/src/crypto/tls/conn.go:625 +0x250 fp=0xc000035c20 sp=0xc000035880 pc=0x5ffef0
crypto/tls.(*Conn).readRecord(...)
        /opt/hostedtoolcache/go/1.21.0/x64/src/crypto/tls/conn.go:587
crypto/tls.(*Conn).Read(0xc00011ea80, {0xc0d8aad000, 0x1000, 0x3e?})
        /opt/hostedtoolcache/go/1.21.0/x64/src/crypto/tls/conn.go:1369 +0x158 fp=0xc000035c90 sp=0xc000035c20 pc=0x6061b8
net/http.(*persistConn).Read(0xc000c46240, {0xc0d8aad000?, 0xc000d94720?, 0xc000035d38?})
        /opt/hostedtoolcache/go/1.21.0/x64/src/net/http/transport.go:1954 +0x4a fp=0xc000035cf0 sp=0xc000035c90 pc=0x69ac8a
bufio.(*Reader).fill(0xc0d8ad8000)
        /opt/hostedtoolcache/go/1.21.0/x64/src/bufio/bufio.go:113 +0x103 fp=0xc000035d28 sp=0xc000035cf0 pc=0x6367a3
bufio.(*Reader).Peek(0xc0d8ad8000, 0x1)
        /opt/hostedtoolcache/go/1.21.0/x64/src/bufio/bufio.go:151 +0x53 fp=0xc000035d48 sp=0xc000035d28 pc=0x6368d3
net/http.(*persistConn).readLoop(0xc000c46240)
        /opt/hostedtoolcache/go/1.21.0/x64/src/net/http/transport.go:2118 +0x1b9 fp=0xc000035fc8 sp=0xc000035d48 pc=0x69ba79
net/http.(*Transport).dialConn.func5()
        /opt/hostedtoolcache/go/1.21.0/x64/src/net/http/transport.go:1776 +0x25 fp=0xc000035fe0 sp=0xc000035fc8 pc=0x69a2a5
runtime.goexit()
        /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc000035fe8 sp=0xc000035fe0 pc=0x46aae1
created by net/http.(*Transport).dialConn in goroutine 3291
        /opt/hostedtoolcache/go/1.21.0/x64/src/net/http/transport.go:1776 +0x169f

goroutine 3303 [select]:
runtime.gopark(0xc000702f90?, 0x2?, 0xe0?, 0x2d?, 0xc000702f1c?)
        /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/proc.go:398 +0xce fp=0xc000702db8 sp=0xc000702d98 pc=0x43bc4e
runtime.selectgo(0xc000702f90, 0xc000702f18, 0xc0d8a06540?, 0x0, 0xc0dafd46f0?, 0x1)
        /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/select.go:327 +0x725 fp=0xc000702ed8 sp=0xc000702db8 pc=0x44b605
net/http.(*persistConn).writeLoop(0xc000c46240)
        /opt/hostedtoolcache/go/1.21.0/x64/src/net/http/transport.go:2421 +0xe5 fp=0xc000702fc8 sp=0xc000702ed8 pc=0x69d445
net/http.(*Transport).dialConn.func6()
        /opt/hostedtoolcache/go/1.21.0/x64/src/net/http/transport.go:1777 +0x25 fp=0xc000702fe0 sp=0xc000702fc8 pc=0x69a245
runtime.goexit()
        /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc000702fe8 sp=0xc000702fe0 pc=0x46aae1
created by net/http.(*Transport).dialConn in goroutine 3291
        /opt/hostedtoolcache/go/1.21.0/x64/src/net/http/transport.go:1777 +0x16f1

**Comment by ekristen** [comment]
You are running out of memory. How big is the EC2 instance? How many resources are in your AWS account? Try to reduce the scope of your nuke run a bit by targeting 1 or 2 resources and see if that helps or reduce the number of regions you are targeting.

**Comment by ekristen** [comment]
@agroyz if you switch to the fork and continue to have issues. Please open an issue over on the fork. When you do please include a copy of your configuration, console output and of course the error message.

Please see the copy of the notice from the README about the deprecation of this project. Sven was kind enough to grant me access to help triage and close issues and pull requests that have already been addressed in the actively maintained fork. Some additional information is located in the [welcome issue](https://github.com/ekristen/aws-nuke/issues/276) for more information. 

> [!CAUTION]
> This repository for aws-nuke is no longer being actively maintained. We recommend users to switch to the actively maintained fork of this project at [ekristen/aws-nuke](https://github.com/ekristen/aws-nuke).
> We appreciate all the support and contributions we've received throughout the life of this project. We believe that the fork will continue to provide the functionality and support that you have come to expect from aws-nuke.
> Please note that this deprecation means we will not be addressing issues, accepting pull requests, or making future releases from this repository.
> Thank you for your understanding and support.
