### ISSUE TITLE
Add support for SageMaker Space Apps and Spaces

### ISSUE THREAD

**Issue by tbarrella-figma** [rebuy-de/aws-nuke#1184]
- [SageMakerApp](https://github.com/rebuy-de/aws-nuke/blob/main/resources/sagemaker-apps.go) doesn't support deleting apps with a SpaceName and no UserProfileName ([list ref](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/sagemaker/list-apps.html), [delete ref](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/sagemaker/delete-app.html)). This prevents deleting Spaces
  - Cloud Control also [doesn't seem to support this](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sagemaker-app.html)
- There's no support for SageMaker Spaces ([list ref](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/sagemaker/list-spaces.html), [delete ref](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/sagemaker/delete-space.html)). This prevents deleting UserProfiles/Domains with Spaces

**Comment by ekristen** [comment]
This has already been implemented over at https://github.com/ekristen/aws-nuke

----

Please see the copy of the notice from the README about the deprecation of this project. Sven was kind enough to grant me access to help triage and close issues and pull requests that have already been addressed in the actively maintained fork. Some additional information is located in the [welcome issue](https://github.com/ekristen/aws-nuke/issues/276) for more information. 

> [!CAUTION]
> This repository for aws-nuke is no longer being actively maintained. We recommend users to switch to the actively maintained fork of this project at [ekristen/aws-nuke](https://github.com/ekristen/aws-nuke).
> We appreciate all the support and contributions we've received throughout the life of this project. We believe that the fork will continue to provide the functionality and support that you have come to expect from aws-nuke.
> Please note that this deprecation means we will not be addressing issues, accepting pull requests, or making future releases from this repository.
> Thank you for your understanding and support.
