### ISSUE TITLE
Cant delete IoTThingGroup

### ISSUE THREAD

**Issue by rstalbow** [rebuy-de/aws-nuke#1199]
AWS-Nuke is failing to delete an IoT Thing Group. Here is part of the error from Cloudtrail:

```
"eventTime": "2024-03-08T13:41:37Z",
    "eventSource": "iot.amazonaws.com",
    "eventName": "DeleteThingGroup",
    "awsRegion": "eu-west-2",
    "sourceIPAddress": "3.254.22.150",
    "userAgent": "aws-sdk-go/1.44.328 (go1.21.0; linux; amd64) exec-env/AWS_ECS_FARGATE",
    "errorCode": "InvalidRequestException",
    "errorMessage": "This operation does not support dynamic thing groups. Thing group arn: arn:aws:iot:eu-west-2:730335588724:thinggroup/os-linux",
    "requestParameters": {
        "thingGroupName": "os-linux",
        "expectedVersion": 1
    },
```

I should add that I was able to delete it in the AWS Console without issue

**Comment by ekristen** [comment]
Looks like dynamic groups have to be deleted by a different API call, but they are listed with the same listing call.

**Comment by ekristen** [comment]
@rstalbow you can try my fork and builds outlined here https://github.com/ekristen/aws-nuke/pull/124#issuecomment-1998963569 to see if it fixes it.

**Comment by ekristen** [comment]
@rstalbow this was implemented and fixed via https://github.com/ekristen/aws-nuke/pull/124 on the fork that is the successor to this wonderful project. Please take a look, should you have any problems. Let me know.

----

Please see a copy of the notice from the README about the deprecation of this project. Sven was kind enough to grant me access to help triage and close issues and pull requests that have already been addressed in the actively maintained fork. Some additional information is located in the [welcome issue](https://github.com/ekristen/aws-nuke/issues/276) for more information. 

> [!CAUTION]
> This repository for aws-nuke is no longer being actively maintained. We recommend users to switch to the actively maintained fork of this project at [ekristen/aws-nuke](https://github.com/ekristen/aws-nuke).
> We appreciate all the support and contributions we've received throughout the life of this project. We believe that the fork will continue to provide the functionality and support that you have come to expect from aws-nuke.
> Please note that this deprecation means we will not be addressing issues, accepting pull requests, or making future releases from this repository.
> Thank you for your understanding and support.
