### ISSUE TITLE
Cannot delete secrets that are part of the Event Bridge connection

### ISSUE THREAD

**Issue by moltar** [rebuy-de/aws-nuke#1204]
These secrets have the following naming pattern:

```
events!connection/${NAME}/${UUID}
```

They are managed by the Event Bridge connection.

They cannot be deleted, and can only be scheduled for deletion (min 7 days).

https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-target-connection.html

**Comment by ekristen** [comment]
@moltar do you have any logs that you can share? It would be helpful to see what ResourceType is throwing the error and what the logs are. Thanks.

**Comment by moltar** [comment]
Hey @ekristen, it's just a secret from the  AWS Secrets Manager.

The difference is that it's auto-managed by Amazon EventBridge service for you.

From the docs: https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-target-connection.html

> A connection defines the authorization method and credentials for EventBridge to use in connecting to a given HTTP endpoint. When you configure the authorization settings and create a connection, **it creates a secret in AWS Secrets Manager** to securely store the authorization information.

Unfortunately, I cannot repro it at the moment, because I have already wiped it manually.

Next time I deploy and need to nuke again, I will update the error message.

**Comment by ekristen** [comment]
Tracking over in the fork.

----

Please see the copy of the notice from the README about the deprecation of this project. Sven was kind enough to grant me access to help triage and close issues and pull requests that have already been addressed in the actively maintained fork. Some additional information is located in the [welcome issue](https://github.com/ekristen/aws-nuke/issues/276) for more information. 

> [!CAUTION]
> This repository for aws-nuke is no longer being actively maintained. We recommend users to switch to the actively maintained fork of this project at [ekristen/aws-nuke](https://github.com/ekristen/aws-nuke).
> We appreciate all the support and contributions we've received throughout the life of this project. We believe that the fork will continue to provide the functionality and support that you have come to expect from aws-nuke.
> Please note that this deprecation means we will not be addressing issues, accepting pull requests, or making future releases from this repository.
> Thank you for your understanding and support.
