### ISSUE TITLE
Cannot have more than 0 builds in queue for the account 

### ISSUE THREAD

**Issue by drathbo** [rebuy-de/aws-nuke#1209]
Having the following codebuild error when running aws nuke:
Cannot have more than 0 builds in queue for the account 

and some other fluff. According to AWS there is a service quote limit (https://docs.aws.amazon.com/codebuild/latest/userguide/limits.html) that may be the culprit and in my research may require an AWS ticket to increase the quota. Has anybody else ran into this, and if so where in the codebuild is something being invoked that may pop off this error?

**Comment by drathbo** [comment]
I got this resolved through requesting additional service quotas, however I'm still not 100% what caused it.

**Comment by aneescheckit** [comment]
@drathbo I ran into similar issue and that was because of  the template I used was using `general1.2xlarge` compute type for codebuild which didn't make sense to me as that was huge for our use case. So I lowered it down to `BUILD_GENERAL1_SMALL` and that fixed issue for me. Maybe for that much computer power, your need to request limit increase.

**Comment by drathbo** [comment]
> @drathbo I ran into similar issue and that was because of the template I used was using `general1.2xlarge` compute type for Codebuild which didn't make sense to me as that was huge for our use case. So I lowered it down to `BUILD_GENERAL1_SMALL` and that fixed issue for me. Maybe for that much compute power, your need to request limit increase.
> 
> See if your template is utilising any large compute type? You might want to lower it down anyways because of pricing.

Where are you seeing these fields? Are you saying in the cloudformation template or something else that runs when the eventbridge rule is executed?

**Comment by aneescheckit** [comment]
@drathbo CloudFormation template it is. Check the compute type of CodeBuild Project inside the template, field should be `ComputeType`
