### ISSUE TITLE
Include SageMaker domains, user, user profile and space.

### ISSUE THREAD

**Issue by pomcho555** [rebuy-de/aws-nuke#1216]
The following resources are available in aws-nuke.

```yaml
    - SageMakerApp
    - SageMakerDomain
    - SageMakerEndpoint
    - SageMakerEndpointConfig
    - SageMakerModel
    - SageMakerNotebookInstance
    - SageMakerNotebookInstanceLifecycleConfig
    - SageMakerNotebookInstanceState
    - SageMakerUserProfiles
 ```

But I couldn't delete domains from this tool. It's super nice to delete domains. Please note there are some tree type dependencies to delete domains.

Reference: https://docs.aws.amazon.com/sagemaker/latest/dg/gs-studio-delete-domain.html

**Comment by npellegrin** [comment]
Without additional logs it is impossible to investigate, but Sagemaker domains likely cannot be deleted because of an associated SageMaker space.

I have opened a [PR to fix it](https://github.com/rebuy-de/aws-nuke/pull/1197) two months ago but none of the maintainers approved it...

**Comment by ekristen** [comment]
Please check out https://github.com/ekristen/aws-nuke, it has all these implemented.

If you have a chance, please check it out and let us know if you run into an issues by opening an issue over on the fork.

----

Please see the copy of the notice from the README about the deprecation of this project. Sven was kind enough to grant me access to help triage and close issues and pull requests that have already been addressed in the actively maintained fork. Some additional information is located in the [welcome issue](https://github.com/ekristen/aws-nuke/issues/276) for more information. 

> [!CAUTION]
> This repository for aws-nuke is no longer being actively maintained. We recommend users to switch to the actively maintained fork of this project at [ekristen/aws-nuke](https://github.com/ekristen/aws-nuke).
> We appreciate all the support and contributions we've received throughout the life of this project. We believe that the fork will continue to provide the functionality and support that you have come to expect from aws-nuke.
> Please note that this deprecation means we will not be addressing issues, accepting pull requests, or making future releases from this repository.
> Thank you for your understanding and support.
