### ISSUE TITLE
Can not add an alias to our accounts

### ISSUE THREAD

**Issue by michaelajr** [rebuy-de/aws-nuke#1221]
What are my options here? Our accounts are locked down. We do not have rights to add aliases. Does this mean I can not use aws-nuke?

**Comment by ekristen** [comment]
Hi @michaelajr there's an issue here #1187 in it, it talks about a fork I maintain. It's more like a next-gen fork, much of the core code has been updated and new features added, to include being able to bypass alias checks. It's still in beta, but we haven't run into any issues, working on coming out of beta soon! Docs are here https://ekristen.github.io/aws-nuke/features/bypass-alias-check/

**Comment by michaelajr** [comment]
@ekristen Wonderful. I’ll take a look. Thank you.

**Comment by ekristen** [comment]
@michaelajr as previously stated my fork has this solved. Should you run into any issues or have problems please open an issue over there.

Please see a copy of the notice from the README about the deprecation of this project. Sven was kind enough to grant me access to help triage and close issues and pull requests that have already been addressed in the actively maintained fork. Some additional information is located in the [welcome issue](https://github.com/ekristen/aws-nuke/issues/276) for more information. 

> [!CAUTION]
> This repository for aws-nuke is no longer being actively maintained. We recommend users to switch to the actively maintained fork of this project at [ekristen/aws-nuke](https://github.com/ekristen/aws-nuke).
> We appreciate all the support and contributions we've received throughout the life of this project. We believe that the fork will continue to provide the functionality and support that you have come to expect from aws-nuke.
> Please note that this deprecation means we will not be addressing issues, accepting pull requests, or making future releases from this repository.
> Thank you for your understanding and support.
