### ISSUE TITLE
i ran your tool and cant login anymore

### ISSUE THREAD

**Issue by puzzlepeaches** [rebuy-de/aws-nuke#1226]
what do?

**Comment by svenwltr** [comment]
You should still be able to login with your root account. If you forgot it you could follow https://docs.aws.amazon.com/IAM/latest/UserGuide/reset-root-password.html or otherwise contact AWS support.

**Comment by svenwltr** [comment]
You should really try to recover your account to make sure there is nothing that accumulates costs.
