### ISSUE TITLE
Delete CloudFormation Stacks in Parrallel

### ISSUE THREAD

**Issue by dnops** [rebuy-de/aws-nuke#1230]
Hi,

I would find it useful for a feature to be added to allow CloudFormation stacks to be deleted in parallel rather than waiting for each stack to delete after multiple attempts. Perhaps the delete command could be issued for each stack then aws-nuke could wait for each stack to be deleted for a period of time or maybe even ignore failures?

CFN deletes can take a decent amount of time and this delays the rest of the nuke operations significantly.

**Comment by ekristen** [comment]
I opened a tracking issue for this feature request over on [ekristen/aws-nuke](https://github.com/ekristen/aws-nuke).

This is a complicate proposal, but one worth tracking.

----

Please see a copy of the notice from the README about the deprecation of this project. Sven was kind enough to grant me access to help triage and close issues and pull requests that have already been addressed in the actively maintained fork. Some additional information is located in the [welcome issue](https://github.com/ekristen/aws-nuke/issues/276) for more information. 

> [!CAUTION]
> This repository for aws-nuke is no longer being actively maintained. We recommend users to switch to the actively maintained fork of this project at [ekristen/aws-nuke](https://github.com/ekristen/aws-nuke).
> We appreciate all the support and contributions we've received throughout the life of this project. We believe that the fork will continue to provide the functionality and support that you have come to expect from aws-nuke.
> Please note that this deprecation means we will not be addressing issues, accepting pull requests, or making future releases from this repository.
> Thank you for your understanding and support.
