### ISSUE TITLE
OperationNotPermitted: You are not allowed to manage 'ela-attach' attachments

### ISSUE THREAD

**Issue by heinosasshallik** [rebuy-de/aws-nuke#1232]
Looks like aws-nuke fails when there is a network interface that needs to be detached. From stderr:

```
level=error msg="OperationNotPermitted: You are not allowed to manage \'ela-attach\' attachments
```

Full logs (aws-nuke version 2.19.0):

* stderr: 
[awsnukefailstderr.log](https://github.com/user-attachments/files/15764741/awsnukefailstderr.log)
* stdout: 
[awsnukefailstdout.log](https://github.com/user-attachments/files/15764749/awsnukefailstdout.log)

Note: many of the errors in the stderr logs are not actually fatal. Refer to https://github.com/rebuy-de/aws-nuke/issues/1231

Tested against:

* multiple separate accounts that have network attachments. Aws-nuke failed and contained the above error in the logs
* one account that did not have a network attachment. Aws-nuke completed successfully (status code 0)

***

**Manual verification**

I initially thought the problem was related to the invalid credentials error messages or perhaps the service control policy error messages. However, that does not seem to be the case:

* I manually verified that the credentials given to aws-nuke are correct and work properly
* I manually verified the SCPs and they are the same as they have always been (errors started popping up lately, otherwise the same system has been working fine for over a year).

*** 

**Version upgrade testing**

I thought perhaps upgrading to the latest version would fix the issue. I upgraded to version 2.25.0, but I still get an error (process exit code 255). Except this time, I don't see the `ela-attach`-related error message in the logs. I'm not exactly sure what's going wrong here.

Logs:

* stderr:
[awsnuke225failstderr.log](https://github.com/user-attachments/files/15764877/awsnuke225failstderr.log)
* stdout: 
[awsnuke225failstdout.log](https://github.com/user-attachments/files/15764879/awsnuke225failstdout.log)

**Comment by heinosasshallik** [comment]
Looking through the AWS account manually, I can confirm that 2.25.0 successfully deleted the network interface. So there is some sort of other problem now

**Comment by heinosasshallik** [comment]
There are some OpenSearch errors at the bottom of the 2.25 stderr logs. I manually went through all the sidebar options in Amazon OpenSearch. Everything seems to be empty.

**Comment by heinosasshallik** [comment]
I tested version 2.25 against an account that 2.19 was able to nuke successfully and 2.25 failed to nuke that account. The logs look the same, with stderr ending with OpenSearch errors

**Comment by heinosasshallik** [comment]
Using the aws-nuke option `--exclude OSPackage` fixed the error. But I think there's some sort of bug with aws-nuke here because as far as I can tell, I haven't done anything with OpenSearch and there shouldn't be anything aws-nuke couldn't delete

**Comment by ekristen** [comment]
There seems to be a mess of errors happening. First and foremost, there seems to be issues with the credentials you are using. There are a lot of sts authentication errors or invalid security token happening.  How are you authenticating? 

The 255 error looks to be that an OpenSearch Package (OSPackage) is trying to be deleted the default packages, this has been fixed in my fork and in this code base, but a new version of 2.x has not been released with the fix.

Excluding OSPackage is a workaround for your exit 255 for now.

**Comment by heinosasshallik** [comment]
I'm authenticating to an [OrganizationAccountAccessRole](https://docs.aws.amazon.com/organizations/latest/userguide/orgs_manage_accounts_access.html) via temporary access credentials (access key, secret key, session token).

**Comment by heinosasshallik** [comment]
I'm not really sure what the credential failures could be related to. Perhaps due to credential propagation?

Then again, perhaps not. As you can see from the stderr logs, the first error that is shown is an AccessDenied error on iam:GetRole that occurs because of a service control policy. Assuming all credentials get validated against STS, it shouldn't be possible for a credential to be valid at one time (leading to the iam:GetRole failure) and then invalid later on (the expiry date is 10 hours so there's no way it would have expired that fast).

I think the `iam:GetRole` error is also a bug, by the way. I had filtered out the OrganizationAccountAccessRole in the aws-nuke config, but for some reason it's still trying to perform `iam:GetRole` against that user. Luckily it doesn't cause a failure in aws-nuke, so I've just been ignoring it

**Comment by ekristen** [comment]
Yes, filtering out of the `OrganizationAccountAccessRole` is standard, it is not done by default.

**Comment by heinosasshallik** [comment]
> Yes, filtering out of the OrganizationAccountAccessRole is standard, it is not done by default.

I'm filtering out OrganizationAccountAccessRole like this:

```
    config = {
        "regions": regions,
        "account-blocklist": [parent_account_id],
        "accounts": {
            target_account_id: {
                "filters": {
                    "IAMRole": ["OrganizationAccountAccessRole"],
                }
            }
        },
    }
```

> Since you mentioned SCP it sounds like you have SCPs that are blocking actions, this would account for a lot of the failures

I don't know. The SCP only stops anything from messing with OrganizationAccountAccessRole and the aws-nuke config filters out that role anyways. This is all the SCP does:

```
{
  "Statement": [
    {
      "Action": "*",
      "Condition": {
        "StringNotEquals": {
          "aws:PrincipalArn": "arn:aws:*::REDACTED:*/*"
        }
      },
      "Effect": "Deny",
      "Resource": "arn:aws:iam::*:role/OrganizationAccountAccessRole",
      "Sid": "ProtectAccessRole"
    },
    {
      "Action": "*",
      "Effect": "Allow",
      "Resource": "*",
      "Sid": "AllowAllActionsByDefault"
    }
  ],
  "Version": "2012-10-17"
}
```

**Comment by ekristen** [comment]
So filtering out does not stop the tool from querying. We have no insight into SCPs so it will try and discover all roles, and get details and then filter them from being targeted.

**Comment by ekristen** [comment]
It's unclear if this is still an issue. Please test the fork out and if the issue persists then open an issue there. Thank you.

----

Please see the copy of the notice from the README about the deprecation of this project. Sven was kind enough to grant me access to help triage and close issues and pull requests that have already been addressed in the actively maintained fork. Some additional information is located in the [welcome issue](https://github.com/ekristen/aws-nuke/issues/276) for more information. 

> [!CAUTION]
> This repository for aws-nuke is no longer being actively maintained. We recommend users to switch to the actively maintained fork of this project at [ekristen/aws-nuke](https://github.com/ekristen/aws-nuke).
> We appreciate all the support and contributions we've received throughout the life of this project. We believe that the fork will continue to provide the functionality and support that you have come to expect from aws-nuke.
> Please note that this deprecation means we will not be addressing issues, accepting pull requests, or making future releases from this repository.
> Thank you for your understanding and support.
