### ISSUE TITLE
ca-west-1 Not Deleting Resources

### ISSUE THREAD

**Issue by BenMorganMY** [rebuy-de/aws-nuke#1239]
Hey guys,

I'm running `aws-nuke -c nuke.yml --profile staging --no-dry-run` and when I have the regions set to `ca-west-1` here in Cowtown, it isn't deleting the RDS instances, elastic IP's, VPC records, S3 buckets, resource analyzer and views, and so on.

**Comment by ekristen** [comment]
@BenMorganMY please provide logging output.
