### ISSUE TITLE
Add Support for Redshift Serverless components

### ISSUE THREAD

**Issue by pursachi** [rebuy-de/aws-nuke#1247]
aws-nuke is unable to delete Redshift serverless workgroup and namespaces as a result of which other dependent components like VPC, VPC endpoint, Security group etc are failing to nuke.

**Comment by ekristen** [comment]
There was already a PR for this that has been merged -- https://github.com/rebuy-de/aws-nuke/pull/1194/files -- however it hasn't been released by the maintainers.  It has been released on my fork.

**Comment by ekristen** [comment]
This has been implemented at https://github.com/ekristen/aws-nuke

If you have a chance, please check it out and let us know if you run into an issues by opening an issue over on the fork.

----

Please see the copy of the notice from the README about the deprecation of this project. Sven was kind enough to grant me access to help triage and close issues and pull requests that have already been addressed in the actively maintained fork. Some additional information is located in the [welcome issue](https://github.com/ekristen/aws-nuke/issues/276) for more information. 

> [!CAUTION]
> This repository for aws-nuke is no longer being actively maintained. We recommend users to switch to the actively maintained fork of this project at [ekristen/aws-nuke](https://github.com/ekristen/aws-nuke).
> We appreciate all the support and contributions we've received throughout the life of this project. We believe that the fork will continue to provide the functionality and support that you have come to expect from aws-nuke.
> Please note that this deprecation means we will not be addressing issues, accepting pull requests, or making future releases from this repository.
> Thank you for your understanding and support.
