### ISSUE TITLE
Cannot Destroy `IOTAuthorizer`

### ISSUE THREAD

**Issue by adrians5j** [rebuy-de/aws-nuke#1251]
Recently I started creating IOT authorizers in my AWS acc, and once I run AWS Nuke, it is unable to delete them for some reason. 🤔

![image](https://github.com/user-attachments/assets/e0bf9927-8e92-47e6-a38d-7163a8a58403)

The AWS Nuke version I'm using is:
```
aws-nuke version v2.25.0.28.gbc5b576 - Sun Jul 28 03:21:05 UTC 2024 - bc5b576365682946ed90e45bbd1c2da3d9e6201c
```

Maybe it's related to the fact that, at least from the UI, you first need to deactivate an authorizer, and then delete it? 🤔

In any case, if anybody has any clue, it'd be helpful. I can also provide extra logs if needed. Just let me know!

**Comment by ekristen** [comment]
What do the logs say once it fails out? It should give the actual reason for it failing after it's tried 3 times.

**Comment by adrians5j** [comment]
Was looking at the logs, did not find anything there actually. But I see you already merged a fix, so I'll give it a try and let you know how it went!

**Comment by ekristen** [comment]
Yeah, sorry, I try to help people but not push my fork directly too much, trying to be respectful. Let me know if you run into issues. I was able to replicate it locally. :)

**Comment by ekristen** [comment]
@adrians5j  this issues has been fixed via https://github.com/ekristen/aws-nuke/pull/241

Please see a copy of the notice from the README about the deprecation of this project. Sven was kind enough to grant me access to help triage and close issues and pull requests that have already been addressed in the actively maintained fork. Some additional information is located in the [welcome issue](https://github.com/ekristen/aws-nuke/issues/276) for more information. 

> [!CAUTION]
> This repository for aws-nuke is no longer being actively maintained. We recommend users to switch to the actively maintained fork of this project at [ekristen/aws-nuke](https://github.com/ekristen/aws-nuke).
> We appreciate all the support and contributions we've received throughout the life of this project. We believe that the fork will continue to provide the functionality and support that you have come to expect from aws-nuke.
> Please note that this deprecation means we will not be addressing issues, accepting pull requests, or making future releases from this repository.
> Thank you for your understanding and support.

**Comment by adrians5j** [comment]
Thank you @ekristen 🍻🍻🍻!
