### ISSUE TITLE
Issues with Resource Deletion in AWS-Nuke: Ignoring Tag Filters for Protected Users

### ISSUE THREAD

**Issue by franciscojose-sanchezsanchez** [rebuy-de/aws-nuke#1259]
aws-nuke deletes the IAMUserGroupAttachment, IAMLoginProfile, and IAMUserPolicyAttachment resources of a user despite the user being specified in the filters (by tags) for protection. It seems that aws-nuke ignores the tag filters.

I provided the filter configuration in two different ways to facilitate the information.

The user has a tag "exception-nuke" with the value "value-for-exception" when we want to prevent deletion.

~~~
  tags-exclusion:
    filters:
      IAMLoginProfile:
      - property: tag:user:exception-nuke
        value: "value-for-exception"
      - property: tag:exception-nuke
        value: "value-for-exception"
		 
      IAMUserGroupAttachment:
      - property: tag:user:exception-nuke
        value: "value-for-exception"
      - property: tag:exception-nuke
        value: "value-for-exception"
~~~

**Comment by ekristen** [comment]
@franciscojose-sanchezsanchez it looks like the IAMLoginProfile does not support tags at the moment, you have to exclude by the username. 

The `IAMUserGroupAttachment` only supports filtering by UserName or GroupName.

Typically filtering looks something like this for both.


```yaml
filters:
  IAMUserGroupAttachment:
    - UserName -> GroupName
```


```yaml
filters:
  IAMLoginProfile:
    - UserName
```
