### ISSUE TITLE
support STS login

### ISSUE THREAD

**Issue by FernandoMiguel** [rebuy-de/aws-nuke#126]
I use aws-vault to login to aws. 
as such there is no aws access keys, only sts temporary tokens.

using --profile Default works, but is not as intuitive.

**Comment by tomvachon** [comment]
I use --profile and I dont find it too cumbersome

**Comment by FernandoMiguel** [comment]
took me a while to find the best way to run it.
maybe add a note in the docs?

**Comment by tomvachon** [comment]
Yea, that makes sense.  Its already in the --help, but you are right, the docs could use a little TLC

**Comment by FernandoMiguel** [comment]
`      --profile string             Name of the AWS profile name for accessing the AWS API. Cannot be used together with --access-key-id and --secret-access-key.`

dont see there anything about using Default

**Comment by tomvachon** [comment]
Default is the name of the profile on disk.

I am in setting up #aws-nuke on Freenode right now, so feel free to join and ask

**Comment by FernandoMiguel** [comment]
havent used IRC in a few years, but many of us are on https://signup.hangops.com/ Slack :)

**Comment by tomvachon** [comment]
I would hook up Glitter but then again, I don't own the project.  Slack might be a good idea. nothing like a 10th workspace!

**Comment by tomvachon** [comment]
I think I invited you to #aws-nuke on that workspace.  Until I talk to Sven and Marius, this should work

**Comment by svenwltr** [comment]
The STS temporary tokens consist of a Access Key ID, Secret Access Key and a Session Token, right?

**Comment by FernandoMiguel** [comment]
@svenwltr that is correct.

My original idea was for nuke to not require a profile if a sts token exists

**Comment by svenwltr** [comment]
Will be fixed in #134.

**Comment by FernandoMiguel** [comment]
for anyone coming here (probably me in a few months)
```sh
$ ./aws-nuke -c config.yml --access-key-id $AWS_ACCESS_KEY_ID --secret-access-key $AWS_SECRET_ACCESS_KEY --session-token $AWS_SESSION_TOKEN --no-dry-run
```

**Comment by bjoernhaeuser** [comment]
Is this worth updating the documentation if its unclear / not mentioned properly?
