### ISSUE TITLE
Disable and delete CloudFront distributions before depending S3 buckets

### ISSUE THREAD

**Issue by madpipeline** [rebuy-de/aws-nuke#1262]
If the S3 bucket that a CloudFront instance depends on for it's origin or logs is missing (because it was already nuked) the CloudFront distribution can no longer be deleted, thus the `aws-nuke` command will fail.

Can we set an order to the nuking process to destroy the CloudFront Distributions before the S3 buckets?

The general consensus on the internet in this situation is to recreate the S3 buckets so that the CloudFront Distributions can be deleted. This is not a good solution when we're trying to clean-up an account.

**Comment by ekristen** [comment]
@madpipeline there's an on-going feature request for ordered deletes but it's a tricky implementation that's run into issues.

This repo has been deprecated but the issues have been left open for me to triage and close, can you please open this issue over on the [actively managed fork of aws-nuke](https://github.com/ekristen/aws-nuke) and reference this one. At which time I'll close (or you can close) this issue. Thanks!

----

Please see the copy of the notice from the README about the deprecation of this project. Sven was kind enough to grant me access to help triage and close issues and pull requests that have already been addressed in the actively maintained fork. Some additional information is located in the [welcome issue](https://github.com/ekristen/aws-nuke/issues/276) for more information. 

> [!CAUTION]
> This repository for aws-nuke is no longer being actively maintained. We recommend users to switch to the actively maintained fork of this project at [ekristen/aws-nuke](https://github.com/ekristen/aws-nuke).
> We appreciate all the support and contributions we've received throughout the life of this project. We believe that the fork will continue to provide the functionality and support that you have come to expect from aws-nuke.
> Please note that this deprecation means we will not be addressing issues, accepting pull requests, or making future releases from this repository.
> Thank you for your understanding and support.
