### ISSUE TITLE
Parallelise API requests

### ISSUE THREAD

**Issue by svenwltr** [rebuy-de/aws-nuke#151]
Currently *aws-nuke* is rather slow, because it does every request sequentially. This means the process is sleeping the most of the time. Also the AWS API can probably handle a lot more requests (unfortunately I did not find any reliable documentation about this).

By parallelising the API request we can speed up *aws-nuke* a lot.

**Comment by FernandoMiguel** [comment]
based on the experience from terraform there is a _soft_ limit of 10 API calls in parallel , if you are looking at a start value

**Comment by tomvachon** [comment]
@svenwltr we need to be able to control this PER resource.  Some allow 1 request/s tops I have found

**Comment by svenwltr** [comment]
I tried a very naive approach and just paralyzed all remove queries, regardless of the resource type. The problem is not just the rate limiting (`ThrottlingException: Rate exceeded`), but also that some resource need to generate a token, which expires as soon as a second one is requested (`WAFStaleDataException: The input token is no longer current.`)

I am not sure how to continue here. Currently, I do not see an easy way to independently parallize per service with the current code base.

**Comment by tomvachon** [comment]
Parallel is really needed particularly going to overseas regions.  What
about adding switches on resources which we know are not “parallel safe”.
We can put it into stuff like WAF.

That’s the only one I’m aware of in my batch which operates like that, so
it should be easy to default it to true. Wouldn’t hurt to add a config item
which also disables it for the users if they are having an issue

**Comment by bjoernhaeuser** [comment]
Hm, I understand. Which APIs come to your mind?

I would only see:

* S3
* EC2

**Comment by tomvachon** [comment]
It’s really all of them. All of the newer APIs are highly scoped and
interdependent. Say you are in the US cleaning the up a Mumbai region setup
from your offshore team. It’s not going to end well. Most people I’ve
talked to are using this for sandbox accounts or pre-deletion which means
you hit every api in every region to ensure you got everything

**Comment by gshel** [comment]
Would be really great to revisit this 👍

**Comment by danbdo** [comment]
Not sure what the status of parallelization is these days. But I get a bunch of Rate Exceeded errors when nuking an account.

**Comment by ekristen** [comment]
Tracking here https://github.com/ekristen/aws-nuke/issues/191
