### ISSUE TITLE
resource-types exclude/include in config not working

### ISSUE THREAD

**Issue by lobeck** [rebuy-de/aws-nuke#170]
adding a `include` or `exclude` filter via `resource-types` in the config file seems to have no effect.

resources are checked and removed anyway.

example config:

```
resource-types:
  include:
  - foo
  exclude:
  - S3Bucket
```

i've added a printf after the `yaml.Unmarshal` in `config.go` and the returned values are empty:

`ResourceTypes:{Targets:[] Excludes:[]}}] ResourceTypes:{Targets:[] Excludes:[]}`

I guess this is caused because `types.Collection` is used for these values and there seems to be no custom unmarshaler for this type.

**Comment by svenwltr** [comment]
It actually is `excludes` and `targets`. Where did you get the names from? I found one occurrence of `exclude` and fix it in #171.

Another issue is that *aws-nuke* should print an error when there is an unknown config field.

**Comment by lobeck** [comment]
> Another issue is that aws-nuke should print an error when there is an unknown config field.

Afaik Unmarshal will just ignore them, but UnmarshalStrict should bring the desired behaviour.
