### ISSUE TITLE
Unable to remove S3 buckets if versioning is enable

### ISSUE THREAD

**Issue by asdz** [rebuy-de/aws-nuke#175]
As per title, when there's versioning enable on S3 bucket with files, aws-nuke won't be able to remove the old versions.
Instead it will show an error message:-
"BucketNotEmpty: The bucket you tried to delete is not empty. You must delete all versions in the bucket.
        status code: 409, request id: XXXXXXXXXXXXX, host id: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"

**Comment by svenwltr** [comment]
This should be already fixed in #76, but the fix was not release yet. I just did an alpha release, where deleting versioned S3 Objects should properly work: https://github.com/rebuy-de/aws-nuke/releases/tag/v2.0.0-alpha1
