### ISSUE TITLE
Running via assumed role

### ISSUE THREAD

**Issue by leozhad** [rebuy-de/aws-nuke#185]
I am trying to run aws-nuke from my master AWS account, which is blacklisted -- but from which I am assuming a role into the target account I want nuked. When I try to do this (via the --profile option), I get this: 

```Error: You are trying to nuke the account with the ID XXXXXXXXXX, but it is blacklisted. Aborting.```

I think this error is wrong though, since I am using the blacklisted account to assume a role into the account I actually want to nuke.

**Comment by svenwltr** [comment]
I am not able to reproduce this. Could you please try the command `aws --profile XXX sts get-caller-identity` and check whether the protected or the other one is displayed there?

**Comment by leozhad** [comment]
When I try it, I get the account ID of the account I am trying to nuke:
```
{
    "Account": "YYYYYYYYYY",
    "UserId": "AROAIXXXXXXXXXXXXXX:AWS-CLI-session-1524764491",
    "Arn": "arn:aws:sts::YYYYYYYYYY:assumed-role/Admin/AWS-CLI-session-1524764491"
}
```

Here is what my nuke config looks like:

```
regions:
- us-east-1
- us-east-2
- us-west-1
- us-west-2

account-blacklist:
- "XXXXXXXXXXX" # prod account

resource-types:
  targets:
    - S3Object
    - S3Bucket
    - EC2Instance

accounts:
  "YYYYYYYYYY": {} # training 1
```

Here is my ~/.aws/config:

```
[default]
region = us-east-1
aws_access_key_id = ZZZZZZZZZZZ
aws_secret_access_key = VVVVVVVVVVVVVV
s3 =
    signature_version = s3v4
emr =
    service_role = EMR_DefaultRole
    instance_profile = EMR_EC2_DefaultRole

[profile training1]
role_arn=arn:aws:iam::YYYYYYYYYY:role/Admin
source_profile=default
```

**Comment by tomvachon** [comment]
@leozhad can you email me on my work email the verbose output?  I think you still know it ;)

I haven't see this either.  Please also provide your AWS account alias too

**Comment by leozhad** [comment]
Looks like this issue was something in my environment.

**Comment by hdpoe** [comment]
@leozhad  What was the issue in your environment? I am experiencing the same issue and can't seem to make any progress.

**Comment by hdpoe** [comment]
Wanted to leave an update for any other poor soul hitting this issue. It turns out you cannot have the AWS environment variables set or aws-nuke won't work. So if you unset 
`AWS_SECRET_ACCESS_KEY` and `AWS_ACCESS_KEY_ID` and ensure that the `.aws/config` and `.aws/creds` file are setup to allow you to assume a role into an account it should solve your issue. 

I am running on Ubuntu 18.04 
aws-nuke version has the following output
```
version:     v2.10.0
build date:  Wed Apr 17 09:54:52 UTC 2019
scm hash:    4d614f17b44a178746fc8d86fd94d1f3734eb642
environment: root@43f3cdac9d19
```
Hopefully this helps some poor googler in the future.
