### ISSUE TITLE
Include AWS CLI Profile in config file per account

### ISSUE THREAD

**Issue by leozhad** [rebuy-de/aws-nuke#187]
Let's say I have 20 AWS accounts, each of which involve a different AWS CLI profile stored in ~/.aws/config -- it would be awesome if I could include which AWS CLI profile it should use in my config file -- per account, so I don't have to for loop through running aws-nuke with 20 different config files.

**Comment by tomvachon** [comment]
Leo wants to be able to set the aws credential profile per account in the
config so he can have unique ones running concurrently

**Comment by svenwltr** [comment]
Does this mean to omit the profile completely and switch between account via the config file?

Currently it is intended to have a single config file for all accounts. From the README:

> To ensure to not accidentally delete a random account, it is required to specify a config file. It is recommended to have only a single config file and add it to a central repository. This way the account blacklist is way easier to manage and keep up to date.

Otherwise the blacklist feature gets some sort of unreliable, because a company/organization-unit/user would have to update multiple config when adding new production accounts. 

Since this is a precaution for production accounts, I dislike to change that. But if someone think this doesn't make sense we can talk about this.

**Comment by leozhad** [comment]
My use case is -- let's say I have 40 accounts I want to nuke -- each are
associated with a different profile in my ~/.aws/config -- which is
assuming a role in each account. How can I use one invocation of aws-nuke
for this? Right now, I just have a config file for each account, and for
loop through each one with one invocation of aws-nuke per account.

**Comment by svenwltr** [comment]
So I guess your script currently looks somehow like this:

```bash
aws-nuke --profile acc1 --config ./nuke-acc1.yaml
aws-nuke --profile acc2 --config ./nuke-acc2.yaml
aws-nuke --profile acc3 --config ./nuke-acc3.yaml
aws-nuke --profile acc4 --config ./nuke-acc4.yaml
```

I think it is more safe to use a single config file for all accounts, so there is only a single place to update filters and the account blacklist:

```bash
aws-nuke --profile acc1 --config ./nuke.yaml
aws-nuke --profile acc2 --config ./nuke.yaml
aws-nuke --profile acc3 --config ./nuke.yaml
aws-nuke --profile acc4 --config ./nuke.yaml
```

Anyway, would the ability to specify the profile multiple times solve your problem? Something like this:

```bash
aws-nuke --profile acc1 --profile acc2 --profile acc3 --profile acc4 --config ./nuke.yaml
```

**Comment by leozhad** [comment]
Yes -- that would be great. Would it then also know which role to assume out of .AWS/config -- assuming they had the same names as the profiles in the aws nuke config file?

**Comment by svenwltr** [comment]
Ok. I will take a look how we can implement this. This might take a while.

The configuration does not contain any profile names. The whole filtering is only based on the account ID.

**Comment by rhysjtevans** [comment]
Hi folks,
I've just discovered aws-nuke and really like it. I have the identical use case but I would have thought it would have made most sense to do something like the following?
```
---
regions:
- "global"
- "eu-west-1"

account-blacklist:
- 1234567890

accounts:
  555133742:
    role_arn: "arn:......"
    filters:....
```

**Comment by optplx** [comment]
hi there, I am also interested in this feature, and I like the proposal from @rhysjtevans . Looking at the code, it looks like a pretty big change though. Is this still something being considered?

**Comment by ekristen** [comment]
If this is still a desired feature, I'll consider it, please open an issue at https://github.com/ekristen/aws-nuke

----

Please see the copy of the notice from the README about the deprecation of this project. Sven was kind enough to grant me access to help triage and close issues and pull requests that have already been addressed in the actively maintained fork. Some additional information is located in the [welcome issue](https://github.com/ekristen/aws-nuke/issues/276) for more information. 

> [!CAUTION]
> This repository for aws-nuke is no longer being actively maintained. We recommend users to switch to the actively maintained fork of this project at [ekristen/aws-nuke](https://github.com/ekristen/aws-nuke).
> We appreciate all the support and contributions we've received throughout the life of this project. We believe that the fork will continue to provide the functionality and support that you have come to expect from aws-nuke.
> Please note that this deprecation means we will not be addressing issues, accepting pull requests, or making future releases from this repository.
> Thank you for your understanding and support.
