### ISSUE TITLE
Release v2.0.0

### ISSUE THREAD

**Issue by svenwltr** [rebuy-de/aws-nuke#190]
I want to release v2.0.0 soon, since there a quite a lot of issues which are already solved.

@rebuy-de/prp-aws-nuke Do you see any problems which we still need to tackle before doing the release? 

/cc @tomvachon Also, do you have anything important we have missed to do?

**Comment by stephanlindauer** [comment]
no objections from my side

**Comment by bjoernhaeuser** [comment]
lets do it :)

**Comment by svenwltr** [comment]
Done: https://github.com/rebuy-de/aws-nuke/releases/tag/v2.0.0
