### ISSUE TITLE
Take AWS Keys/Tokens from Environment

### ISSUE THREAD

**Issue by leflamm** [rebuy-de/aws-nuke#201]
Hi, IIUC if I don't want to use `--profile` I have to specify the AWS keys, ids and tokens explicitely like 

```
$ aws-nuke-v2.0.1-linux-amd64 -c <someconfig> --access-key-id <foo> --secret-access-key <bar> --session-token <baz>
```

It didn't seem to work to implicitly have those values taken out of the usual environment variables: `AWS_ACCESS_KEY_ID`, `AWS_SECRET_ACCESS_KEY` and `AWS_SESSION_TOKEN`. Would simplify the usage of this great tool massively.

Would you consider this. If I get pointed into the right direction I could provide a PR myself. Thx, Christian.

**Comment by svenwltr** [comment]
Hello @leflamm,

thanks for your issue. This feature is missing on purpose. *aws-nuke* is a very destructive tool and environment variables are usually invisible. You could for example pick up an old terminal, thinking that you are in a specific environment, but you actually are not. [This kind of stuff happens](https://blog.travis-ci.com/2018-04-03-incident-post-mortem). One could argue, that *aws-nuke* has enough other features to prevent this, but I would say you could not have enough of these.

Do you have another opinion? What does @rebuy-de/prp-aws-nuke think?

**Comment by leflamm** [comment]
Hi @svenwltr, I understand your concern.

Typically we use https://github.com/leflamm/afpre to provide AWS CLI environments like this ...
```
~$ afpre --account=stage12
token expired - need to renew...
authenticating as <some user> for stage12/admin against <some afp host>
done.
AFP|admin@stage12 ~$ 
```
... which also provides some visual confirmation about the current role and account. 

I wouldn't want this implemented as default behavior, but a switch to enable it. A simple alternative would of course be a wrapper script just passing data from the environment to the command.

Cheers, Christian

**Comment by fvant** [comment]
Eventually found this issue that explained why my AWS_SESSION_TOKEN  was not respected..perhaps add a line about it in the README ?
