### ISSUE TITLE
Use AWS SDK v2

### ISSUE THREAD

**Issue by svenwltr** [rebuy-de/aws-nuke#222]
AWS will release a new AWS SDK soon. See https://github.com/aws/aws-sdk-go-v2.

**Comment by ekristen** [comment]
Being tracked on the fork at https://github.com/ekristen/aws-nuke/issues/187

----

Please see the copy of the notice from the README about the deprecation of this project. Sven was kind enough to grant me access to help triage and close issues and pull requests that have already been addressed in the actively maintained fork. Some additional information is located in the [welcome issue](https://github.com/ekristen/aws-nuke/issues/276) for more information. 

> [!CAUTION]
> This repository for aws-nuke is no longer being actively maintained. We recommend users to switch to the actively maintained fork of this project at [ekristen/aws-nuke](https://github.com/ekristen/aws-nuke).
> We appreciate all the support and contributions we've received throughout the life of this project. We believe that the fork will continue to provide the functionality and support that you have come to expect from aws-nuke.
> Please note that this deprecation means we will not be addressing issues, accepting pull requests, or making future releases from this repository.
> Thank you for your understanding and support.
