### ISSUE TITLE
Request for Release of Changes since v2.3.0

### ISSUE THREAD

**Issue by leflamm** [rebuy-de/aws-nuke#243]
Kind request to benefit from newest changes w/o having to use private builds :-)

Thanks in advance + Cheers!

**Comment by svenwltr** [comment]
See https://github.com/rebuy-de/aws-nuke/releases/tag/v2.4.0. The binaries should get uploaded soon.

There is still a problem with the CloufFormation stacks. I added some notes to the release.

**Comment by leflamm** [comment]
Thx!
