### ISSUE TITLE
Clear steps to use the tool

### ISSUE THREAD

**Issue by aws25** [rebuy-de/aws-nuke#246]
The README.md file is not very clear on the usage of the tool. For example, something like below would be helpful 

step 1. git clone https://github.com/rebuy-de/aws-nuke.git
step 2. cd aws-nuke
step 3. ??
step 4. ??
step 5. ??

**Comment by srij91** [comment]
I think the main idea around releasing binaries was so that people can copy them to their bin folder and get going with an alias. If you're cloning the repo and trying to compile the binary yourself then one should already be aware of that process. No?

**Comment by svenwltr** [comment]
@srij91 Is right. You do not need to clone and compile this by yourself, if you do not want to develop it. Therefore you do not need to clone it.

There is already [an install section](https://github.com/rebuy-de/aws-nuke#install). What do you think is missing there?

**Comment by aws25** [comment]
How I install "aws-nuke-v2.4.0-linux-amd64" on my linux box ? tried "yum install aws-nuke-v2.4.0-linux-amd64" and it didn't work..

**Comment by aws25** [comment]
Also I need to Install  Glide, golint and GNU Make. Below is the error I get when I have installed Glide.

curl https://glide.sh/get | sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4833  100  4833    0     0   5505      0 --:--:-- --:--:-- --:--:--  5504
ARCH=amd64
OS=linux
Using curl as download tool
Getting https://glide.sh/version
TAG=v0.13.1
GLIDE_DIST=glide-v0.13.1-linux-amd64.tar.gz
Downloading https://github.com/Masterminds/glide/releases/download/v0.13.1/glide-v0.13.1-linux-amd64.tar.gz
which: no glide in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin:/usr/local/go/bin:/usr/local/go/bin:/home/vmohana/.local/bin:/home/vmohana/bin)
glide not found. Did you add $GOBIN to your $PATH?
Fail to install glide

**Comment by aws25** [comment]
go env
GOARCH="amd64"
GOBIN="/home/vmohana/projects/bin"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/vmohana/projects/src"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build292349022=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"

**Comment by DMVamsi** [comment]
./aws-nuke-v2.4.0-darwin-amd64
-bash: ./aws-nuke-v2.4.0-darwin-amd64: cannot execute binary file
I am running Linux 3.10.0-693.el7.x86_64 ---- x86_64 x86_64 x86_64 GNU/Linux

**Comment by aws25** [comment]
./aws-nuke-v2.4.0-darwin-amd64
-bash: ./aws-nuke-v2.4.0-darwin-amd64: cannot execute binary file
I am running Linux 3.10.0-693.el7.x86_64 ---- x86_64 x86_64 x86_64 GNU/Linux

**Comment by svenwltr** [comment]
@aws25 This means you need the linux binary. `darwin` is the OSX architecture.

**Comment by aws25** [comment]
Thanks svenwltr.. and now 
./aws-nuke-v2.4.0-linux-amd64
Error: You have to specify the --config flag.

**Comment by bjoernhaeuser** [comment]
Now you need to read the complete documentation :)

**Comment by aws25** [comment]
:) Like the pre-req have been met (Glide, golint and GNU Make) are already installed.

**Comment by aws25** [comment]
Do I need to "Compile from Source" ?

**Comment by fredshino** [comment]
Don't be lazy man. You need to read the readme file. More specifically the "Usage" section.

**Comment by egarbi** [comment]
@aws25 No need to compile if you are using a binary.
you need just to create a file to use a config and pass it as an argument.
Its all there in the README.

At first you need to create a config file for aws-nuke. This is a minimal one:
```
regions:
- eu-west-1

account-blacklist:
- "999999999999" # production

accounts:
  "000000000000": {} # aws-nuke-example
```
With this config we can run aws-nuke:
```
$ aws-nuke -c config/nuke-config.yml --profile aws-nuke-example
```

**Comment by aws25** [comment]
Apologies for the trouble but, "aws-nuke" dosen't work yet. I am under the impression to install "aws-nuke-v2.4.0-linux-amd64."

I am trying to delete all the resources in the account with alias testnuke01

 aws-nuke -c config/nuke-config.yml --profile testnuke01
bash: aws-nuke: command not found...

**Comment by srij91** [comment]
It depends on what alias you gave to the actual binary.  Looks like you haven't given one. Try 
./aws-nuke-v2.4.0-linux-amd64 -c config/nuke-config.yml --profile testnuke01 as per your earlier comment

**Comment by fredshino** [comment]
Spot the difference:

> ./aws-nuke-v2.4.0-linux-amd64 -c config/nuke-config.yml --profile testnuke01

> ./aws-nuke-v2.4.0-linux-amd64/nuke-config.yml --profile testnuke01

**Comment by egarbi** [comment]
at this point I think @aws25  is just playing with us.

**Comment by aws25** [comment]
@egarbi by no means I meant that, I am probably confused.

./aws-nuke-v2.4.0-linux-amd64 -c config/nuke-config.yml --profile testnuke01
Error: NoCredentialProviders: no valid providers in chain. Deprecated.
        For verbose messaging see aws.Config.CredentialsChainVerboseErrors

**Comment by aws25** [comment]
./aws-nuke-v2.4.0-linux-amd64 -c config/nuke-config.yml --access-key-id XXXXXXXXX--secret-access-key XXXXXXXX
ERRO[0005] Failed to parse config file.
Error: open config/nuke-config.yml: no such file or directory

I have the below file in my present working directory
-rw-rw-r--. 1 aws25 aws25       267 Aug 29 10:37 nuke-config.yml

 $cat nuke-config.yml
regions:
- us-east-1

accounts:
  "596151608783": # aws-nuke-example
    filters:
      IAMUser:
      - "aws25"
      IAMUserPolicyAttachment:
      - "aws25 -> AdministratorAccess"
      IAMUserAccessKey:
      - "aws25 -> XXXXXXXXXXXX

**Comment by aws25** [comment]
./aws-nuke-v2.4.0-linux-amd64 -c config/nuke-config.yml --access-key-id XXXXXXXXX--secret-access-key XXXXXXXX
ERRO[0005] Failed to parse config file.
Error: open config/nuke-config.yml: no such file or directory

I have the below file in my present working directory
-rw-rw-r--. 1 aws25 aws25       267 Aug 29 10:37 nuke-config.yml

 $cat nuke-config.yml
regions:
- us-east-1

accounts:
  "XXXXXXXXX": # aws-nuke-example
    filters:
      IAMUser:
      - "aws25"
      IAMUserPolicyAttachment:
      - "aws25 -> AdministratorAccess"
      IAMUserAccessKey:
      - "aws25 -> XXXXXXXXXXXX

**Comment by egarbi** [comment]
```
./aws-nuke-v2.4.0-linux-amd64 -c nuke-config.yml --access-key-id XXXXXXXXX--secret-access-key XXXXXXXX
```

**Comment by srij91** [comment]
Wow. This issue seems more of a PEBKAC. Can we close this?

**Comment by egarbi** [comment]
@srij91 its definitely a PICNIC, close it

**Comment by aws25** [comment]
That worked, thanks @egarbi .. Apologies for the trouble.

**Comment by spacefuntus** [comment]
While running nuke 2.10 after few resources the terminal is getting killed. Any idea why ? 
like below
us-east-1 - S3Bucket - s3://www.asdfasd.xlab.aws.net - would remove
us-east-1 - S3Bucket - s3://www.asdfa.com - would remove
us-east-1 - S3Bucket - s3://www.dev.brmartec.com - would remove
Killed

**Comment by spacefuntus** [comment]
I got that.. Memory issue.
