### ISSUE TITLE
IAMRole not nukable

### ISSUE THREAD

**Issue by gdhgdhgdh** [rebuy-de/aws-nuke#248]
Hello,

Using the 2.4.0-darwin binary and this sample config:

```
regions:
  - eu-west-2

account-blacklist:
  - "999999999999"

resource-types:
  targets:
    - IAMRole

accounts:
  "07xxxxxxxxxx": {}
```

and this commandline:

```
$ ./aws-nuke-v2.4.0-darwin-amd64 -c aws-nuke.yml --profile testaccount
```

I'm told `Scan complete: 0 total, 0 nukeable, 0 filtered.` yet there are dozens of IAM roles active in this account:

```
15:46 $ AWS_PROFILE=testaccount aws iam list-roles | grep -c RoleId
31
```

If I remove the `resource-types` stanza, then `aws-nuke` will happily list hundreds of EC2 instance, S3 objects, DynamoDB table items, etc..... but no IAM roles

What am I doing wrong?

**Comment by svenwltr** [comment]
Hello @gdhgdhgdh,

IAM Roles are a global resource. This means you have to add `global` to the `regions` list.

We probably should express that in the README somehow.

**Comment by gdhgdhgdh** [comment]
Beautiful, thank you.

I'd got half-way there by trying `us-east-1` since that's something of a 'magic region' for billing, but yeah a mention in the `README` would be useful :)

👍 on the super fast reply, and thanks for such useful software!
