### ISSUE TITLE
Compress release assets

### ISSUE THREAD

**Issue by markphelps** [rebuy-de/aws-nuke#249]
Hi,

I was starting to work on creating a Homebrew formula to fix #125, and noticed that the release binaries are not compressed. 

Would it be possible to add compressed versions of the binaries as well? This would allow brew to download the binary more quickly which on slow connections would be very beneficial IMO.

The file is almost 10x smaller when gzipped:

```
❯ ls -lh aws-nuke*
-rw-r--r--@ 1 mark  wheel   103M Aug 20 05:54 aws-nuke
-rw-r--r--  1 mark  wheel    16M Aug 28 14:14 aws-nuke.tar.gz
```

**Comment by svenwltr** [comment]
Will be fixed in #250.

I already took a look at goreleaser, but I did not figure out how to inject the version into the binary with it, yet. Might be worth a separate ticket to discuss this.
