### ISSUE TITLE
aws-nuke command

### ISSUE THREAD

**Issue by MichaJack** [rebuy-de/aws-nuke#256]
Hay guys, thanks for developing such a cool tool. It does all the magic I ever wanted.

I really did not want to create an issue here for a silly thing. I am able to accomplish my work but then a bit hesitant to ask a dumb question: how do I use the command aws-nuke. All I am using is the binary to nuke out my environment. Would be good to use a simple command instead of calling the executable in CWD.

**Comment by Spea** [comment]
I'm not sure if I get your point. Is the issue that you have to go to a certain directory in order to execute the binary?

**Comment by Spea** [comment]
As @srij91 already said, you can crate an alias 

```bash
alias aws-nuke='/path/to/your/binary/aws-nuke-v2.4.0-linux-amd64'
``` 

or move the binary to a path which is also in your `$PATH` environment e.g.

```bash
mv /path/to/your/binary/aws-nuke-v2.4.0-linux-amd64 /usr/local/bin/aws-nuke
chmod u+x /usr/local/bin/aws-nuke
aws-nuke -c ...
```

**Comment by MichaJack** [comment]
Perfect, proved I am dumb !! Thanks Guys
