### ISSUE TITLE
Remove Termination Protection for ELB before deleting

### ISSUE THREAD

**Issue by root360-AndreasUlm** [rebuy-de/aws-nuke#258]
Hi,

we used aws-nuke to cleanup an account and encountered a deletion problem.
When an LB has an active termination protection it cannot be removed by nuke:
`eu-central-1 - ELBv2 - <name> - OperationNotPermitted: Load balancer 'arn:aws:elasticloadbalancing:eu-central-1:<accountid>:loadbalancer/app/<name>/<id>' cannot be deleted because deletion protection is enabled
`

IMHO nuke should remove the termination protection first and then issue the deletion request.

Is there a reason why nuke does not resolve this dependency?

Regards,
Andreas

**Comment by philippevidal80** [comment]
Hello any update on this issue ?

**Comment by ekristen** [comment]
tracked via https://github.com/ekristen/aws-nuke/issues/350

----

Please see the copy of the notice from the README about the deprecation of this project. Sven was kind enough to grant me access to help triage and close issues and pull requests that have already been addressed in the actively maintained fork. Some additional information is located in the [welcome issue](https://github.com/ekristen/aws-nuke/issues/276) for more information. 

> [!CAUTION]
> This repository for aws-nuke is no longer being actively maintained. We recommend users to switch to the actively maintained fork of this project at [ekristen/aws-nuke](https://github.com/ekristen/aws-nuke).
> We appreciate all the support and contributions we've received throughout the life of this project. We believe that the fork will continue to provide the functionality and support that you have come to expect from aws-nuke.
> Please note that this deprecation means we will not be addressing issues, accepting pull requests, or making future releases from this repository.
> Thank you for your understanding and support.
