### ISSUE TITLE
Filtered Resources Causing Performance Issues

### ISSUE THREAD

**Issue by scottybrisbane** [rebuy-de/aws-nuke#262]
As part of our workflow to run aws-nuke, we nuke all S3Objects and S3Buckets in our account. One of the buckets in the account is our cloudtrail log bucket, which we don’t want to delete, so we filter out this bucket. Due to the buckets size and the sheer number of objects in it, the process of listing every single object in the bucket causes considerable performance problems. Having looked around the code, I’m not yet sure how this problem could best be overcome. Ideally in this case, the cloudtrail log bucket would be completely ignored by aws-nuke.

**Comment by svenwltr** [comment]
Unfortunately I also don't see much possibilities to address that. Just these two:

* add option to hide filtered resources in the output and see if this improves the performance
  * additionally utilize Go channels even more, so the objects are not in memory for too long
* parameterize the listing of resources (ie tell the s3 object lister to skip certain buckets)

The first one is quite easy to implement (at least the first part), but I am not sure if this would actually have a performance impact. The second one has the problem, that I don't have a good idea how the configuration for this should look like.

/cc @rebuy-de/prp-aws-nuke
