### ISSUE TITLE
ERRO[0007] Listing DynamoDBTable failed.  [Release: v2.5.0]

### ISSUE THREAD

**Issue by ajobayer** [rebuy-de/aws-nuke#265]
ERRO[0007] Listing DynamoDBTable failed. Please report this to https://github.com/rebuy-de/aws-nuke/issues/new.
    !!! AccessDeniedException: User: arn:aws:iam::<AWS A/C No>:user/admin-to-run-nuke is not authorized to perform: dynamodb:ListTables on resource: *
    !!!         status code: 400, request id:

**Comment by svenwltr** [comment]
What permissions does the user `admin-to-run-nuke` have? Is he allowed to list DynamoDB tables? Can you do a `aws dynamodb list-tables` on the CLI with these permissions?

**Comment by ajobayer** [comment]
admin-to-run-nuke: This role has full access (AdministratorAccess; AmazonDynamoDBFullAccess)
As well as run the command: 
An error occurred (AccessDeniedException) when calling the ListTables operation: User: arn:aws:iam::<Account>:user/admin-to-run-nuke is not authorized to perform: dynamodb:ListTables on resource: *

I guess it's not aws-nuke issue. Do you have any clue? Highly appreciated and thanks in advanced if you could help me regarding this.

**Comment by svenwltr** [comment]
@ajobayer It looks like the user does not have this permissions. You should double check this.

Besides that there could be additional policies which can deny access to parts of the API and there is a new thing called "Permission Boundaries" which could make AWS deny your request. You should check those both too.

**Comment by ekristen** [comment]
Closing due to age. Please test v3 at https://github.com/ekristen/aws-nuke, if still an issue, open an issue there. Thank you.

----

Please see the copy of the notice from the README about the deprecation of this project. Sven was kind enough to grant me access to help triage and close issues and pull requests that have already been addressed in the actively maintained fork. Some additional information is located in the [welcome issue](https://github.com/ekristen/aws-nuke/issues/276) for more information. 

> [!CAUTION]
> This repository for aws-nuke is no longer being actively maintained. We recommend users to switch to the actively maintained fork of this project at [ekristen/aws-nuke](https://github.com/ekristen/aws-nuke).
> We appreciate all the support and contributions we've received throughout the life of this project. We believe that the fork will continue to provide the functionality and support that you have come to expect from aws-nuke.
> Please note that this deprecation means we will not be addressing issues, accepting pull requests, or making future releases from this repository.
> Thank you for your understanding and support.
