### ISSUE TITLE
Document required permissions and improve error output

### ISSUE THREAD

**Issue by svenwltr** [rebuy-de/aws-nuke#266]
On missing permissions, we currently print something like this:

```
ERRO[0007] Listing DynamoDBTable failed. Please report this to https://github.com/rebuy-de/aws-nuke/issues/new.
!!! AccessDeniedException: User: arn:aws:iam::<AWS A/C No>:user/admin-to-run-nuke is not authorized to perform: dynamodb:ListTables on resource: *
!!! status code: 400, request id:
```

This causes user to actually fill issues, for missing permissions (#247, #264, #265). We should change the error output is the error is a `AccessDeniedException`. Also we should document which permissions are required (ie Admin access plus KMS permissions).

**Comment by zvictor** [comment]
Following the `Least privilege` principle, how can I define the minimum level of permissions for a given `aws-nuke-agent` user?

Or am I supposed to not create a user to run `aws-nuke`?
I am confused by the fact that AWS' best practices force me to have my CLI configured with permissions that are too restrictive for `aws-nuke` and I don't see anywhere here an explanation on how to set users up for nuking.
