### ISSUE TITLE
Nuking accounts in an aws organisation

### ISSUE THREAD

**Issue by AnujSehgall** [rebuy-de/aws-nuke#268]
```
regions:
- global
- us-east-1

account-blacklist:
- "xxxxxxxxxxxx" # prod

accounts:
  "yyyyyyyyyyyy": {} # stage
```

Above is the content of my congif.yml  file.

On nuking I'm getting "Error: You are trying to nuke the account with the ID xxxxxxxxxxxx, but it is blacklisted. Aborting." But I'm trying to nuke "yyyyyyyyyyyy" not "xxxxxxxxxxxx"

**Comment by AnujSehgall** [comment]
@svenwltr 
 So can I nuke another account present in my organization without changing the profile configuration?

**Comment by svenwltr** [comment]
@AnujSehgall I am not sure if I understand you correctly.

Any account you want to nuke must be in the `accounts` list and must not be in the `account-blacklist`.

Also the AWS Profile or AWS Credentials must point to the account you actually want to nuke.

**Comment by AnujSehgall** [comment]
Thank you @svenwltr 
I think I've got the exact area where I'm going wrong.
Closing the topic.
