### ISSUE TITLE
 CloudFormation resource retention tries to retain resources in DELETE_COMPLETE state 

### ISSUE THREAD

**Issue by scottybrisbane** [rebuy-de/aws-nuke#270]
I'm seeing a lot of the following errors on CloudFormation stack deletion:
```
ValidationError: The specified resources to retain must be in a valid state. Do not specify resources that are in the DELETE_COMPLETE state.
```
Digging a little deeper, it seems to be caused by the resource retention logic for cloudformation stacks not filtering resources to retain based on their state. It is trying to retain resources that are in a `DELETE_COMPLETE` state.

**Comment by svenwltr** [comment]
@stephanlindauer Can you take a look?

**Comment by stephanlindauer** [comment]
@scottybrisbane 
can you verify if https://github.com/rebuy-de/aws-nuke/pull/271 fixes your issues?
alternatively: can you give me a pointer on how to reproduce the scenario under which this would usually fails?

**Comment by scottybrisbane** [comment]
@stephanlindauer Looks good! Thanks for the fix.

Simplest scenario this failed under was as follows:
1. Create CF stack with S3 bucket and another resource (say, an SQS queue)
2. Upload files to the S3 bucket such that it's non-empty
3. Trigger a delete stack (either via `aws-nuke` or otherwise) - this will fail due to the bucket being non-empty. The bucket will be in `DELETE_FAILED` state and the queue will be `DELETE_COMPLETE`.
4. Run `aws-nuke` - the CF stack will fail to delete with the above validation error.

**Comment by stephanlindauer** [comment]
Fixed by https://github.com/rebuy-de/aws-nuke/pull/271
