### ISSUE TITLE
Disable Termination Protection on EC2 Instances

### ISSUE THREAD

**Issue by rowanu** [rebuy-de/aws-nuke#279]
I'm seeing this error:

````
ap-southeast-2 - EC2Instance - i-xxxx - OperationNotPermitted: The instance 'i-xxxx' may not be terminated. Modify its 'disableApiTermination' instance attribute and try again.
````

I'd like for `aws-nuke` to remove termination protection. If I send a PR for that would you be happy to accept it?

**Comment by bjoernhaeuser** [comment]
Yes, we would accept it. :)

**Comment by jbmchuck** [comment]
Created https://github.com/rebuy-de/aws-nuke/pull/417 to address this.

**Comment by jcarter3** [comment]
A PR was merged that fixes this, can this get closed?

**Comment by svenwltr** [comment]
Yes, it was fixed in https://github.com/rebuy-de/aws-nuke/pull/417. Thanks

**Comment by pulkitsingh30** [comment]
Hey All
I see this issue again today. Below are the logs:

time="2023-06-30T17:07:[24](https://github.com/XXXXX/aws-nuke/actions/runs/XXXX/jobs/9854SXX9#step:4:25)+10:00" level=error msg="There are resources in failed state, but none are ready for deletion, anymore."
time="2023-06-30T17:07:24+10:00" level=error msg="OperationNotPermitted: The instance 'i-03xxxxxxx' may not be terminated. Modify its 'disableApiTermination' instance attribute and try again.\n\tstatus code: 400, request id: 15d01fad-2b63-441c-b1b3-XXXXXXX"
