### ISSUE TITLE
Spare EC2NetworkInterface

### ISSUE THREAD

**Issue by gbergere** [rebuy-de/aws-nuke#286]
Hello, 

I'm trying to spare some EC2NetworkInterface from the nuke but I'm not able to. EC2NetworkInterface are defined by a map and I haven't been able to add them in my config file in anyway to be properly filtered.

Anyone would have any idea to help ?

Thanks

**Comment by gbergere** [comment]
Hello, 

Do you have any news on this? Should I add more details?

Sorry It's a bit blocking for me so if I could have a bit more details it would be very appreciated.

Thanks

**Comment by stephanlindauer** [comment]
hi @gbergere,
can you supply me with your nuke config? only the relevant pieces would be fine.

**Comment by gbergere** [comment]
Here is a sample : 

```---

regions:
  - global
  - us-east-1

account-blacklist:
  - "99999999999"  # Production

accounts:
  "1111111111111":  # Sandbox
    filters:
      ...
      EC2NetworkInterface:
        - ID: "eni-XXX"
        - ID: "eni-XXX"
        - ID: "eni-XXX"
```

I've try with : `"ID: eni-XXX"` or `'ID: "eni-XXX"'` or `"[ID: "eni-XXX", ...]"` none properly work.

**Comment by stephanlindauer** [comment]
can you try:
```
      EC2NetworkInterface:
      - property: ID
        value: "eni-XXX"
```
see https://github.com/rebuy-de/aws-nuke#filter-properties for more details. :)
if this resolved it: can you close the ticket?
