### ISSUE TITLE
CFN fix seems to be a critical one. New binary perhaps?

### ISSUE THREAD

**Issue by srij91** [rebuy-de/aws-nuke#288]

**Comment by stephanlindauer** [comment]
do you mean https://github.com/rebuy-de/aws-nuke/pull/283?
i'll push a new release later today.

just fyi: if you use the docker image then you can use the branch name as a tag: https://quay.io/repository/rebuy/aws-nuke?tag=latest&tab=tags

**Comment by stephanlindauer** [comment]
https://github.com/rebuy-de/aws-nuke/releases/tag/v2.6.0
