### ISSUE TITLE
Baseline account to automatically create filters

### ISSUE THREAD

**Issue by carter3d** [rebuy-de/aws-nuke#292]
I would like to be able to run a baseline that captured all currently configured services and defaults (like VPCs, subnets, etc) and output the results into a configuration file where each discovered resource would be filtered.  Then, after some amount of use in the account (demos, training, experiments), the baseline config file would be used when running AWS Nuke to return the account to the starting state.

**Comment by svenwltr** [comment]
This is an interesting idea. The only issue would be to clearly identify these resources. We could just use properties, but they are not implemented on every resource, yet. Also this might cause problems, if some resource generates dynamic properties (eg IP addresses). I currently do not have an idea how to solve this.

/cc @rebuy-de/prp-aws-nuke

**Comment by bjoernhaeuser** [comment]
I like the idea. I could imagine to extend the current interface and change every resource to list the current one in a compatible format. In the end every resource has a ARN, and we could simply filter on them.

**Comment by svenwltr** [comment]
> In the end every resource has a ARN, and we could simply filter on them.

No, not every resource in terms of *aws-nuke*. There are some like `IAMRolePolicyAttachment` that are not really existent on AWS. The most of these resource are probably identifiable by using the two ARNs of the resource which it connects, but there are funny things like `WAFRegionalByteMatchSetIP`, where you [need four values](https://github.com/rebuy-de/aws-nuke/blob/master/resources/wafregional-byte-match-set-tuples.go#L83-L89). This means we have to take a look at every resource itself and decide how to identify it.

**Comment by dooreelko** [comment]
A PR implementing this has been submitted https://github.com/rebuy-de/aws-nuke/pull/507
Let's give it some traction :)

**Comment by ekristen** [comment]
I like this idea, I'm closing the issue, but haven't closed the PR. I'm looking at implemention possibilities over on the fork. I will comment on the PR as to what I decide to do.

----

Please see the copy of the notice from the README about the deprecation of this project. Sven was kind enough to grant me access to help triage and close issues and pull requests that have already been addressed in the actively maintained fork. Some additional information is located in the [welcome issue](https://github.com/ekristen/aws-nuke/issues/276) for more information. 

> [!CAUTION]
> This repository for aws-nuke is no longer being actively maintained. We recommend users to switch to the actively maintained fork of this project at [ekristen/aws-nuke](https://github.com/ekristen/aws-nuke).
> We appreciate all the support and contributions we've received throughout the life of this project. We believe that the fork will continue to provide the functionality and support that you have come to expect from aws-nuke.
> Please note that this deprecation means we will not be addressing issues, accepting pull requests, or making future releases from this repository.
> Thank you for your understanding and support.
