### ISSUE TITLE
[0115] Listing ELB failed. Please report this ...

### ISSUE THREAD

**Issue by rmharris157** [rebuy-de/aws-nuke#295]
!!! InvalidParameter: 1 validation error(s) found.
    !!! - missing required field, DescribeTagsInput.LoadBalancerNames.

**Comment by svenwltr** [comment]
We suddenly have the same problem. Apparently AWS changed something.

@rebuy-de/prp-aws-nuke Is someone eager to fix this? :>

**Comment by stephanlindauer** [comment]
@svenwltr i will take a look on friday if nobody else comes before me. fyi: in our infrastructure the second attempt after a failure doesn't have this issue.
