### ISSUE TITLE
CognitoUserPool with domain cannot be deleted

### ISSUE THREAD

**Issue by mseiwald** [rebuy-de/aws-nuke#330]
Using AWS Nuke v2.7.0, we encountered this error:

`eu-west-1 - CognitoUserPool - Test - InvalidParameterException: User pool cannot be deleted. It has a domain configured that should be deleted first.
`

**Comment by svenwltr** [comment]
This was already fixed in https://github.com/rebuy-de/aws-nuke/pull/304. I just created a new release that contains this change (https://github.com/rebuy-de/aws-nuke/releases/tag/v2.8.0).

Please reopen, if this does not fix your problem.
