### ISSUE TITLE
AWSServiceRoleForAmazonGuardDuty should be excluded

### ISSUE THREAD

**Issue by mseiwald** [rebuy-de/aws-nuke#331]
Using AWS Nuke v2.7.0, we encountered this error:

`global - IAMRolePolicy - AWSServiceRoleForAmazonGuardDuty -> b4b3b0b27e29f5db632f1c5405f658e3 - UnmodifiableEntity: Cannot perform the operation on the protected role 'AWSServiceRoleForAmazonGuardDuty' - this role is only modifiable by AWS
`

**Comment by mseiwald** [comment]
It seems that we have some non-standard inline policy attached to it. Still, it seems to me that aws-nuke should not try to delete them because they are unmodifiable..

**Comment by svenwltr** [comment]
Hello @mseiwald.

Sorry for the late response. I created a fix in #340, but unfortunately I do not know how to reproduce such a role and therefore I cannot test it.
