### ISSUE TITLE
List of Supported Regions

### ISSUE THREAD

**Issue by acbrazie** [rebuy-de/aws-nuke#343]
I have my config.yml configured with eu-north-1 but the verbose output doesn't show a number of  services available in eu-north-1.  I currently have instances in the Stockholm region.

config.yaml
---
regions:
- eu-north-1
....

Verbose Output:
DEBU[0004] skipping request: service 'ec2' is not available in region 'eu-north-1'

**Comment by svenwltr** [comment]
Hello @acbrazie. This looks like a duplicate of #332, which was already fixed, but not released yet.

I just release [v2.9.0](https://github.com/rebuy-de/aws-nuke/releases/tag/v2.9.0), which contains the fix. Please update and see if it fixes your problem.

**Comment by acbrazie** [comment]
Ah yes, sorry, I see #332.  I've updated to 2.9.0 and it now works, thanks!
