### ISSUE TITLE
taged lambda resources are also deleted with nuke

### ISSUE THREAD

**Issue by plpatankar** [rebuy-de/aws-nuke#344]
Tagged lambda resources are also getting deleted using nuke. Added following config for lambda. 

accounts:
  "ACCOUNT_NO": # nuke account
      filters:
          LambdaEventSourceMapping:
            - property: "tag:nukeignore"
              value : "true"
          LambdaFunction:
            - property: "tag:nukeignore"
              value : "true"

logs: 
[0m[1mus-east-1[0m - [mLambdaFunction[0m - [1mtest[0m - [32mremoved

**Comment by svenwltr** [comment]
Our Lambda resource does not support tags yet. We need to add this features.

**Comment by plpatankar** [comment]
Could you please point me to the list where I can find specially "Tags" are not supported by nuke for AWS services.

**Comment by svenwltr** [comment]
There is no list of resource which support tags, but you can see them in the scan output:

```
eu-west-1 - EC2Subnet - subnet-01c1b999dd29bbdcf - [tag:Name: "Public eu-west-1b", DefaultForAz: "false"] - would remove
```

If the `tag:*` appears there, it supports them.

Unfortunately AWS does not provide a unified API for their resources. Therefore we need to add it to every resource separately.

**Comment by plpatankar** [comment]
Alright, thanks !!

**Comment by svenwltr** [comment]
I reopen this issue to track that we need to add tag support to Lambda resources.

**Comment by plpatankar** [comment]
Sorry to bother you again. However I was trying to find out list of services that at least supported by nuke to ignore on tags. However when I grep into nuke output there are multiple entries where for single service sometimes tag:* exists and sometime not. 

EVENTS  1554143368628                   us-east-1        -      EC2VPC   -      vpc-0f5fb91d85a4f5598    -      [ID: "vpc-0f5fb91d85a4f5598", IsDefault: "true"]         -      mfiltered by con

EVENTS  1554143368628                   us-east-1        -      EC2VPC   -      vpc-0a21ed7c3d2639377    -      [IsDefault: "false", tag:Name: "pacbot-vpc", ID: "vpc-0a21ed7c3d2639377"]

Hence could not drive to the conclusion that such services are support for ignore on tag or not ?

**Comment by svenwltr** [comment]
If the concrete resource does not have any tags, it also does not show them. You can verify this with these commands:

```
aws ec2 describe-vpcs --vpc-ids vpc-0f5fb91d85a4f5598
aws ec2 describe-vpcs --vpc-ids vpc-0a21ed7c3d2639377
```

I did a quick cli run to see what resources are supported. This is the result:

```
% ack -l 'properties.SetTag' ./resources | xargs ack --no-filename 'register\("([^"]+)",' --output='$1' | sort
CloudFormationStack
EC2Instance
EC2InternetGateway
EC2InternetGatewayAttachment
EC2NATGateway
EC2RouteTable
EC2Subnet
EC2VPC
EC2VPCEndpoint
EC2VPNGatewayAttachment
EC2Volume
ELB
ELBv2
ELBv2TargetGroup
FSxBackup
FSxFileSystem
IAMRolePolicy
```

So, there is a lot of work left.

**Comment by videte47** [comment]
I will see if I can help on this front @svenwltr. I have free time this week and wanted to find more resources that needed tagging

**Comment by svenwltr** [comment]
Hi @videte47. I added a new issue for keeping track of tag support: https://github.com/rebuy-de/aws-nuke/issues/353

Unfortunately it is a very long list of resources.
