### ISSUE TITLE
Support Amazon MSK (Managed Services for Kafka) service

### ISSUE THREAD

**Issue by jonotto** [rebuy-de/aws-nuke#354]
More info:
https://aws.amazon.com/msk/

GO SDK info:
https://docs.aws.amazon.com/sdk-for-go/api/service/kafka/

**Comment by videte47** [comment]
I have a working process against this issue https://github.com/rebuy-de/aws-nuke/pull/359

**Comment by videte47** [comment]
I should be amending the PR based on the feedback

**Comment by videte47** [comment]
@svenwltr can we close this issue ?
