### ISSUE TITLE
MaxRetriesExceed does not return none zero exit code

### ISSUE THREAD

**Issue by videte47** [rebuy-de/aws-nuke#355]
This is sort of a question, but I would think that when resources exceed the wait retries threshold aws-nuke should exit with a none zero code no ? This makes the caller aware that there are some orphan resources that are left behind. Currently, aws-nuke while printing the message that we have exceeded the threshold it exits cleaning making the caller assumed that the job was properly completed and all resources were removed. 
https://github.com/rebuy-de/aws-nuke/blob/master/cmd/nuke.go#L117-L118
I wanted to put this issue to get some feedback @svenwltr before submitting a PR

**Comment by svenwltr** [comment]
Yes, you are right @videte47. It should return an error instead of just exiting the loop here.

**Comment by videte47** [comment]
Closing issue per https://github.com/rebuy-de/aws-nuke/pull/356
