### ISSUE TITLE
TooManyRequestsException - 1 request every 30 seconds per account - apigateway-restapis.go

### ISSUE THREAD

**Issue by jcare23** [rebuy-de/aws-nuke#358]
**Title:** TooManyRequestsException - 1 request every 30 seconds per account - apigateway-restapis.go
**Product:** “aws-nuke v2.9.0”
**Classification:** “Minor Bug”
**Platform:** “MacOs Mojave 10.14.4, GNU bash, version 4.4.23(1)-release (x86_64-apple-darwin17.5.0)”
**Can it be reproduced?** “Every time”
**Description:**
-   **Summary:** "Ran aws-nuke deletes one REST API then throws an error, TooManyRequestsException, for 30 seconds until next one is deleted.”
-   **What’s the error?:** “TooManyRequestsException, The request has reached its throttling limit. Retry after the specified time period.”
-   **Steps to reproduce:** “Run aws-nuke with multiple REST APIs to see the behavior.”
-   **Expected results:** “I expected the request to pause for at least 30 seconds before continuing.”
-   **Actual results:** “I received an error message”
-   **Workaround:** “Add a 30-second delay to the DeleteRestApi func per API Gateway Limit Guidelines (DeleteRestApi-1 request every 30 seconds per account) https://docs.aws.amazon.com/apigateway/latest/developerguide/limits.html”
-   **Attachments:**

**Comment by videte47** [comment]
I think the link has an unexpected ' " ' 
https://docs.aws.amazon.com/apigateway/latest/developerguide/limits.html

**Comment by videte47** [comment]
@svenwltr what are your thoughts if we add this pause under here  https://github.com/rebuy-de/aws-nuke/blob/master/resources/apigateway-restapis.go#L49 ? if you shed some light I am willing to push PR

**Comment by svenwltr** [comment]
What exactly is the benefit of waiting after the delete, compared to letting aws-nuke retry the deletion?

I have to check if a sleep does not break anything. In the worst case the whole aws-nuke run will go to sleep. This depends on the implementation of the parallel execution.

**Comment by videte47** [comment]
ya that is a good point @svenwltr actually now that I think of it is the same process that I have some resources. What do you think @jcare23 ?

**Comment by jcare23** [comment]
Sounds good.
