### ISSUE TITLE
aws-nuke --yes

### ISSUE THREAD

**Issue by pcj** [rebuy-de/aws-nuke#360]
I'm looking for a way to use this tool in a periodic job in our CI system that will not require human intervention for the confirmation messages.  Is is possible?  Willing to take a PR?

**Comment by bjoernhaeuser** [comment]
Hey,

what are you exactly looking for? The confirmation messages have a timeout, by default 15 seconds. This can be reduced to one second. 

You need to provide `--no-dry-run` and you can also set `--force-sleep` to the desired timeout.

**Comment by pcj** [comment]
Thanks @bjoernhaeuser so if I set `--no-dry-run` and `--force-sleep=1` then I don't have to enter the account alias?  I'll try that.

I want to have this tool launched by our CI system every 12 hours to cleanup resources in an account I definitely know is okay to nuke everything.

**Comment by bjoernhaeuser** [comment]
And you need to set `--force` :)

**Comment by pcj** [comment]
OK thanks @bjoernhaeuser , this was pretty obvious in hindsight, sorry for the noise!
