### ISSUE TITLE
Using code under /pkg

### ISSUE THREAD

**Issue by nayyara-samuel** [rebuy-de/aws-nuke#362]
We have been using AWS Nuke at our company, contributing to it and I have been reading the code on my own. 
I wanted to use the code under `https://github.com/rebuy-de/aws-nuke/tree/master/pkg` - specifically using the types for a tool I'm writing. Really like the code in this repo - it's clean and usable for the use case I have :D

I want to open-source the tool I am working on, but wanted to check with you about using your code and also some of your patterns (filtering, properties, etc). I'll reference your repo as well. 

Anyways, let me know if that's cool - given your license. Thanks for this awesome project!

**Comment by svenwltr** [comment]
Hello @nayyara-samuel. Reusing code perfectly complies with the MIT Licence. See https://github.com/rebuy-de/aws-nuke/blob/master/LICENSE.

Also I suggest to actually copy it and not just import it, because the interfaces might change any time.

**Comment by nayyara-samuel** [comment]
Thanks for the info!
