### ISSUE TITLE
Failed to get caller identity

### ISSUE THREAD

**Issue by roland33377** [rebuy-de/aws-nuke#363]
Hello everytime i try to start it with ./aws-nuke-v2.10.0-linux-amd64 -c config/nuke-config.yml --profile aws-nuke-example --no-dry-run

i get this error

Error: failed get caller identity: NoCredentialProviders: no valid providers in chain. Deprecated.
        For verbose messaging see aws.Config.CredentialsChainVerboseErrors
What can i do to fix it ?

Regards

**Comment by svenwltr** [comment]
Hello @roland33377. I think this means the profile does not exist. We should output a proper error message here.

**Comment by roland33377** [comment]
Hello @svenwltr nice to hear from you so fast anyway I can run this on a Windows machine like cloud-nuke or what did I do wrong the second error messages it gives me is no static credentials

Regards

**Comment by roland33377** [comment]
Let's say it like this I don't know where to run that thing on a ec2 Linux instances or aws CLI ?

**Comment by der-eismann** [comment]
You can run it on every Linux or macOS machine, just download the [latest release](https://github.com/rebuy-de/aws-nuke/releases/tag/v2.10.0) or the docker container.

When you have done that you need to configure:
- [AWS credentials](https://github.com/rebuy-de/aws-nuke#aws-credentials)
- [a nuke config](https://github.com/rebuy-de/aws-nuke#specifying-resource-types-to-delete)

And then finally run it with a command like `aws-nuke -c config/nuke-config.yml --profile aws-nuke-example` where the nuke config and the profile refer to the previous configured text files.

**Comment by roland33377** [comment]
Ok @der-eismann Thanks for you fast reply so this is my nuke-config.yml

---
regions:
  - "eu-central-1"
account-blacklist:
- 1234567890

resource-types:
  targets:
  - S3Object
  - S3Bucket
  - IAMRole

accounts:
  263208374221: {}

And this is my config "credentials"

[default]
aws_access_key_id =XXXXXXXXXXXXXXXXXXXXXX
aws_secret_access_key =XXXXXXXXXXXXXXXXXXXXXXXXXXXXX

And this is the error i get 

Error: failed get caller identity: NoCredentialProviders: no valid providers in chain. Deprecated.
        For verbose messaging see aws.Config.CredentialsChainVerboseErrors

Here is a picture of my folder
[https://ibb.co/Y27D5kJ](url)

This is what i launch in command line (ubuntu)
./aws-nuke-v2.10.0-linux-amd64 -c config/nuke-config.yml --profile aws-nuke-example

Can someone help with with that ?

**Comment by svenwltr** [comment]
@roland33377 

You need to specify the profile you created, as well. In your case it is `default` and not `aws-nuke-example`.

Also the credentials file needs to be at the correct location and not just in the current directory. See  https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-files.html

**Comment by roland33377** [comment]
Okay @svenwltr and @der-eismann  Thank you very much i got it to work now, Thanks 

Regards
