### ISSUE TITLE
AWS Nuke reports resources removed when dependencies prevent deletion

### ISSUE THREAD

**Issue by snixon** [rebuy-de/aws-nuke#367]
Hello, 
I'm attempting to use aws-nuke to clean up default resources in new accounts and ran into the following issue.

When a removal fails due to a dependency error, it appears aws-nuke interprets the 400 status code return as a successful removal and moves on.

Version: `aws-nuke-v2.10.0-linux-amd64`

```
----snip----
DEBU[0084] sending AWS request:
    > POST / HTTP/1.1
    > Host: ec2.us-west-2.amazonaws.com
    > Authorization: <hidden>
    > Content-Length: 54
    > Content-Type: application/x-www-form-urlencoded; charset=utf-8
    > User-Agent: aws-sdk-go/1.17.8 (go1.11.9; linux; amd64)
    > X-Amz-Date: 20190513T153503Z
    >
    > Action=DeleteVpc&Version=2016-11-15&VpcId=vpc-3c49e044
DEBU[0084] received AWS response:
    < HTTP/1.1 400 Bad Request
    < Connection: close
    < Transfer-Encoding: chunked
    < Date: Mon, 13 May 2019 15:35:02 GMT
    < Server: AmazonEC2
    <
    < 108
    < <?xml version="1.0" encoding="UTF-8"?>
    < <Response><Errors><Error><Code>DependencyViolation</Code><Message>The vpc 'vpc-3c49e044' has dependencies and cannot be deleted.</Message></Error></Errors><RequestID>...</RequestID></Response>
    < 0
us-west-2 - EC2VPC - vpc-3c49e044 - [ID: "vpc-3c49e044", IsDefault: "true"] - removed
----snip----
```

The following config was used:

```
regions:
- us-west-2

accounts:
  "[redacted]": # aws-nuke-example

account-blacklist:
- "999999999999"

resource-types:
  targets:
  - EC2VPC
  - EC2RouteTable
  - EC2Subnet
  - EC2InternetGateway
  - EC2DHCPOption
  - EC2SecurityGroup
```

**Comment by svenwltr** [comment]
Hey @snixon,

is there anything between the debug and the "removed" output? Because *aws-nuke* does not mark a resource as successful removed based on the return code, but only if a [successive listing](https://github.com/rebuy-de/aws-nuke/blob/5792b88/cmd/nuke.go#L276-L306) does not return the resource anymore.

Is this a reproducible issue?
Could something or someone different have deleted the resource in the background?

**Comment by snixon** [comment]
Hi @svenwltr,
Let me see if I can get you an repro early next week, I'm out the rest of this one.  On the run that the above log came from  there appeared to be multiple failed attempts to remove, with the final successfully marked as "removed". After the run the resources were still in place.

**Comment by snixon** [comment]
Looks like I grabbed the wrong output when I put this issue in.  Things are working as expected this morning.

Cheers
