### ISSUE TITLE
S3 buckets not deleted

### ISSUE THREAD

**Issue by ghost** [rebuy-de/aws-nuke#373]
I've used aws-nuke to clear out an account with (amongst many other things) 81 S3 buckets. Having done so I found that only 30 had been removed. There were no failures or exclusions - it looks like it just couldn't see the other buckets.

These buckets reside in the same region as ones which were successfully removed (so it's not #42), I have no filter to exclude any buckets, and I can list the buckets with the same credentials via the AWS CLI and console.

Running aws-nuke again, after deleting those 30 buckets, with the same config didn't find any other buckets. If I add a bucket, it finds the new bucket - just none of the remaining 51. If I add a filter to exclude this new bucket (turns out it was still required - oops!) it is correctly excluded.

Can anyone shed any light on this phenomenon?

**Comment by svenwltr** [comment]
My guess is, that the user you are using, simply has no permissions to see the bucket. To verify this you can try these commands:

```
aws-nuke -c nuke/nuke-config.yml --profile your-profile -t S3Bucket -v
```

```
aws s3api --profile your-profile list-buckets
```

You have to change the profile and the configuration. If the missing bucket appears in one of those two commands, it might be a problem with aws-nuke. Otherwise it is a permission-issue.

**Comment by rodom** [comment]
Nope, it's not a permission issue. I'm using the same credentials (profile) for both commands and the CLI command can see the buckets, and aws-nuke can't.

**Comment by svenwltr** [comment]
It could also be because of the bucket location. While the S3 API is a global one, the buckets still have a region. These regions need to be set in the config.

**Comment by bjoernhaeuser** [comment]
I think the problem is that s3 buckets are not paged and only the first page of results are taken into account

**Comment by svenwltr** [comment]
> I think the problem is that s3 buckets are not paged and only the first page of results are taken into account

It looks like this API does not support pagination: https://docs.aws.amazon.com/sdk-for-go/api/service/s3/#ListBucketsInput

**Comment by bjoernhaeuser** [comment]
Oh wow, thats unexpected..

**Comment by bjoernhaeuser** [comment]
In this case it is probably the mentioned region thingy. 

@rodom could you check that please? :)

**Comment by rodom** [comment]
I don't think it's the region - my config had "eu-west-1" set, and successfully deleted 30 buckets in that region. Most of the rest of the buckets are in the same region, and aren't found.

Pagination, or lack thereof, doesn't appear to fit the symptoms (if it were that, after deleting the first 30 buckets, I'd have expected the next 30 to be shown).

**Comment by svenwltr** [comment]
Sorry for the late answer. You can check the region by executing this with the AWS CLI:

```bash
aws s3api get-bucket-location --bucket $mybucket
```

Replace `$mybucket` with the name of a bucket that does not get deleted. If the printed location is not in the AWS Nuke config, it won't get deleted.

**Comment by rodom** [comment]
@svenwltr the region specified in the AWS Nuke config is the region in which the ignored buckets live.

**Comment by bjoernhaeuser** [comment]
@rodom I think the bugfix for this is in #388

**Comment by rodom** [comment]
@bjoernhaeuser that's certainly a possibility. I can't check, having deleted all the offending buckets manually, but I think it's quite likely that they weren't tagged.

**Comment by jeffchiucp** [comment]
@svenwltr I encountered an issue an error when I tried to remove S3 buckets, and I tried to remove all of my AWS resources today especially S3 buckets, but I encountered an issue that for some reasons some of the old S3 Buckets I removed, for some reasons S3 buckets were  created again after I tried to remove. Screenshot shows that they were removed earlier today. Please help me to remove those resources so I can reduce my AWS cost and billing. Thank you.  Currently, it is showing me error, i have not seen this error before.

**Comment by svenwltr** [comment]
Hello @jeffchiucp. This is not an aws-nuke issue and it is also unrelated to this issue you replied to.

You have figure out what it creating those buckets. *aws-nuke* just deletes them, but any other tool with AWS access is free to recreate them at any time.

**Comment by jeffchiucp** [comment]
Thank you for your help. I got update from AWS Support. AWS Note: Because of eventual consistency (1), a bucket that was recently deleted might appear in the console with "Error" in the Access field. To confirm if a bucket was deleted, you can check the AWS CloudTrail event history (2) for DeleteBucket events (3).
Reference.
(1) - Eventual consistency - https://docs.aws.amazon.com/AmazonS3/latest/dev/Introduction.html#ConsistencyModel
(2) - AWS CloudTrail event history -  https://docs.aws.amazon.com/AmazonS3/latest/dev/cloudtrail-logging.html
(3) - DeleteBucket events - https://docs.aws.amazon.com/AmazonS3/latest/API/API_DeleteBucket.html
That's helpful to know about the S3 issue.
