### ISSUE TITLE
Delete resources in all regions?

### ISSUE THREAD

**Issue by yosef-elementryx** [rebuy-de/aws-nuke#375]
I'm looking to delete all the resources currently in my account regardless of region. Is there a way to delete resources in all regions without specifying each?

**Comment by svenwltr** [comment]
Hello @yosef-elementryx. There is no way to do it without specifying every region. You have to specify each one. See https://docs.aws.amazon.com/general/latest/gr/rande.html for a full list of regions.

**Comment by wesgreentree** [comment]
@svenwltr Would this issue and or project in general be good for a GoLang newbie looking to contribute ? I'm keen.

**Comment by svenwltr** [comment]
Hello @wesgreentree, before we can judge the complexity, we need to agree on how the configuration file should look like. Generally it should not be that hard, since the AWS SDK contains a list of all regions somewhere.

**Comment by wesgreentree** [comment]
@svenwltr Is anything on this page helpful ?  https://docs.aws.amazon.com/sdk-for-go/api/aws/endpoints/

**Comment by svenwltr** [comment]
This contains the mentioned list of regions, but we still need a proposal on how the aws-nuke config file should look like.

**Comment by robkinyon-lokavant** [comment]
There will never be a region called "ALL", so just use that.

**Comment by m-31** [comment]
aws ec2 describe-regions --query "Regions[*].RegionName" --output text | xargs -n 1 | sort

**Comment by wonjoonSeolDH** [comment]
```
regions:
- global
- ap-northeast-1
- ap-northeast-2
- ap-northeast-3
- ap-south-1
- ap-southeast-1
- ap-southeast-2
- ca-central-1
- eu-central-1
- eu-north-1
- eu-west-1
- eu-west-2
- eu-west-3
- sa-east-1
- us-east-1
- us-east-2
- us-west-1
- us-west-2
```

**Comment by drzamich** [comment]
Update, as some regions were updated in the past 2 years
```
regions:
- global
- us-east-2
- us-east-1
- us-west-1
- us-west-2
- af-south-1
- ap-east-1
- ap-southeast-3
- ap-south-1
- ap-northeast-3
- ap-northeast-2
- ap-southeast-1
- ap-southeast-2
- ap-northeast-1
- ca-central-1
- cn-north-1
- cn-northwest-1
- eu-central-1
- eu-west-1
- eu-west-2
- eu-south-1
- eu-west-3
- eu-north-1
- me-south-1
- sa-east-1
```

**Comment by tzvatot** [comment]
It would be very beneficial to get this feature without actually having to generate this list all the time.

**Comment by optplx** [comment]
Hello, not sure what is blocking here, wouldn't a `all-region: true` or `regions: ["all"]` be fine for the config part? It looks like we are kind of maintaining a list of all regions in this issue while we could fetch it dynamically instead :)

**Comment by pswalia2u** [comment]
![image](https://user-images.githubusercontent.com/20887270/217167436-840d6eda-290d-4fc1-ad3e-f3dc954c5e0a.png)
![image](https://user-images.githubusercontent.com/20887270/217167500-a06fd0d9-3180-464d-acce-24d66bcbcac6.png)
---
# This is a sample AWS Nuke configuration file
# Please refer to the documentation for more information:
# https://github.com/rebuy-de/aws-nuke

# AWS Nuke will only act on resources within the specified regions.
# By default, if no regions are specified, AWS Nuke will not act on any resources.
regions:
  - ap-south-1
  - ap-northeast-3
  - ap-northeast-2
  - ap-southeast-1
  - ap-southeast-2
  - ap-northeast-1
  - ca-central-1
  - eu-central-1
  - eu-west-1
  - eu-west-2
  - eu-west-3
  - eu-north-1
  - me-south-1
  - sa-east-1
  - us-east-1
  - us-east-2
  - us-west-1
  - us-west-2

account-blocklist:
- "999999999999" # production

accounts:
  "<Account-id>": {} # aws-nuke-example

**Comment by sickdyd** [comment]
Updated list of regions as per today taken from [here](https://docs.aws.amazon.com/general/latest/gr/rande.html):

```yml
regions:
- global
- us-east-2
- us-east-1
- us-west-1
- us-west-2
- af-south-1
- ap-east-1
- ap-south-2
- ap-southeast-3
- ap-southeast-4
- ap-south-1
- ap-northeast-3
- ap-northeast-2
- ap-southeast-1
- ap-southeast-2
- ap-northeast-1
- ca-central-1
- ca-west-1
- eu-central-1
- eu-west-1
- eu-west-2
- eu-south-1
- eu-west-3
- eu-south-2
- eu-north-1
- eu-central-2
- il-central-1
- me-south-1
- me-central-1
- sa-east-1
- us-gov-east-1
- us-gov-west-1
```

**Comment by ekristen** [comment]
The now active fork implemented a feature called all enabled regions - https://github.com/ekristen/aws-nuke/pull/84

If you have a chance, please check it out and let us know if you run into an issues by opening an issue over on the fork.

----

Please see the copy of the notice from the README about the deprecation of this project. Sven was kind enough to grant me access to help triage and close issues and pull requests that have already been addressed in the actively maintained fork. Some additional information is located in the [welcome issue](https://github.com/ekristen/aws-nuke/issues/276) for more information. 

> [!CAUTION]
> This repository for aws-nuke is no longer being actively maintained. We recommend users to switch to the actively maintained fork of this project at [ekristen/aws-nuke](https://github.com/ekristen/aws-nuke).
> We appreciate all the support and contributions we've received throughout the life of this project. We believe that the fork will continue to provide the functionality and support that you have come to expect from aws-nuke.
> Please note that this deprecation means we will not be addressing issues, accepting pull requests, or making future releases from this repository.
> Thank you for your understanding and support.
