### ISSUE TITLE
aws-nuke gets stuck, no errors. How to troubleshoot it?

### ISSUE THREAD

**Issue by fredshino** [rebuy-de/aws-nuke#376]
The dry run shows all resources that should be nuked but with --no-dry-run, it gets stuck and doesn't do anything. No error messages. Pasting the output below.

Is there a way to run it on a verbose/debug mode or something so I can understand why it's getting stuck?

[[redacted]@[redacted] ~]$ aws-nuke -c run-2.yml --profile default --no-dry-run
aws-nuke version v2.11.0 - Mon May 20 08:55:46 UTC 2019

Do you really want to nuke the account with the ID [redacted] and the alias '[redacted]'?
Do you want to continue? Enter account alias to continue.
[redacted]

us-east-1 - S3Bucket - s3://[redacted] - filtered by config
us-east-1 - S3Bucket - s3://[redacted] - would remove
[...]
Scan complete: 44 total, 31 nukeable, 13 filtered.

Do you really want to nuke these resources on the account with the ID [redacted] and the alias '[redacted]'?
Do you want to continue? Enter account alias to continue.
[redacted]
(gets stuck here forever, I ctrl+C to quit)
^C
[[redacted]@[redacted] ~]$

**Comment by bjoernhaeuser** [comment]
How many items are in these buckets?

**Comment by fredshino** [comment]
> How many items are in these buckets?

500k+. I was able to manually delete the bucket on the console but it took a while too. If that's the issue, can it at least output something to let us know it's executing something and not just stuck?

**Comment by svenwltr** [comment]
> ... can it at least output something to let us know it's executing something and not just stuck?

Having so much objects sounds a bit like an edge case to me. I do not see a quick and easy way to output something without cluttering up the output in general.

**Comment by maciejstromich** [comment]
It's not really an edge case. We have multiple buckets which are 1M+ objects. What we found useful was to exclude S3Object resource type while retaining S3Bucket. This will mean that there will be no S3 ListBucket operation  to gather all the objects inside the bucket which takes a lot of time. Buckets get emptied while they are being removed and you're not getting the impression that it's stuck. Also if you have large DynamoDB tables excluding DynamoDBTableItem resource works the same way.

**Comment by mhvelplund** [comment]
> What we found useful was to exclude S3Object resource type while retaining S3Bucket.

I came to the same conclusion.

**Comment by jamesgeddes** [comment]
Some feedback so reassure us humans that it has not died would be helpful.

**Comment by ekristen** [comment]
If you've already excluded `S3Object`, please try out the docker images from the [actively managed fork of aws-nuke](https://github.com/ekristen/aws-nuke) 

If the issue still persists, please open an issue over on the forked repository. Thank you.

----

Please see the copy of the notice from the README about the deprecation of this project. Sven was kind enough to grant me access to help triage and close issues and pull requests that have already been addressed in the actively maintained fork. Some additional information is located in the [welcome issue](https://github.com/ekristen/aws-nuke/issues/276) for more information. 

> [!CAUTION]
> This repository for aws-nuke is no longer being actively maintained. We recommend users to switch to the actively maintained fork of this project at [ekristen/aws-nuke](https://github.com/ekristen/aws-nuke).
> We appreciate all the support and contributions we've received throughout the life of this project. We believe that the fork will continue to provide the functionality and support that you have come to expect from aws-nuke.
> Please note that this deprecation means we will not be addressing issues, accepting pull requests, or making future releases from this repository.
> Thank you for your understanding and support.
