### ISSUE TITLE
Can't get docker running

### ISSUE THREAD

**Issue by schmidalex37** [rebuy-de/aws-nuke#377]
So i can't get the docker running. The config works fine and the programm can be executed locally with go. 
`go run main.go --config config/nuke-settings.yaml --profile testUser --force --no-dry-run`

Configurations are applied correctly.
`docker build . -t rebuy-de/aws_nuke/playground-nuke` 
works fine and the build is successfully built

The problem is if i try to run the docker this way i get this error
```
docker run -a stdin -a stdout -ti rebuy-de/aws_nuke/playground-nuke -c config/nuke-config.yml --profile testUser -v
DEBU[0000] creating new session in us-east-1
DEBU[0000] creating new root session in us-east-1
Error: failed get caller identity: NoCredentialProviders: no valid providers in chain. Deprecated.
        For verbose messaging see aws.Config.CredentialsChainVerboseErrors
``` 
but i can get the caller identity with this code:
```
aws sts get-caller-identity --profile testUser
{
    "Account": "############################",
    "UserId": "############################",
    "Arn": "############################"
}
```
if i use the key directly in the console this happens, even if i use the example config file it does not work:

```
C:\Go\src\github.com\rebuy-de\aws-nuke\playground-nuke>docker run -a stdin -a stdout -ti rebuy-de/aws_nuke/playground-nuke -c config/nuke-settings.yaml --access-key-id=########  --secret-access-key=######## --session-token=######## -v
DEBU[0000] creating new session in us-east-1
DEBU[0000] creating new root session in us-east-1
DEBU[0000] sending AWS request:
    > POST / HTTP/1.1
    > Host: sts.amazonaws.com
    > Authorization: <hidden>
    > Content-Length: 43
    > Content-Type: application/x-www-form-urlencoded; charset=utf-8
    > User-Agent: aws-sdk-go/1.19.48 (go1.12.5; linux; amd64)
    > X-Amz-Date: 20190613T071439Z
    > X-Amz-Security-Token: <hidden>
    >
    > Action=GetCallerIdentity&Version=2011-06-15
DEBU[0000] received AWS response:
    < HTTP/1.1 200 OK
    < Content-Length: 469
    < Content-Type: text/xml
    < Date: Thu, 13 Jun 2019 07:14:39 GMT
    < X-Amzn-Requestid: e89d725d-8daa-11e9-930d-77a502702f1e
    <
    < <GetCallerIdentityResponse xmlns="https://sts.amazonaws.com/doc/2011-06-15/">
    <   <GetCallerIdentityResult>
    <     <Arn>arn:aws:sts::########:assumed-role/########</Arn>
    <     <UserId>########</UserId>
    <     <Account>########</Account>
    <   </GetCallerIdentityResult>
    <   <ResponseMetadata>
    <     <RequestId>e89d725d-8daa-11e9-930d-77a502702f1e</RequestId>
    <   </ResponseMetadata>
    < </GetCallerIdentityResponse>
DEBU[0000] creating new session in global
DEBU[0000] sending AWS request:
    > POST / HTTP/1.1
    > Host: iam.amazonaws.com
    > Authorization: <hidden>
    > Content-Length: 44
    > Content-Type: application/x-www-form-urlencoded; charset=utf-8
    > User-Agent: aws-sdk-go/1.19.48 (go1.12.5; linux; amd64)
    > X-Amz-Date: 20190613T071439Z
    > X-Amz-Security-Token: <hidden>
    >
    > Action=ListAccountAliases&Version=2010-05-08
DEBU[0001] received AWS response:
    < HTTP/1.1 200 OK
    < Content-Length: 398
    < Content-Type: text/xml
    < Date: Thu, 13 Jun 2019 07:14:40 GMT
    < X-Amzn-Requestid: e8e836d4-8daa-11e9-82f0-cf006d42f1a3
    <
    < <ListAccountAliasesResponse xmlns="https://iam.amazonaws.com/doc/2010-05-08/">
    <   <ListAccountAliasesResult>
    <     <IsTruncated>false</IsTruncated>
    <     <AccountAliases>
    <       <member>aws-playground-nuke</member>
    <     </AccountAliases>
    <   </ListAccountAliasesResult>
    <   <ResponseMetadata>
    <     <RequestId>e8e836d4-8daa-11e9-82f0-cf006d42f1a3</RequestId>
    <   </ResponseMetadata>
    < </ListAccountAliasesResponse>
ERRO[0001] Failed to parse config file.
Error: open config/nuke-settings.yaml: no such file or directory
```
I don't know where this error comes from and would appreciate if you can help me.

**Comment by svenwltr** [comment]
It is hard to tell what the exact problem is without seeing the actual Dockerfile. One important thing is that application running inside Docker do not have access to any files from the host system, if they are not specified explicitly. This means the AWS config and the aws-nuke config have to be copied to the image.

**Comment by svenwltr** [comment]
I just saw the the Docker section of the README is a bit unclear. Perhaps we need to clarify it.

**Comment by schmidalex37** [comment]
I did not edit the dockerfile, I used your example file.

**Comment by schmidalex37** [comment]
I need a bit help with your new Docker command. I am quite new to programming and not used to aws or docker.
My environment is located at "C:\Go\src\github.com\rebuy-de\aws-nuke\playground-nuke"
I named the config file with all the filters nuke-settings.yaml
If I run this code:
` docker run --rm -it -v config/nuke-settings.yaml:/home/aws-nuke/playground-nuke/config.yml -v /home/user/.aws:/home/aws-nuke/.aws quay.io/rebuy/aws-nuke:v2.11.0 --profile testUser --config /home/aws-nuke/playground-nuke/config/nuke-settings.yml`

I get this error: docker: 
`Error response from daemon: create config/nuke-settings.yaml: "config/nuke-settings.yaml" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path.
See 'docker run --help'.`

With GO everything works and runs, even with the config.
Thanks in advance.

**Comment by svenwltr** [comment]
Hello @schmidalex37.

You cannot use relative paths (`config/nuke-settings.yaml`) for attaching volumes with Docker. It has to be an absolute one, like `/home/user/config/nuke-settings.yaml`. Unfortunately I do not know how the paths look like in Windows.

**Comment by schmidalex37** [comment]
So I get a notification from docker, that they want to acces my local drive and there is no error popping up, but also nothing happening. 
`docker run --rm -it -v C:/Go/src/github.com/rebuy-de/aws-nuke/playground-nuke/config/docker-config.yaml:/home/aws-nuke/playground-nuke/config.yml -v /home/user/.aws:/home/aws-nuke/.aws quay.io/rebuy/aws-nuke:v2.11.0 --profile testUser --config  C:/Go/src/github.com/rebuy-de/aws-nuke/playground-nuke/config/nuke-settings.yaml`

**Comment by schmidalex37** [comment]
Still error messages
```
docker run --rm -it -v C:/Go/src/github.com/rebuy-de/aws-nuke/playground-nuke/config/nuke-settings.yaml:/home/aws-nuke/playground-nuke/config.yml -v /home/user/.aws:/home/aws-nuke/.aws quay.io/rebuy/aws-nuke:v2.11.0 --config C:/Go/src/github.com/rebuy-de/aws-nuke/playground-nuke/config/nuke-settings.yaml --profile testUser -v
DEBU[0000] creating new session in us-east-1
DEBU[0000] creating new root session in us-east-1
Error: failed get caller identity: NoCredentialProviders: no valid providers in chain. Deprecated.
        For verbose messaging see aws.Config.CredentialsChainVerboseErrors
```
```
docker run --rm -it -v C:/Go/src/github.com/rebuy-de/aws-nuke/playground-nuke/config/nuke-settings.yaml:/home/aws-nuke/playground-nuke/config.yml -v /home/user/.aws:/home/aws-nuke/.aws quay.io/rebuy/aws-nuke:v2.11.0 --config C:/Go/src/github.com/rebuy-de/aws-nuke/playground-nuke/config/nuke-settings.yaml --access-key-id=##### --secret-access-key=##### --session-token=##### -v
DEBU[0000] creating new session in us-east-1
DEBU[0000] creating new root session in us-east-1
DEBU[0065] sending AWS request:
    > POST / HTTP/1.1
    > Host: sts.amazonaws.com
    > Authorization: <hidden>
    > Content-Length: 43
    > Content-Type: application/x-www-form-urlencoded; charset=utf-8
    > User-Agent: aws-sdk-go/1.17.8 (go1.12.5; linux; amd64)
    > X-Amz-Date: 20190618T112315Z
    > X-Amz-Security-Token: <hidden>
    >
    > Action=GetCallerIdentity&Version=2011-06-15
Error: failed get caller identity: RequestError: send request failed
caused by: Post https://sts.amazonaws.com/: dial tcp 52.46.134.192:443: connect: connection refused
```

**Comment by svenwltr** [comment]
This looks like a networking issue. Perhaps it has something to do with your Firewall.

Maybe you should ask in some Docker usergroup about this issue, since we have nobody who uses Docker on Windows.

**Comment by ekristen** [comment]
Please try out the docker images from the [actively managed fork of aws-nuke](https://github.com/ekristen/aws-nuke) 

If the issue still persists, please open an issue over on the forked repository. Thank you.

----

Please see the copy of the notice from the README about the deprecation of this project. Sven was kind enough to grant me access to help triage and close issues and pull requests that have already been addressed in the actively maintained fork. Some additional information is located in the [welcome issue](https://github.com/ekristen/aws-nuke/issues/276) for more information. 

> [!CAUTION]
> This repository for aws-nuke is no longer being actively maintained. We recommend users to switch to the actively maintained fork of this project at [ekristen/aws-nuke](https://github.com/ekristen/aws-nuke).
> We appreciate all the support and contributions we've received throughout the life of this project. We believe that the fork will continue to provide the functionality and support that you have come to expect from aws-nuke.
> Please note that this deprecation means we will not be addressing issues, accepting pull requests, or making future releases from this repository.
> Thank you for your understanding and support.
