### ISSUE TITLE
support for robomaker resources is missing

### ISSUE THREAD

**Issue by mvanholsteijn** [rebuy-de/aws-nuke#386]
I have an account which has RoboMaker resources. Working on a PR at https://github.com/binxio/aws-nuke. Once it is finished, I will submit it.

**Comment by liaharr** [comment]
Has there been any updates on this? Do you plan to merge your forked branch? Adding a RoboMaker resource would be hugely helpful for the project I'm working on!

**Comment by mvanholsteijn** [comment]
merged.
