### ISSUE TITLE
Cannot run AWS Nuke in non-default partitions

### ISSUE THREAD

**Issue by Brian-McG** [rebuy-de/aws-nuke#391]
Hi,

We have AWS accounts in multiple [AWS partitions](https://docs.aws.amazon.com/sdk-for-go/api/aws/endpoints/#DefaultPartitions). Aws-nuke works really well at cleaning up our accounts in the default (aws) partition but we want to be able to use it in the aws-cn partition too.

When I run it with verbose logging, I see that it always creates a session in us-east-1. I think this is when it is trying to get the account-alias here: https://github.com/rebuy-de/aws-nuke/blob/master/pkg/awsutil/account.go#L21

It looks like this also gets a session from us-east-1: https://github.com/rebuy-de/aws-nuke/blob/master/pkg/awsutil/session.go#L56

A session created in an aws partition is not valid in a different partition (aws-cn for example). Is it possible to use the region from the config when creating the session?

**Comment by svenwltr** [comment]
This would be possible for sessions, but we have to find a way to handle the `global` region, because I guess these are also bound to a partition.

**Comment by chrisgilmerproj** [comment]
@svenwltr - I have opened PR https://github.com/rebuy-de/aws-nuke/pull/647 which might address this issue.
