### ISSUE TITLE
Permit the ability to specify an Iam role to assume for AWS nuke

### ISSUE THREAD

**Issue by mcolatosti** [rebuy-de/aws-nuke#409]
Looking to create an AWS wipe function for an environment with many accounts using terraform and automated build pipelines.  We do not permit the use of user accounts or credentials in any of the environments, especially from any "pipeline" aws resource building accounts.  Any thoughts about supporting the use of an EC2 instance role, and specifically for an the AWS Nuke process to use an ec2 iam role to assume the actual role giving it the permissions to destroy resources?  So basically command line argument for AWS Nuke to use its currently running EC2 iam role to assume another role specified via the config file or a command line parameter?

**Comment by dxciberaws** [comment]
We use a simple Python script that assumes a role and writes a profile into .aws/credentials, we combine it in the same script that then invokes aws-nuke using the just generated profile.
Mind that if you run this script under a role's principal, such as if you do it from an instance with an Instance Profile, ECS container (we do this), or similar, you are affected by a 1 hour maximum session time for Role Chaning, no matter if the role has a longer maximum allowed session time, and you specify a longer time in the AssumeRole operation. That will make the role assumption fail.

**Comment by njtrettel** [comment]
I think #667 addresses this

it adds the ability to pass in an `--assume-role-arn` to the CLI which nuke will assume before initializing any AWS clients

**Comment by ekristen** [comment]
The [actively managed fork of aws-nuke](https://github.com/ekristen/aws-nuke) has the ability to assume role with the following CLI arguments and environment variables.

```console
   --assume-role-arn value                                                                  the role arn to assume using the credentials provided in the profile or statically set [$AWS_ASSUME_ROLE_ARN]
   --assume-role-session-name value                                                         the session name to provide for the assumed role [$AWS_ASSUME_ROLE_SESSION_NAME]
   --assume-role-external-id value                                                          the external id to provide for the assumed role [$AWS_ASSUME_ROLE_EXTERNAL_ID]
```

If you have a chance, please check it out and let us know if you run into an issues by opening an issue over on the fork.

----

Please see the copy of the notice from the README about the deprecation of this project. Sven was kind enough to grant me access to help triage and close issues and pull requests that have already been addressed in the actively maintained fork. Some additional information is located in the [welcome issue](https://github.com/ekristen/aws-nuke/issues/276) for more information. 

> [!CAUTION]
> This repository for aws-nuke is no longer being actively maintained. We recommend users to switch to the actively maintained fork of this project at [ekristen/aws-nuke](https://github.com/ekristen/aws-nuke).
> We appreciate all the support and contributions we've received throughout the life of this project. We believe that the fork will continue to provide the functionality and support that you have come to expect from aws-nuke.
> Please note that this deprecation means we will not be addressing issues, accepting pull requests, or making future releases from this repository.
> Thank you for your understanding and support.
