### ISSUE TITLE
Nuke in China Region

### ISSUE THREAD

**Issue by weiping-bj** [rebuy-de/aws-nuke#411]
Hi,

I try to use aws-nuke in china region (cn-northwest-1), and correctly set my AKSK in profile. 

But I encountered an error message as follows:
"failed get caller identity: InvalidClientTokenId: The security token included in the request is invalid."

Does anyone could guide me how to fix this problem?

Thanks.

**Comment by svenwltr** [comment]
We have to implement support for other [partitions](https://docs.aws.amazon.com/sdk-for-go/api/aws/endpoints/#Partition). Currently only the default one is supported.

**Comment by weiping-bj** [comment]
Got it. Thanks.

**Comment by svenwltr** [comment]
This is still something we should do. Therefore I'll reopen this issue.

**Comment by PatMyron** [comment]
more generally https://github.com/rebuy-de/aws-nuke/issues/391

**Comment by svenwltr** [comment]
Closing in favor of #391

**Comment by DawnElixir** [comment]
The issue still remains for China region(cn-north-1 & cn-northwest-1). The PR seems only resolve the issue in GovCloud but there's no proper way to use aws-nuke in China region.
