### ISSUE TITLE
Less verbose reporting on S3 buckets

### ISSUE THREAD

**Issue by mcolatosti** [rebuy-de/aws-nuke#418]
If deleting some S3 buckets with 100K+ objects is there or could there be a way to output just the fact the bucket was deleted rather than iterating through all the files?  If its necessary to iterate through the files, is it possible to avoid displaying that in the output?  It drowns most everything else.

**Comment by McAntMan** [comment]
@mcolatosti I would exclude the `S3Object` resource or only target `S3Bucket` in your configuration. Nuking only the `S3Bucket` resources will clean up all the objects within the bucket still, without logging all of the individual objects.

**Comment by ekristen** [comment]
The proper method here is to exclude `S3Object` in your configuration and just use `S3Bucket` as @thonyphony mentioned.
