### ISSUE TITLE
exclude complete resource "families" like IAM*

### ISSUE THREAD

**Issue by youwalther65** [rebuy-de/aws-nuke#420]
It is not an issue but more an enhancement request.
Currently I am using the following approach to exlude all IAM resources:

---
regions:
- "global" # This is for all global resource types e.g. IAM
- "eu-central-1"
- "eu-west-1"

account-blacklist:
  - yyyyyyy

# optional: restrict nuking to these resources
resource-types:
  # don't nuke IAM resources (but if created with CloudFormation you can't avod it :-( )
  excludes:
    - IAMGroup
    - IAMGroupPolicy
    - IAMGroupPolicyAttachment
    - IAMInstanceProfile
    - IAMInstanceProfileRole
    - IAMLoginProfile
    - IAMOpenIDConnectProvider
    - IAMPolicy
    - IAMRole
    - IAMRolePolicy
    - IAMRolePolicyAttachment
    - IAMSAMLProvider
    - IAMServerCertificate
    - IAMServiceSpecificCredential
    - IAMUser
    - IAMUserAccessKey
    - IAMUserGroupAttachment
    - IAMUserPolicy
    - IAMUserPolicyAttachment

accounts:
  xxxxxxxxxxxxxxx

wher I got all possible IAM resources vi

aws-nuke resource-types | grep -i IAM

Would it be possible to implement something like IAM* for excluding all IAM (or other) related resources?
resource-types:
  # don't nuke IAM resources at all
  excludes:
  - IAM*

**Comment by ekristen** [comment]
@youwalther65 I think this is a valid feature request and I cannot currently see any downside. I've opened https://github.com/ekristen/aws-nuke/issues/302 for tracking on what is now the actively managed fork of aws-nuke. 

----

Please see the copy of the notice from the README about the deprecation of this project. Sven was kind enough to grant me access to help triage and close issues and pull requests that have already been addressed in the actively maintained fork. Some additional information is located in the [welcome issue](https://github.com/ekristen/aws-nuke/issues/276) for more information. 

> [!CAUTION]
> This repository for aws-nuke is no longer being actively maintained. We recommend users to switch to the actively maintained fork of this project at [ekristen/aws-nuke](https://github.com/ekristen/aws-nuke).
> We appreciate all the support and contributions we've received throughout the life of this project. We believe that the fork will continue to provide the functionality and support that you have come to expect from aws-nuke.
> Please note that this deprecation means we will not be addressing issues, accepting pull requests, or making future releases from this repository.
> Thank you for your understanding and support.
