### ISSUE TITLE
Delete NS record

### ISSUE THREAD

**Issue by qrevel** [rebuy-de/aws-nuke#423]
Creating NS records in a zone is possible (subdomain hosted zone for example)

Unfortunately, aws-nuke doesn't delete them and skip them.

Is the filter can be updated to only filter the NS of the actual zone and not other NS that points to subzone?

**Comment by bjoernhaeuser** [comment]
@qrevel do you want to provide the necessary PR for this?

**Comment by ekristen** [comment]
Please try the fork out at https://github.com/ekristen/aws-nuke, if this is still an issue open an issue there.

If you have a chance, please check it out and let us know if you run into an issues by opening an issue over on the fork.

----

Please see the copy of the notice from the README about the deprecation of this project. Sven was kind enough to grant me access to help triage and close issues and pull requests that have already been addressed in the actively maintained fork. Some additional information is located in the [welcome issue](https://github.com/ekristen/aws-nuke/issues/276) for more information. 

> [!CAUTION]
> This repository for aws-nuke is no longer being actively maintained. We recommend users to switch to the actively maintained fork of this project at [ekristen/aws-nuke](https://github.com/ekristen/aws-nuke).
> We appreciate all the support and contributions we've received throughout the life of this project. We believe that the fork will continue to provide the functionality and support that you have come to expect from aws-nuke.
> Please note that this deprecation means we will not be addressing issues, accepting pull requests, or making future releases from this repository.
> Thank you for your understanding and support.
