### ISSUE TITLE
Issue with feature-flag

### ISSUE THREAD

**Issue by gsund89** [rebuy-de/aws-nuke#425]
Encountered the below error while mentioning feature-flag on the root-level of the config file. Used the latest release v2.12.0.

```
[Container] 2019/10/30 10:23:42 Running command aws-nuke -c $account_id-config.yml --force --access-key-id $ACCESS_KEY_ID --secret-access-key $SECRET_ACCESS_KEY --session-token $SESSION_TOKEN
time="2019-10-30T10:23:42Z" level=error msg="Failed to parse config file." 
Error: yaml: unmarshal errors: 
  line 249: field feature-flags not found in type config.Nuke 
```

Config.yml
---------------

```yaml
regions:
- "global"
- "us-east-1"

account-blacklist:
- "999999999999"

accounts:
  "000000000000"  {}

feature-flags:
  disable-deletion-protection:
    RDSInstance: true
    CloudFormationStack: true
    EC2Instance: true
```

**Comment by svenwltr** [comment]
Hello @gsund89.

Feature-flags are a new feature and are not released, yet.

**Comment by gsund89** [comment]
any ETA?

**Comment by youwalther65** [comment]
To be honest: This is kind of strange. You can't put a feature in the top level documentation which is not yet implemented! aws-nuke is a great tool so please be careful with such things. Intersted in the ETA too!

**Comment by svenwltr** [comment]
Hello. Sorry for the late response. We are very busy recently and I forgot about this issue. I just created a release which includes the new feature flags: https://github.com/rebuy-de/aws-nuke/releases/tag/v2.13.0

The reason for the difference between the GitHub readme and the release it that we currently only have the `master` branch and feature branches. Therefore every change will be update there as soon as we approve a change. I agree that this is not the nicest way to show a documentation to the user.

**Comment by youwalther65** [comment]
Great, thx very much. I will test it in a minute :)
