### ISSUE TITLE
runtime error - MacOS

### ISSUE THREAD

**Issue by tbatch** [rebuy-de/aws-nuke#43]
$ aws-nuke-v1.2.1-darwin-amd64 -c aws-nuke-config.yml --profile aws-enterprise-uat

us-east-1 - RDSDBSubnetGroup - 'apiture-stacks-component-rds-databasesubnetgroup-17hxceov4kkcc' - would remove
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x185dbf6]

goroutine 53 [running]:

**Comment by svenwltr** [comment]
@tbatch Could you also post the stack trace, which comes after that error?

**Comment by tbatch** [comment]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x185dbf6]

goroutine 29 [running]:
github.com/rebuy-de/aws-nuke/resources.(*S3Nuke).DescribeBuckets(0xc420074240, 0x244fda0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/rebuy-de/aws-nuke/resources/s3-buckets.go:28 +0x166
github.com/rebuy-de/aws-nuke/resources.(*S3Nuke).ListBuckets(0xc420074240, 0x244fda0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/rebuy-de/aws-nuke/resources/s3-buckets.go:38 +0x40
github.com/rebuy-de/aws-nuke/resources.(*S3Nuke).ListBuckets-fm(0x244fda0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/rebuy-de/aws-nuke/resources/listers.go:101 +0x2a
github.com/rebuy-de/aws-nuke/cmd.Scan.func1(0xc420138180, 0xc4204d0320, 0xc42019eae0)
	/go/src/github.com/rebuy-de/aws-nuke/cmd/scan.go:22 +0x77
created by github.com/rebuy-de/aws-nuke/cmd.Scan
	/go/src/github.com/rebuy-de/aws-nuke/cmd/scan.go:39 +0x9e

**Comment by tbatch** [comment]
Sorry about that, the stack trace is above.

**Comment by tbatch** [comment]
Maybe something wrong with my region?  Below is my config file.

regions:
- us-east-1

account-blacklist:
- "0000000000" # production - real account number here.

accounts:
  "0000000000": {} # real account number here.

**Comment by bjoernhaeuser** [comment]
@tbatch can you try out release [v1.2.2](https://github.com/rebuy-de/aws-nuke/releases/tag/v1.2.2)? It should contain the required bugfix. Thanks!

**Comment by tbatch** [comment]
Looks good!  Thanks so much!

**Comment by bjoernhaeuser** [comment]
Thanks for testing :)
