### ISSUE TITLE
nuke of  enabled CloudFormation stacks with "termination protected" enabled

### ISSUE THREAD

**Issue by youwalther65** [rebuy-de/aws-nuke#430]
Would it be possible to add CloudFormation to feature-flag -> disable-deletion-protection

feature-flags:
  disable-deletion-protection:
    EC2Instance: true
    RDSInstance: true
    **CloudFormationStack: true**

Currently it seems it only supports EC2 and RDS
Thx in advance!

**Comment by bjoernhaeuser** [comment]
@youwalther65 sure! Do you want to contribute this change?

**Comment by jcarter3** [comment]
I added in support for this in a branch, but unfortunately did my other contribution out of `master` so will need to shuffle some stuff around to properly submit a PR

**Comment by jcarter3** [comment]
Fixed the branches in my fork, submitted PR to support this via feature flag

**Comment by jcarter3** [comment]
PR was merged

**Comment by der-eismann** [comment]
Fixed by #481
