### ISSUE TITLE
Untagged resources wipe

### ISSUE THREAD

**Issue by moradiyaamit** [rebuy-de/aws-nuke#432]
Is there any way to wipe the resources which are untagged in the account? I am talking about the resources such as EC2, S3 , RDS Dynamo

**Comment by svenwltr** [comment]
Hello @moradiyaamit. What exactly do you mean? Do you want to delete *only* resources that do not have tags?

This is a bit difficult, because there are some "virtual" resources that are not able to have tags (eg EC2 EBS Attachements). This would mean, that those always get deleted. Additionally there are resources in *aws-nuke* that do not have tagging implemented yet. Those would get deleted too.

Currently, I do not see any easy way to do this.

**Comment by moradiyaamit** [comment]
Let's assume it is ec2 instance only, is it possible to do for that or not at all

**Comment by svenwltr** [comment]
Unfortunately you can only filter instances that do not have a specific tag.

Something like this should work:

```yaml
EC2Instance:
- property: "tag:MyTag"
  type: regex
  value: ".+"
```

**Comment by moradiyaamit** [comment]
Are you guys planning to add these as feature in future?

**Comment by svenwltr** [comment]
@moradiyaamit There is still a proposal missing on what to do with "untaggable" resources and how the config should look like.

**Comment by ekristen** [comment]
Feel free to open an issue over at https://github.com/ekristen/aws-nuke if this is still a desired feature

----

Please see the copy of the notice from the README about the deprecation of this project. Sven was kind enough to grant me access to help triage and close issues and pull requests that have already been addressed in the actively maintained fork. Some additional information is located in the [welcome issue](https://github.com/ekristen/aws-nuke/issues/276) for more information. 

> [!CAUTION]
> This repository for aws-nuke is no longer being actively maintained. We recommend users to switch to the actively maintained fork of this project at [ekristen/aws-nuke](https://github.com/ekristen/aws-nuke).
> We appreciate all the support and contributions we've received throughout the life of this project. We believe that the fork will continue to provide the functionality and support that you have come to expect from aws-nuke.
> Please note that this deprecation means we will not be addressing issues, accepting pull requests, or making future releases from this repository.
> Thank you for your understanding and support.
