### ISSUE TITLE
error with go 1.13 ?

### ISSUE THREAD

**Issue by agarossi** [rebuy-de/aws-nuke#433]
trying to make build with go version go1.13.4 linux/amd64
 I get this output:

[ec2-user@ip-172-31-29-247 aws-nuke]$ make build
go mod vendor
github.com/rebuy-de/aws-nuke/pkg/awsutil imports
        net imports
        golang_org/x/net/lif: malformed module path "golang_org/x/net/lif": missing dot in first path element
github.com/rebuy-de/aws-nuke/pkg/awsutil imports
        net imports
        golang_org/x/net/route: malformed module path "golang_org/x/net/route": missing dot in first path element
github.com/rebuy-de/aws-nuke/pkg/awsutil imports
        net/http imports
        golang_org/x/net/http2/hpack: malformed module path "golang_org/x/net/http2/hpack": missing dot in first path element
github.com/rebuy-de/aws-nuke/pkg/awsutil imports
        net/http imports
        golang_org/x/net/idna: malformed module path "golang_org/x/net/idna": missing dot in first path element
github.com/rebuy-de/aws-nuke/pkg/awsutil imports
        net/http imports
        golang_org/x/net/lex/httplex: malformed module path "golang_org/x/net/lex/httplex": missing dot in first path element
github.com/rebuy-de/aws-nuke/pkg/awsutil imports
        net/http imports
        golang_org/x/net/proxy: malformed module path "golang_org/x/net/proxy": missing dot in first path element
github.com/rebuy-de/aws-nuke/cmd imports
        github.com/aws/aws-sdk-go/aws/session imports
        crypto/tls imports
        golang_org/x/crypto/chacha20poly1305: malformed module path "golang_org/x/crypto/chacha20poly1305": missing dot in first path element
github.com/rebuy-de/aws-nuke/cmd imports
        github.com/aws/aws-sdk-go/aws/session imports
        crypto/tls imports
        golang_org/x/crypto/curve25519: malformed module path "golang_org/x/crypto/curve25519": missing dot in first path element
make: *** [vendor] Error 1

seems something related to go 1.13?
thanks

**Comment by agarossi** [comment]
autoclosing :

**sudo su**
make build

**Comment by svenwltr** [comment]
Hello @agarossi,

good that it worked for you, but you actually do not need to compile it yourself, if you do not want to develop on *aws-nuke*. You can simply download precompiled releases from [the releases page](https://github.com/rebuy-de/aws-nuke/releases).

**Comment by sarinkejohn** [comment]
malformed module path "golang_org/x/net/lex/httplex": missing dot in first path element
how did you go about it
