### ISSUE TITLE
Specifying custom endpoints

### ISSUE THREAD

**Issue by rom-stratoscale** [rebuy-de/aws-nuke#434]
Hey,
Is there and option to run nuke with custom endpoints (instead of *.amazonaws.com)?
Similar to what is supported by TF 
https://www.terraform.io/docs/providers/aws/guides/custom-service-endpoints.html ?

Thanks

**Comment by svenwltr** [comment]
There is an [open PR](https://github.com/rebuy-de/aws-nuke/pull/371) for this, but unfortunately it did not make it into `master`, yet.

**Comment by rom-stratoscale** [comment]
@svenwltr we noticed it exists and working on finalizing it.
