### ISSUE TITLE
v2.13.0 cannot get credentials when running on Lambda

### ISSUE THREAD

**Issue by mseiwald** [rebuy-de/aws-nuke#435]
Hi,

we are running aws-nuke from a Python Lambda handler like this:

```
os.system("echo <account_name> | ./aws-nuke --profile default -c config.yaml --no-dry-run --force")
```

This has been working fine up until version `v2.11.0`. After upgrading to `v2.13.0` the execution fails to get AWS credentials.

```
Error: failed get caller identity: NoCredentialProviders: no valid providers in chain. Deprecated.
For verbose messaging see aws.Config.CredentialsChainVerboseErrors
```

Downgrading immediately resolved the issue. Is there some workaround to make it work on Lambda?

Regards
Michael

**Comment by svenwltr** [comment]
Hello @mseiwald,

can you show us how the `default` profile looks like? Of course with redacted secrets.

**Comment by mseiwald** [comment]
We are running on Lambda with an IAM role, there is no profile configured..

**Comment by svenwltr** [comment]
Then, why are you specifying the `default` profile? Can you try this:

```
os.system("echo <account_name> | ./aws-nuke -c config.yaml --no-dry-run --force")
```

**Comment by mseiwald** [comment]
When running without `--profile` we get this error:

```Error: You have to specify the --profile flag OR --access-key-id with --secret-access-key and optionally --session-token```

**Comment by svenwltr** [comment]
Ah, I see. We need to implement that *aws-nuke* falls back to EC2 Instance Roles, if there is no profile given.

**Comment by mseiwald** [comment]
Still strange that it worked fine before v2.13.0 even with `--profile`

**Comment by mseiwald** [comment]
When setting `CredentialsChainVerboseErrors` to `true` I get this error output:

```Error: failed get caller identity: NoCredentialProviders: no valid providers in chain
caused by: EnvAccessKeyNotFound: failed to find credentials in the environment.
SharedCredsLoad: failed to load profile, default.
EC2RoleRequestError: no EC2 instance role found
caused by: RequestError: send request failed
caused by: Get http://169.254.169.254/latest/meta-data/iam/security-credentials/: dial tcp 169.254.169.254:80: connect: connection refused
```

As I said the Lambda function has a role associated with it and it works flawlessly with `v2.11.0` so I assume it has something to do with the updated `aws-sdk-go`

**Comment by mseiwald** [comment]
And I can confirm that `v2.13.0` with (downgraded) `aws-sdk-go v1.17.8` works. 🎉 

Will report my findings upstream.

**Comment by mseiwald** [comment]
Actually what triggers the problem seems to be setting the `profile` on the `session.Options`. Reported here https://github.com/aws/aws-sdk-go/issues/3008

**Comment by svenwltr** [comment]
https://github.com/rebuy-de/aws-nuke/pull/438 should solve it, but it needs some testing. I will do it in the next days.

**Comment by tabdon** [comment]
@mseiwald Off topic, but how did you get the the <account_name> into the config.yml file?

**Comment by ajobayer** [comment]
@mseiwald, Would you mind to explain how are you using aws-nuke and setting up through lambda functions?

I really appreciate if you can give me some hints. Right now I am running nuke from EC2 and when saw your comments here though it would be really good idea if I can handle through lambda funciton.

**Comment by ekristen** [comment]
Please try with v3 at https://github.com/ekristen/aws-nuke, if the issue still persists open an issue there. Thank you.

----

Please see the copy of the notice from the README about the deprecation of this project. Sven was kind enough to grant me access to help triage and close issues and pull requests that have already been addressed in the actively maintained fork. Some additional information is located in the [welcome issue](https://github.com/ekristen/aws-nuke/issues/276) for more information. 

> [!CAUTION]
> This repository for aws-nuke is no longer being actively maintained. We recommend users to switch to the actively maintained fork of this project at [ekristen/aws-nuke](https://github.com/ekristen/aws-nuke).
> We appreciate all the support and contributions we've received throughout the life of this project. We believe that the fork will continue to provide the functionality and support that you have come to expect from aws-nuke.
> Please note that this deprecation means we will not be addressing issues, accepting pull requests, or making future releases from this repository.
> Thank you for your understanding and support.
