### ISSUE TITLE
Cannot perform the operation on the protected role 'AWSReservedSSO*

### ISSUE THREAD

**Issue by naumvd95** [rebuy-de/aws-nuke#441]
```global - IAMRole - AWSReservedSSO_AdministratorAccess_9a45132a4fc687f4 - failed
time="2019-12-16T19:13:07Z" level=error msg="There are resources in failed state, but none are ready for deletion, anymore."
time="2019-12-16T19:13:07Z" level=error msg="UnmodifiableEntity: Cannot perform the operation on the protected role 'AWSReservedSSO_AdministratorAccess_9a45132a4fc687f4' - this role is only modifiable by AWS\n\tstatus code: 400, request id: 0f796535-610b-4c65-b638-29cf646b4a96"
time="2019-12-16T19:13:07Z" level=error msg="UnmodifiableEntity: Cannot perform the operation on the protected role 'AWSReservedSSO_AdministratorAccess_9a45132a4fc687f4' - this role is only modifiable by AWS\n\tstatus code: 400, request id: 2019e4ea-a967-42d1-b0c6-d38172343cd6"
Error: failed
global - IAMRolePolicyAttachment - AWSReservedSSO_AdministratorAccess_9a45132a4fc687f4 -> AdministratorAccess - [PolicyName: "AdministratorAccess", RoleName: "AWSReservedSSO_AdministratorAccess_9a45132a4fc687f4"] - failed```

**Comment by naumvd95** [comment]
```Error: failed
global - IAMRolePolicyAttachment - AWSReservedSSO_AdministratorAccess_9a45132a4fc687f4 -> AdministratorAccess - [PolicyName: "AdministratorAccess", RoleName: "AWSReservedSSO_AdministratorAccess_9a45132a4fc687f4"] - failed```

IAMRolePolicyAttachment also affected

**Comment by ekristen** [comment]
Closing due to age, if this is still an issue please open an issue at https://github.com/ekristen/aws-nuke

----

Please see the copy of the notice from the README about the deprecation of this project. Sven was kind enough to grant me access to help triage and close issues and pull requests that have already been addressed in the actively maintained fork. Some additional information is located in the [welcome issue](https://github.com/ekristen/aws-nuke/issues/276) for more information. 

> [!CAUTION]
> This repository for aws-nuke is no longer being actively maintained. We recommend users to switch to the actively maintained fork of this project at [ekristen/aws-nuke](https://github.com/ekristen/aws-nuke).
> We appreciate all the support and contributions we've received throughout the life of this project. We believe that the fork will continue to provide the functionality and support that you have come to expect from aws-nuke.
> Please note that this deprecation means we will not be addressing issues, accepting pull requests, or making future releases from this repository.
> Thank you for your understanding and support.
