### ISSUE TITLE
Hang after LifecycleHook Scan

### ISSUE THREAD

**Issue by the-chronomancer** [rebuy-de/aws-nuke#442]
Team,

Love your tool!

Unfortunately, it seems that whatever resource exists after LifecycleHook in the scanning process seems to halt aws-nuke entirely. This is when running:

./aws-nuke-v2.13.0-darwin-amd64 -c nuke-config.yaml --profile my-profile-here

In the us-east-2 region. When running against us-east-1 it seems to complete the scan, but if I point this against us-east-2 it will just sit immediately after the LifecycleHook scan and do nothing.

Is there a list of the order of specific resources, so I can test excluding those that come directly after the LifecycleHook?

Thank you for your time!

**Comment by the-chronomancer** [comment]
Looks to be an issue with S3 buckets, I have excluded those and can continue on just fine!

I see that this is mentioned in the docs, due to the global nature of S3, so I will close this issue :)

**Comment by bjoernhaeuser** [comment]
@the-chronomancer do you have a lot of objects in the bucket you are scanning? That could cause a lot of time spent in scanning these buckets.
