### ISSUE TITLE
global filter for resources.

### ISSUE THREAD

**Issue by agarossi** [rebuy-de/aws-nuke#445]
is it possible to filter for any resource that contain in the name "DONOTDELETE" or something similar?
same for tags?

also what is the syntax for filtering a S3 bucket which name contain a string?

filters:
      S3Bucket:
      - type: contain
        value: "DONOTDELETE"

correct?

**Comment by svenwltr** [comment]
Hello @agarossi. You have to individually filter each resource and the capabilities of filtering a resource depends on their respective properties. You can see those properties when doing a dry run on an account.

**Comment by dxciberaws** [comment]
+1
Would be nice to be able to define a generic filter that would apply to all resoures. This filter, of course would have to include every applicable property. Would be a much more concise way to express it and would apply to future resources.
We use naming and tagging convention to differentiate resources that are part of the account's baseline configuration, that would not want to remove. Other uses would be to scope the deletion to a project.

**Comment by chris2fer** [comment]
Came here to ask and suggest the same.  There should be a master Tag for all resources.  "One Tag to Filter Them All"

**Comment by ekristen** [comment]
[Global Filters](https://ekristen.github.io/aws-nuke/config-filtering/#global) have been implemented over on [this fork of aws nuke](https://github.com/ekristen/aws-nuke) which is the successor and active fork of this tool.

Try it out. If you run into issues, report it in an issue over there.

----

Please see a copy of the notice from the README about the deprecation of this project. Sven was kind enough to grant me access to help triage and close issues and pull requests that have already been addressed in the actively maintained fork. Some additional information is located in the [welcome issue](https://github.com/ekristen/aws-nuke/issues/276) for more information. 

> [!CAUTION]
> This repository for aws-nuke is no longer being actively maintained. We recommend users to switch to the actively maintained fork of this project at [ekristen/aws-nuke](https://github.com/ekristen/aws-nuke).
> We appreciate all the support and contributions we've received throughout the life of this project. We believe that the fork will continue to provide the functionality and support that you have come to expect from aws-nuke.
> Please note that this deprecation means we will not be addressing issues, accepting pull requests, or making future releases from this repository.
> Thank you for your understanding and support.
