### ISSUE TITLE
MediaLive resources are not detected and nuked

### ISSUE THREAD

**Issue by powelli** [rebuy-de/aws-nuke#446]
**Steps to reproduce**
1. Create a MediaLive Channel, MediaLive Input & MediaLive Input Security Group in your AWS account
2. Run `aws-nuke` and review the dry-run output for any MediaLive resources

**Expected result**
- MediaLiveChannel, MediaLiveInput and MediaLiveInputSecurityGroup resources are listed

**Actual result**
- None of the above resources are listed

**Additional details**
- `aws-nuke` version - v2.13.0 (via Docker image `quay.io/rebuy/aws-nuke:v2.13.0`)
- MediaLive channel state: IDLE
- config.yml:
```
regions:
- eu-west-2
- global

account-blacklist:
- "999999999999" # production

accounts:
  "<my_aws_account_id>": {}
```
- Docker run command:
```
docker run \
    --rm -it \
    -v /path/to/nuke-config.yml:/home/aws-nuke/config.yml \
    -v /path/to/.aws:/home/aws-nuke/.aws \
    quay.io/rebuy/aws-nuke:v2.13.0 \
    --profile <my_aws_profile> \
    --config /home/aws-nuke/config.yml
```

**Comment by deekayw0n** [comment]
Just a note on this rather evolving issue, it seems that aws-nuke (version v2.19.0.2.gf8495e4) does iterate through these resources and attempts to destroy them; however there seems to be an order of operations problem causing ConflictException errors

Based on my CloudTrail, from DeleteChannel:
`Cannot delete a channel that has not been stopped yet. Please stop the channel and try again.`

From DeleteInput:
`Input #### is busy, it cannot be deleted`

I think aws-nuke would just need to call the StopChannel event for any active channel, and then can run the delete tasks.

**Comment by ekristen** [comment]
MediaLive Channels, Inputs, and Input Security Groups are now supported, see the fork at https://github.com/ekristen/aws-nuke

If you have a chance, please check it out and let us know if you run into an issues by opening an issue over on the fork.

----

Please see the copy of the notice from the README about the deprecation of this project. Sven was kind enough to grant me access to help triage and close issues and pull requests that have already been addressed in the actively maintained fork. Some additional information is located in the [welcome issue](https://github.com/ekristen/aws-nuke/issues/276) for more information. 

> [!CAUTION]
> This repository for aws-nuke is no longer being actively maintained. We recommend users to switch to the actively maintained fork of this project at [ekristen/aws-nuke](https://github.com/ekristen/aws-nuke).
> We appreciate all the support and contributions we've received throughout the life of this project. We believe that the fork will continue to provide the functionality and support that you have come to expect from aws-nuke.
> Please note that this deprecation means we will not be addressing issues, accepting pull requests, or making future releases from this repository.
> Thank you for your understanding and support.
