### ISSUE TITLE
Disable Security Hub

### ISSUE THREAD

**Issue by gebailey** [rebuy-de/aws-nuke#452]
I don't believe Security Hub gets disabled by aws-nuke.  Security Hub, if enabled, can incur costs associated with AWS Config rules and/or costs per finding.  Ideally, Security Hub would be disabled by aws-nuke in any regions that are processed.

**Comment by RockAfeller2013** [comment]
also GuardDuty needs to be disabled. Ive tested and this script does not disable GuardDuty

**Comment by ekristen** [comment]
This is implemented in the fork https://github.com/ekristen/aws-nuke 

If you have a chance, please check it out and let us know if you run into an issues by opening an issue over on the fork.

----

Please see the copy of the notice from the README about the deprecation of this project. Sven was kind enough to grant me access to help triage and close issues and pull requests that have already been addressed in the actively maintained fork. Some additional information is located in the [welcome issue](https://github.com/ekristen/aws-nuke/issues/276) for more information. 

> [!CAUTION]
> This repository for aws-nuke is no longer being actively maintained. We recommend users to switch to the actively maintained fork of this project at [ekristen/aws-nuke](https://github.com/ekristen/aws-nuke).
> We appreciate all the support and contributions we've received throughout the life of this project. We believe that the fork will continue to provide the functionality and support that you have come to expect from aws-nuke.
> Please note that this deprecation means we will not be addressing issues, accepting pull requests, or making future releases from this repository.
> Thank you for your understanding and support.
