### ISSUE TITLE
Resource deletion says failed with Adminstrator permission when performing aws-nuke

### ISSUE THREAD

**Issue by Leectan** [rebuy-de/aws-nuke#457]
all resources say "failed" when performing aws-nuke. Please see attached and Please advise.
<img width="668" alt="Screen Shot 2020-01-24 at 1 04 15 PM" src="https://user-images.githubusercontent.com/24819052/73092667-fee4ee80-3eaa-11ea-8e54-132957f7727f.png">

**Comment by svenwltr** [comment]
Hello @Leectan. The actual error messages are located at the end of the *aws-nuke* output. Those failed resource also might recover. Please show us the end of the output.

**Comment by Leectan** [comment]
<img width="1094" alt="Screen Shot 2020-01-25 at 12 39 07 PM" src="https://user-images.githubusercontent.com/24819052/73125859-ca8c3380-3f79-11ea-9604-fe31a7d48e84.png">

**Comment by Leectan** [comment]
@svenwltr any update on this?

**Comment by svenwltr** [comment]
Hello @Leectan. Sorry for the late response. It looks like you provided invalid access keys.

**Comment by Leectan** [comment]
@svenwltr double checked access keys without any issue. 2nd time performed with all the failed message.

**Comment by bjoernhaeuser** [comment]
@Leectan 

Are you able to use the credentials you are providing directly in the aws-cli? Are you using MFA? Do you use assumed roles?

This could potentially help you resolve the problem: https://stackoverflow.com/questions/34582318/how-can-i-resolve-the-error-the-security-token-included-in-the-request-is-inval

**Comment by Leectan** [comment]
@bjoernhaeuser yes, I'm using --access-keys  and --secret-key perimeters and inject them directly in the CLI. The account doesn't have MFA. Not using assumed roles.

**Comment by Leectan** [comment]
@bjoernhaeuser yes, I'm using --access-keys  and --secret-key perimeters and inject them directly in the CLI. The account doesn't have MFA. Not using assumed roles.

**Comment by Leectan** [comment]
Still getting error with Admin permission, no MFA. No assumed roles. Any other suggestion is appreciated. 

<img width="1701" alt="2" src="https://user-images.githubusercontent.com/24819052/75281725-c1db8700-57dd-11ea-99fa-12046fc451cb.png">

**Comment by bjoernhaeuser** [comment]
Well, as already said this is highly likely a problem in your configuration. Can you check that the account ids match when you execute `aws sts get-caller-identity` with the same access/secret key please?

**Comment by Leectan** [comment]
also, IAM user and IAM profile that are specified in the config file for filter is also removed when execute the cmd. 

<img width="339" alt="3" src="https://user-images.githubusercontent.com/24819052/75282911-d3be2980-57df-11ea-952f-0c13981e7001.png">

**Comment by svenwltr** [comment]
@Leectan Can you please check if this command works for your?

```
AWS_ACCESS_KEY_ID=YOUR_ID AWS_SECRET_ACCESS_KEY=YOUR_SECRET aws iam list-roles
```

Please replace access key id and secret access key with the same credentials you used for *aws-nuke*

**Comment by rbeede** [comment]
I am having a similar issue.  When I ran the dry-run with the IAM account with admin privilege it listed everything as expected.  When I ran the actual nuke I got the failed message many times even though I'm using the same credentials.

Maybe AWS is rate limiting?

**Comment by rahmansamia** [comment]
@Leectan @rbeede are you able to run aws-nuke? I am having the same issue.

**Comment by ekristen** [comment]
@Leectan For the access denied on `iam:ListRole` it either does not have permissions or a SCP is blocking the action. For the `security token is invalid` this means the STS service was used. Depending on how you are authenticating AWS nuke these tokens can be only valid for 1 hour. 

Please test using the [actively managed fork of aws-nuke](https://github.com/ekristen/aws-nuke).

If the issue still persists, please open an issue on the fork.

----

Please see the copy of the notice from the README about the deprecation of this project. Sven was kind enough to grant me access to help triage and close issues and pull requests that have already been addressed in the actively maintained fork. Some additional information is located in the [welcome issue](https://github.com/ekristen/aws-nuke/issues/276) for more information. 

> [!CAUTION]
> This repository for aws-nuke is no longer being actively maintained. We recommend users to switch to the actively maintained fork of this project at [ekristen/aws-nuke](https://github.com/ekristen/aws-nuke).
> We appreciate all the support and contributions we've received throughout the life of this project. We believe that the fork will continue to provide the functionality and support that you have come to expect from aws-nuke.
> Please note that this deprecation means we will not be addressing issues, accepting pull requests, or making future releases from this repository.
> Thank you for your understanding and support.
