### ISSUE TITLE
Filter 'older-than X hours'

### ISSUE THREAD

**Issue by naumvd95** [rebuy-de/aws-nuke#459]
Hello, wanted to know, do you have any plans to create filter by time?
IMO it will be very handy in case of accounts cleanup kinda cicd aws  accounts , where each runs takes about 2 hours , and all resources older than 2 hours should be deleted.
Does anyone plan to work on it? or I can jump in?

**Comment by svenwltr** [comment]
Hello @naumvd95. This looks like a duplicate of https://github.com/rebuy-de/aws-nuke/issues/393 and it does not look like anybody is working on it right now.

**Comment by naumvd95** [comment]
thanks, will look on it
closed as duplicate of #393
