### ISSUE TITLE
SIGSEGV: segmentation violation

### ISSUE THREAD

**Issue by sabrehagen** [rebuy-de/aws-nuke#46]
I encountered a segmentation fault. This is my log. Any assistance debugging appreciated:

https://gist.github.com/sabrehagen/b26e896c256e9d986dde08e505317ad9

**Comment by svenwltr** [comment]
Could you please update to [1.2.2](https://github.com/rebuy-de/aws-nuke/releases/tag/v1.2.2) and try again?

**Comment by svenwltr** [comment]
Since there is no response, I guess the update fixed it.
