### ISSUE TITLE
destroy eks cluster with aws managed node groups

### ISSUE THREAD

**Issue by MHARDEGE** [rebuy-de/aws-nuke#465]
We tear down eks cluster with aws-nuke. If we use aws - managed node groups in our eks setup, aws-nuke terminates with errors because the managed node groups are dependent on the eks cluster, so they cannot be deleted and remain there. Could you tear off the function of the eks cluster, to destroy existing node groups before of the eks cluster yourself ?

here the error message:
eu-central-1 - EKSCluster - XXXXX-XXXXX-XXXXX-XXXXX - failed
ERRO[0998] ResourceInUseException: Cluster has node groups attached
	status code: 409, request id: XXXXX-XXXXX-XXXX-XXXXX-XXXXXXX

**Comment by bjoernhaeuser** [comment]
@MHARDEGE Thank you for your report.

`aws-nuke` does not support EKS node groups (afaics), a resource which is simply missing. Would you want to provide the necessary patch?

**Comment by spr-mweber3** [comment]
@bjoernhaeuser I'll do.
