### ISSUE TITLE
Cant delete HostedZone because not empty, skipped NS Records

### ISSUE THREAD

**Issue by MHARDEGE** [rebuy-de/aws-nuke#467]
We use the new feature in https://github.com/rebuy-de/aws-nuke/pull/439 to clean up all Route53 HostedZone. To clean the HostedZone it is assumed that the HostedZone is cleaned of all records, except the primary NS and SOA records for the HostedZone. We work with many name server delegations for different domains, so we have many NS recordsets in one hosted zone. All SOA and NS records are skipped in the code, so all other records for delegation remain alive and the HostedZone cannot be deleted.

How was that meant, to work ?

**Comment by bjoernhaeuser** [comment]
@MHARDEGE You have to specify that resource records are nuked as well. Then aws-nuke will retry and eventually find the hosted-zone to be empty and AWS will then delete it.

**Comment by MHARDEGE** [comment]
> @MHARDEGE You have to specify that resource records are nuked as well. Then aws-nuke will retry and eventually find the hosted-zone to be empty and AWS will then delete it.

Hi @bjoernhaeuser, the resource records in https://github.com/rebuy-de/aws-nuke/blob/master/resources/route53-resource-records.go# are normally deleted. In the lines https://github.com/rebuy-de/aws-nuke/blob/4ceae299fa75efc1a7cab20f99442311d392d6ff/resources/route53-resource-records.go#L79-L89 all records are skipped which are of type NS. However, if I have my own, several NS records e.g. for the delegation they have to be deleted, otherwise the HostedZone cannot be deleted.
This can be achieved by expanding the query and skipping records of type NS with the name of the subdomain.

**Comment by svenwltr** [comment]
Hello @MHARDEGE. You are right. Are you willing to provide a PR to fix it?

**Comment by MHARDEGE** [comment]
> Hello @MHARDEGE. You are right. Are you willing to provide a PR to fix it?

Yes, we will adapt and test the code, my colleague @jami will do a PR for it.

**Comment by MHARDEGE** [comment]
This issue fixed in https://github.com/rebuy-de/aws-nuke/pull/473#
