### ISSUE TITLE
Not all Lambdas are listed for nuke

### ISSUE THREAD

**Issue by sanyer** [rebuy-de/aws-nuke#47]
31 Lambdas out of 79 are not shown in `aws-nuke`'s output.
I'll investigate it further running aws-nuke in debugger.

**Comment by svenwltr** [comment]
@sanyer My first idea is that they might be in different regions which aren't specified in the config.

Besides that it might be interesting, if these lambdas appear within the AWS CLI: `aws lambda list-functions`.

**Comment by sanyer** [comment]
Yes, I checked that.
Those 31 are shown in `aws lambda list-functions` output.

**Comment by svenwltr** [comment]
Do they also appear when limiting them to the regions you specified in the aws-nuke config?

```
AWS_DEFAULT_REGION=eu-west-1 aws lambda list-functions
```

If they also appear there, I would need the output of `aws lamba list-functions` for further debugging.

**Comment by svenwltr** [comment]
I am closing this, because there is no response. Feel free to reopen.
