### ISSUE TITLE
New resource: Global accelerator

### ISSUE THREAD

**Issue by guy-suli** [rebuy-de/aws-nuke#479]
It will be nice to add support for deleting  Global accelerator with all the dependencies (Like: VPC, RT and etc)

**Comment by jami** [comment]
VPC and RT are not part of the GA environment but Accelerators, Listeners and Endpoints are.
[https://github.com/rebuy-de/aws-nuke/pull/524](https://github.com/rebuy-de/aws-nuke/pull/524)

**Comment by der-eismann** [comment]
Closing since #524 was merged.
