### ISSUE TITLE
Idea: security precaution

### ISSUE THREAD

**Issue by Overbryd** [rebuy-de/aws-nuke#487]
On the second prompt of the account id, the user must enter the position at wich Pi encodes the numeric account id.

### Example

Account ID 077892811

```
Please enter your account id: 077892811
[snip aws-nuke lists resources]
Please enter the position at which the account id is encoded in pi: 101751860
```

Users can use widely available resources like https://www.angio.net/pi/ to determine the Pi encoding position of their account id. Also this way, its much harder to script aws nuke.

**Comment by der-eismann** [comment]
Is this a serious idea? I don't really see the advantage in this.
> Also this way, its much harder to script aws nuke.

Why would you want to make it harder? Lots of people use it with Lambdas/cronjobs to clean their accounts. Also it doesn't really make it harder as the values are static. You could look up the position for every account, save it and enter it via `expect` or similar while scripting.

**Comment by Overbryd** [comment]
Ah dang, you are right. Pi positions are static, and thus very easy to map. I will see if I can come up with a better idea. See you next time.
