### ISSUE TITLE
Resources in ap-northeast-3 not being evaluated

### ISSUE THREAD

**Issue by eXodus1440** [rebuy-de/aws-nuke#490]
Hi Team,

It appears that resources in ap-northeast-3 are not being fully evaluated for removal, at least EC2/EBS/SG resources are being skipped in my case - tests against apne1/apne2 work as expected

Currently using `aws-nuke-v2.14.0-linux-amd64`

With the following config
```regions:
- global
- ap-northeast-1
- ap-northeast-2
- ap-northeast-3

account-blacklist:
- "999999999999" # production

resource-types:
  excludes:
  - EC2VPC
  - EC2Subnet
  - EC2RouteTable
  - EC2DHCPOption
  - EC2InternetGateway
  - EC2InternetGatewayAttachment
  - EC2VPCEndpoint
  - IAMRole


accounts:
  "888888888888": {} # aws-nuke-example
```

**Comment by svenwltr** [comment]
Hello,

can you give us a hint what kind of resources are skipped? Are those some special kind of EC2/EBS/SG resources? If you delete the non-skipped resources. Do the missing ones appear in the next run? Is there a fixed number of resources that are shown to you?

**Comment by vaclavdobsicek** [comment]
I suppose all resources in this region are skipped - in my case all 5 default VPC parts (EC2VPC, 3x EC2Subnet, EC2DHCPOptions)

version:     v2.15.0.beta.2
