### ISSUE TITLE
aws-nuke - no output.

### ISSUE THREAD

**Issue by queglay** [rebuy-de/aws-nuke#493]
When using this binary release aws-nuke-v2.14.0-linux-amd64 on centos 7, it produces no output.
```
[user@workstation aws-nuke]$ aws-nuke -c ./nuke-config.yml --profile aws-nuke-profile
```
The command above will produce no output.

**Comment by svenwltr** [comment]
Hello @queglay,

does it exit? How long did you wait?

**Comment by queglay** [comment]
Yes it exits immediately.

**Comment by svenwltr** [comment]
* What does your config look like?
* Did it work on some point?
* Do you get more useful information when adding the `--verbose` flag?
