### ISSUE TITLE
GitHub Docker Registry requires auth for public repos

### ISSUE THREAD

**Issue by reiz** [rebuy-de/aws-nuke#496]
The GitHub Docker Registry requires auth for public repos. That makes a docker pull for this projects a bit hard. Would be nice if this Docker image would be available on https://hub.docker.com/

**Comment by der-eismann** [comment]
We push our images to [quay.io](https://quay.io/repository/rebuy/aws-nuke), so you can use them without auth via `docker pull quay.io/rebuy/aws-nuke`

**Comment by reiz** [comment]
Works for me! Awesome! Thx!
