### ISSUE TITLE
Provide an option(s) to not require confirmation prompts

### ISSUE THREAD

**Issue by Gowiem** [rebuy-de/aws-nuke#498]
## Issue

I built [terraform-aws-nuke-bomber](https://github.com/masterpointio/terraform-aws-nuke-bomber) so that I would have the ability to completely clean one of my accounts on a schedule. To accomplish this with aws-nuke, [I needed to write this expect script](https://github.com/masterpointio/terraform-aws-nuke-bomber/blob/master/bomber.sh) to allow me to run the script headless. It would be awesome to not have to use that and instead just supply a flag or two.  

## Feature Request

Add a `--no-confirmation` CLI flag which removes the confirmation checks.

**Comment by svenwltr** [comment]
Hello @Gowiem.

What about the `--force` flag? If I understand correctly, this is what you are looking for.

**Comment by Gowiem** [comment]
@svenwltr Haha I found that 2 minutes after posting this in the code and I'm now in progress on updating my terraform repo. Sorry for the confusion -- Closing out. I will try to add a docs PR so that flag is in the README for others.
