### ISSUE TITLE
Timeout error while running aws-nuke

### ISSUE THREAD

**Issue by pragya-nayak** [rebuy-de/aws-nuke#502]
Hi,

I am facing timeout error when there are more aws resources to nuke while when there is less resources aws nuke is deleting the resources. I have installed nuke on EC2 instance t2.micro instance type. The reason can be because of the instance type of EC2. Could you please suggest the EC2 instance type. Here are the targeted resources :

  targets:
  - AutoScalingGroup
  - LaunchConfiguration
  - EC2Instance
  - EC2Volume
  - EC2Image
  - EC2Snapshot
  - ELBLoadBalancer
  - ELBv2LoadBalancer
  - ELBv2TargetGroup
  - RDSInstance
  - RDSSnapshot
  - DynamoDBTable
  - RedshiftCluster
  - RedshiftSnapshot
  - ElasticBeanstalkApplication
  - ElasticBeanstalkEnvironment

I got the timeout error when there were 33 resources to delete including EC2 instance, EC2 Image, EC2 Snapshot, EBS Volume, RDS Instance, Dynamo DB, ASG and Launch Configuration

**Comment by svenwltr** [comment]
Hello @pragya-nayak.

Sorry for the late response. Could you please post the actual error message?

**Comment by pragya-nayak** [comment]
I was using httpd as a frontend that was causing the error because aws nuke is taking more time in deleting the resources, httpd was not get getting response in default time. I have increased the timeout at server configuration and it worked. Thanks for your response.
