### ISSUE TITLE
Tag filter is not working on all resources 

### ISSUE THREAD

**Issue by pragya-nayak** [rebuy-de/aws-nuke#505]
Hi,

I am using tag filter to filter the resources from deletion based on tags. I am using aws-nuke version 2.14.0 

Seems like still all resources are not supported with tag filter as when I tried with ASG tag, filter was not excluding the asg from deletion though other resources like ec2, dynamodb etc are filtering based on the tags.

Could anyone please help with the list of resources that support tags.

**Comment by svenwltr** [comment]
Hello @pragya-nayak.

Sorry for the late response. Currently tags are not supported by many resources. Currently it is just:

```
cloudformation-stack.go
dynamodb-tables.go
ec2-client-vpn-endpoint.go
ec2-dhcp-options.go
ec2-eip.go
ec2-images.go
ec2-instances.go
ec2-internet-gateway-attachments.go
ec2-internet-gateways.go
ec2-nat-gateways.go
ec2-network-interfaces.go
ec2-route-tables.go
ec2-security-groups.go
ec2-subnets.go
ec2-tgw-attachments.go
ec2-tgw.go
ec2-volume.go
ec2-vpc.go
ec2-vpcEndpoint.go
ec2-vpn-connections.go
ec2-vpn-gateway-attachments.go
elb-elb.go
elbv2-alb.go
elbv2-targetgroup.go
fsx-backups.go
fsx-filesystems.go
iam-role-policy.go
iam-roles.go
lambda-functions.go
rds-clusters.go
rds-dbclusterparametergroups.go
rds-dbparametergroups.go
rds-instances.go
rds-snapshots.go
rds-subnets.go
s3-buckets.go
```

**Comment by pragya-nayak** [comment]
Thanks @svenwltr for the response
