### ISSUE TITLE
Docker repository is down?

### ISSUE THREAD

**Issue by dziedrius** [rebuy-de/aws-nuke#506]
When I try to run docker as stated in docs:
```
docker: Error response from daemon: Get https://quay.io/v2/rebuy/aws-nuke/manifests/latest: received unexpected HTTP status: 500 Internal Server Error.
```

It might be related to:
https://status.quay.io/incidents/kw2627bsdwd9

**Comment by svenwltr** [comment]
Hello @dziedrius.

Yes, the Docker image that is hosted on Quay.io is down because of the Quay outage.

Since we are not operating Quay, there is nothing we can do about it and we do not have enough time right now to migrate it to some other registry.
