### ISSUE TITLE
Listing SESReceiptFilter and SESReceiptRuleSet failed on Non-SES Regions 

### ISSUE THREAD

**Issue by dxciberaws** [rebuy-de/aws-nuke#513]
SES service is only provided through a limited number of regional endpoints. These are different for sending, receiving or API access.

In this particular case we are facing an error caused by invoking the API action ListReceiptFilters on an region where the API access is available but is not a receiving enabled region.

The main problem being that it causes an uncontrolled exit of the aws-nuke process and stops the rest of the execution.

time="2020-06-03T10:33:00Z" level=error msg="Listing SESReceiptFilter failed:\n    InvalidAction: Unavailable Operation\n    \tstatus code: 400, request id: 113f4b5e-421a-4975-a050-44ac13731931"

This can be tested with AWS CLI:

On a non SES receiving region:

\> aws ses list-receipt-filters --profile SEC --region eu-central-1

An error occurred (InvalidAction) when calling the ListReceiptFilters operation: Unavailable Operation

On a SES receiving region:

aws ses list-receipt-filters --profile SEC --region eu-west-1
{
    "Filters": []
}

The same error happens for Receipt Rule Sets:

/> aws ses list-receipt-rule-sets --profile SEC --region eu-central-1

An error occurred (InvalidAction) when calling the ListReceiptRuleSets operation: Unavailable Operation

Best option is probably to ignore the error skipping the resource type it if occurs.

**Comment by shacharhelmer** [comment]
+1, also this clutters the output.
My solution is to simply exclude such resources from within the config yaml.

**Comment by ypresto** [comment]
FYI:
I found this error also in [terraformer](https://github.com/GoogleCloudPlatform/terraformer) and aws cli.
I posted this to AWS official forum; please vote it. :pray:
https://repost.aws/questions/QUqXi6glbhRyeiyNPsBVmi9Q/bug-ses-listreceiptrulesets-returns-invalidaction-error

**Comment by ekristen** [comment]
I believe this is no longer an issue. Please test v3 of the tool from https://github.com/ekristen/aws-nuke. If the problem still persists, open an issue there. Thanks.

----

Please see the copy of the notice from the README about the deprecation of this project. Sven was kind enough to grant me access to help triage and close issues and pull requests that have already been addressed in the actively maintained fork. Some additional information is located in the [welcome issue](https://github.com/ekristen/aws-nuke/issues/276) for more information. 

> [!CAUTION]
> This repository for aws-nuke is no longer being actively maintained. We recommend users to switch to the actively maintained fork of this project at [ekristen/aws-nuke](https://github.com/ekristen/aws-nuke).
> We appreciate all the support and contributions we've received throughout the life of this project. We believe that the fork will continue to provide the functionality and support that you have come to expect from aws-nuke.
> Please note that this deprecation means we will not be addressing issues, accepting pull requests, or making future releases from this repository.
> Thank you for your understanding and support.
