### ISSUE TITLE
Getting TagOptionNotMigratedException: TagOption Migration not complete when running aws-nuke on a clean account

### ISSUE THREAD

**Issue by reegnz** [rebuy-de/aws-nuke#515]
I get messages like this when running aws-nuke an almost empty account (just some IAM stuff in there):

```
INFO[0010] TagOptionNotMigratedException: TagOption Migration not complete
	status code: 400, request id: 9e51d7ab-d139-49a4-9a32-a692151d71e6
```

Tried with both 2.14.0 and 2.15.0-beta.1, getting the same message for both.

**Comment by dxciberaws** [comment]
+1 
I excluded the ServiceCatalogTagOption and ServiceCatalogTagOptionPortfolioAttachment as workaround

**Comment by ekristen** [comment]
Please try v3 at https://github.com/ekristen/aws-nuke -- if this is still an issue, let me know over there. Thanks.

----

Please see the copy of the notice from the README about the deprecation of this project. Sven was kind enough to grant me access to help triage and close issues and pull requests that have already been addressed in the actively maintained fork. Some additional information is located in the [welcome issue](https://github.com/ekristen/aws-nuke/issues/276) for more information. 

> [!CAUTION]
> This repository for aws-nuke is no longer being actively maintained. We recommend users to switch to the actively maintained fork of this project at [ekristen/aws-nuke](https://github.com/ekristen/aws-nuke).
> We appreciate all the support and contributions we've received throughout the life of this project. We believe that the fork will continue to provide the functionality and support that you have come to expect from aws-nuke.
> Please note that this deprecation means we will not be addressing issues, accepting pull requests, or making future releases from this repository.
> Thank you for your understanding and support.
