### ISSUE TITLE
Disable production blacklist

### ISSUE THREAD

**Issue by rburchill** [rebuy-de/aws-nuke#520]
I might be missing something, but is there any way to disable the production blacklist check?

My use case is that I only have access to an AWS account that is non prod, prod is managed by another team. I'd like to be able to delete everything in my non prod account regularly.

I guess I could create a dummy AWS account with prod in the alias but this seems needlessly unnecessary. Is it possible to add a CLI flag with scary warnings that disables the blacklist feature completely?

**Comment by der-eismann** [comment]
Hey, sorry for the late response. The blacklist is just a security feature to make sure you don't actually delete your production account.
In your case you don't need to create another account for the blacklist, just enter any account ID (or `"000000000000"`) to bypass the check, there is no need for an additional flag.

**Comment by rburchill** [comment]
@der-eismann Sorry to re-open but this doesn't work for me:

```
aws-nuke -c aws-nuke.yml
aws-nuke version v2.15.0.beta.1 - Mon May 25 14:41:35 UTC 2020 - b61e6d59c66d85eeb7478e98d8d0b54094cbb9c2

Error: The specified account doesn't have an alias. For safety reasons you need to specify an account alias. Your production account should contain the term 'prod'.
```

My config looks like (with my account id redacted):

```
regions:
- eu-west-1
- global

account-blacklist:
- "000000000000"

accounts:
  "XXXXXXXXXX": {}
```

**Comment by der-eismann** [comment]
That error refers to your account, not the blacklist. Have you set an [alias](https://docs.aws.amazon.com/IAM/latest/UserGuide/console_account-alias.html) for your account?

**Comment by Vishal2696** [comment]
@der-eismann Is there a way to bypass this alias check also? Since I'm an IAM user in my organisation account who wants to keep the cost in check, Only root user will be able to set alias for the accounts.
