### ISSUE TITLE
Unable to run the docker image

### ISSUE THREAD

**Issue by vedmisra94** [rebuy-de/aws-nuke#537]
When i try to directly run the docker image - 
``` docker run \
    --rm -it \
    -v /full-path/to/nuke-config.yml:/home/aws-nuke/config.yml \
    -v /home/user/.aws:/home/aws-nuke/.aws \
    quay.io/rebuy/aws-nuke:v2.11.0 \
    --profile default \
    --config /home/aws-nuke/config.yml 
```

It says - 
```ERRO[0003] Failed to parse config file.                 
Error: read /home/aws-nuke/config.yml: is a directory
```

**Comment by der-eismann** [comment]
Did you actually replace `/full-path/to/nuke-config.yml` with the path of your config or did you just try to execute our example?

**Comment by vedmisra94** [comment]
@der-eismann  I replaced `/full-path/to/nuke-config.yml` with my path for config

**Comment by joe-niland** [comment]
@vedmisra94 try this:

```
docker run \
    --rm -it \
    -v $(pwd):/home/aws-nuke/ \
    quay.io/rebuy/aws-nuke:v2.11.0 \
	--access-key-id $AWS_ACCESS_KEY_ID \
	--secret-access-key $AWS_SECRET_ACCESS_KEY \
	--session-token $AWS_SESSION_TOKEN \
    --config /home/aws-nuke/nuke-config.yml
```

**Comment by der-eismann** [comment]
Were you able to get it running @vedmisra94? If not, please post the actual command you are executing.

**Comment by der-eismann** [comment]
I will close this since there hasn't been any reaction in the past months. If you still have problems feel free to reopen!
