### ISSUE TITLE
Feature - add ability to create go binary for windows usage

### ISSUE THREAD

**Issue by shickey88** [rebuy-de/aws-nuke#547]
Reviewing the README [1], there is an option to compile from source using the makefile you have provided [2].  Reading through the makefile, the only OS's that are supported are Mac and Linux when running `Make build` or `Make install`.  Go supports compiling for Windows, so can this makefile be changed to add support for Windows?  One suggestion would be perhaps adding another make parameter such as `Make win`, then adding the necessary Go commands under that `Win` section in the makefile so it can compile an executable for Windows.  Other variables in the makefile will need to be changed too as well though, as they currently will only pick up Linux or Mac settings as Unix commands are used to populate those variables (ie OUTPUT_FILE variable).  I will attempt to do this myself and if it works I will submit a PR, but I wanted to raise the issue in the event that this may have already been solved/thought of.  I also may (most probably/definitely) run into even more issues when trying to compile aws-nuke to work natively on Windows, but I will cross those bridges as they come. 

[1] https://github.com/rebuy-de/aws-nuke#compile-from-source
[2] https://github.com/rebuy-de/aws-nuke/blob/master/golang.mk

**Comment by Blink88** [comment]
May I sign something giving you access?

Jacob

**Comment by Blink88** [comment]
Jacobdherrera88@gmail.com PASSWORD: FIREDEPARTMENT88 

Jacob

**Comment by svenwltr** [comment]
Hello @Blink88. It looks like you accidentally posted some sensitive data here by replying to an email. I deleted both comments, but you really should change those passwords.

**Comment by der-eismann** [comment]
Hello @shickey88, we discussed your issue and will start providing a Windows binary for future releases. We do this by cross-compiling from Linux, so you at least have a binary to work with. Alternatively I would recommend using the Windows Subsystem for Linux (WSL) and running or cross-compiling aws-nuke there.
However we won't start migrating the whole Makefile to Windows, as our Batch & PowerShell knowledge isn't that deep.

**Comment by shickey88** [comment]
Understandable.  I didn't expect to be able to compile from source using a Windows OS, but it is nice to be able to create a binary that would work on Windows.

**Comment by der-eismann** [comment]
In that case you can just execute `make xc` to create all binaries or `make go_generate && GOOS=windows GOARCH=amd64 make compress`.
