### ISSUE TITLE
Support the feature flag "disable-deletion-protection" for ELBv2

### ISSUE THREAD

**Issue by jdyke** [rebuy-de/aws-nuke#554]
ELBv2 resources can have deletion protection but are not supported by `aws-nuke`. From what I can see `aws-nuke` only currently supports 2 resource types:

```
field ELBv2 not found in type struct { RDSInstance bool "yaml:\"RDSInstance\""; EC2Instance bool "yaml:\"EC2Instance\"" }
```

**Comment by ekristen** [comment]
This has been implemented at https://github.com/ekristen/aws-nuke


----

Please see the copy of the notice from the README about the deprecation of this project. Sven was kind enough to grant me access to help triage and close issues and pull requests that have already been addressed in the actively maintained fork. Some additional information is located in the [welcome issue](https://github.com/ekristen/aws-nuke/issues/276) for more information. 

> [!CAUTION]
> This repository for aws-nuke is no longer being actively maintained. We recommend users to switch to the actively maintained fork of this project at [ekristen/aws-nuke](https://github.com/ekristen/aws-nuke).
> We appreciate all the support and contributions we've received throughout the life of this project. We believe that the fork will continue to provide the functionality and support that you have come to expect from aws-nuke.
> Please note that this deprecation means we will not be addressing issues, accepting pull requests, or making future releases from this repository.
> Thank you for your understanding and support.
