### ISSUE TITLE
S3Objects are deleted very slow

### ISSUE THREAD

**Issue by danielrankov-mm** [rebuy-de/aws-nuke#565]
aws-nuke -t S3Bucket seems to be deleting the objects very slowly.
I first thought that it was because of the network latency across regions, but then I started an EC2 instance (t2) in the same region.
I've enabled the S3 Metrics and compared aws-nuke with `aws s3 rb s3://bucket-name --force`
aws-nuke - S3 DELETE avg = 60 req/s
aws s3 rb - S3 DELETE avg = 12000 req/s
Here is the CW metric:
<img width="910" alt="Screenshot 2020-10-09 at 0 19 42" src="https://user-images.githubusercontent.com/61969390/95514752-23471380-09c5-11eb-82c2-30dde55df09d.png">

**Comment by ekristen** [comment]
I'd be happy to look into this again over at my fork https://github.com/ekristen/aws-nuke, it's a difficult problem to test at scale.

----

Please see the copy of the notice from the README about the deprecation of this project. Sven was kind enough to grant me access to help triage and close issues and pull requests that have already been addressed in the actively maintained fork. Some additional information is located in the [welcome issue](https://github.com/ekristen/aws-nuke/issues/276) for more information. 

> [!CAUTION]
> This repository for aws-nuke is no longer being actively maintained. We recommend users to switch to the actively maintained fork of this project at [ekristen/aws-nuke](https://github.com/ekristen/aws-nuke).
> We appreciate all the support and contributions we've received throughout the life of this project. We believe that the fork will continue to provide the functionality and support that you have come to expect from aws-nuke.
> Please note that this deprecation means we will not be addressing issues, accepting pull requests, or making future releases from this repository.
> Thank you for your understanding and support.
