### ISSUE TITLE
MSK Cluster config is not deleted

### ISSUE THREAD

**Issue by abhinav3295** [rebuy-de/aws-nuke#567]
I used the sample config provided in the example.
And it deleted all of my infra except the `MSK Cluster Config`
(arn:aws:kafka:us-east-1:xxxxx:configuration/config)

It neither gets discovered during the plan phase nor it gets deleted during apply phase.

**Comment by spr-mweber3** [comment]
Hey there, I second that. We experienced the same problem recently. As this issue is already open for some time now I want to ask if that is something that is considered to be fixed soon? If not I'd be happy to contribute by implementing that functionality.

**Comment by steveteuber** [comment]
@abhinav3295 I think that this issue can be closed.
