### ISSUE TITLE
Fails to delete EKS cluster because it does not try to delete the EKS nodegroup first

### ISSUE THREAD

**Issue by ecerulm** [rebuy-de/aws-nuke#573]
`aws-nuke` fails to delete the eks cluster, It seems that it does not even attempt to delete the EKS nodegroup (which i think it's a prerequisite to be able to delete the EKS cluster)

```
Removal requested: 0 waiting, 13 failed, 78 skipped, 86 finished
eu-north-1 - EC2SecurityGroup - sg-059bcffdfe04ee34f - ERRO[0331] DependencyViolation: resource sg-059bcffdfe04ee34f has a dependent object
	status code: 400, request id: 61bd8dc7-2b92-484e-ab64-9ccde72e01fd
[Name: "clustername-441991687"] - failed
ERRO[0331] DependencyViolation: resource sg-06c760a39a7f09f95 has a dependent object
	status code: 400, request id: 6e08d6c1-1092-4636-a311-71b800730895
eu-north-1 - EC2SecurityGroup - sg-06c760a39a7f09f95 - [Name: "bia-b2b-eks-dev20201103131536709900000004"] - failed
ERRO[0331] ResourceInUseException: Cluster has nodegroups attached
	status code: 409, request id: 114ce106-ab03-439f-bf3c-74a26607e4ea
eu-north-1 - EKSCluster - clustername - failed
```

If I delete the nodegroup manually from the AWS console and retry with `aws-nuke` then it succeeds in deleting the eks cluster.

**Comment by spkane** [comment]
It is indeed a requirement that any attached nodegroups must be deleted before the EKS cluster is deleted. With the AWS CLI you need to do something like this to achieve the same results.

```
aws eks list-nodegroups --cluster-name app-opal-weapon
aws eks delete-nodegroup --cluster-name app-opal-weapon --nodegroup-name app-opal-weapon-default-winning-chipmunk
aws eks delete-cluster --name app-opal-weapon
```

Just trying to delete the cluster without deleting the nodegroups first will result in an error.

**Comment by akshitkh** [comment]
#605 can fix this.

**Comment by ekristen** [comment]
The way the tool works is that it will try and delete everything even if it's out of order, so it should delete the node group eventually and then the cluster will work, now if everything fails 3 times then it'll fail.

Please test v3 at https://github.com/ekristen/aws-nuke if this is still an issue, open an issue there.

----

Please see the copy of the notice from the README about the deprecation of this project. Sven was kind enough to grant me access to help triage and close issues and pull requests that have already been addressed in the actively maintained fork. Some additional information is located in the [welcome issue](https://github.com/ekristen/aws-nuke/issues/276) for more information. 

> [!CAUTION]
> This repository for aws-nuke is no longer being actively maintained. We recommend users to switch to the actively maintained fork of this project at [ekristen/aws-nuke](https://github.com/ekristen/aws-nuke).
> We appreciate all the support and contributions we've received throughout the life of this project. We believe that the fork will continue to provide the functionality and support that you have come to expect from aws-nuke.
> Please note that this deprecation means we will not be addressing issues, accepting pull requests, or making future releases from this repository.
> Thank you for your understanding and support.
