### ISSUE TITLE
Write statistics upon completion

### ISSUE THREAD

**Issue by borgstrom** [rebuy-de/aws-nuke#582]
Hi 👋 

We provide a sandbox environment for our engineers to experiment and run `aws-nuke` in a scheduled task to cleanup the environment. We would love to have structured output (i.e. JSON, etc) of some statistics so that we can emit them as statsd metrics and in our messaging bus.

Is that something that is easily possible?

Thanks!

**Comment by ekristen** [comment]
@borgstrom what sort of statistics would you want?

**Comment by ekristen** [comment]
tracking via https://github.com/ekristen/aws-nuke/issues/326

----

Please see the copy of the notice from the README about the deprecation of this project. Sven was kind enough to grant me access to help triage and close issues and pull requests that have already been addressed in the actively maintained fork. Some additional information is located in the [welcome issue](https://github.com/ekristen/aws-nuke/issues/276) for more information. 

> [!CAUTION]
> This repository for aws-nuke is no longer being actively maintained. We recommend users to switch to the actively maintained fork of this project at [ekristen/aws-nuke](https://github.com/ekristen/aws-nuke).
> We appreciate all the support and contributions we've received throughout the life of this project. We believe that the fork will continue to provide the functionality and support that you have come to expect from aws-nuke.
> Please note that this deprecation means we will not be addressing issues, accepting pull requests, or making future releases from this repository.
> Thank you for your understanding and support.
