### ISSUE TITLE
Route53 Resolver endpoints error 

### ISSUE THREAD

**Issue by jad0083** [rebuy-de/aws-nuke#586]
Good day, as I was testing the newest compiled build of aws-nuke - was able to test on a couple of accounts that were using route53 resolvers configured with outbound/inbound rules to external DNS.  Nuking r53 resolvers will fail if there are resolver rules configured.  aws-nuke seem to not detect resolver rules, hence failing to nuke resolver endpoints.  Not sure why this is the case, as I see resolver rules as valid nukeable resources.

**Comment by der-eismann** [comment]
Could you post the logs of the failing nuke attempt?

**Comment by kazimierzbudzyk** [comment]
@der-eismann hit the same issue, please see the loglines:
```
ERRO[0073] There are resources in failed state, but none are ready for deletion, anymore.

us-east-1 - Route53ResolverEndpoint - rslvr-out-REDACTED (placeholder_Route53_endpoint) - [EndpointID: "rslvr-out-REDACTED", Name: "placeholder_Route53_endpoint"] - failed
ERRO[0073] InvalidRequestException: [RSLVR-00600] Cannot delete resolver endpoint unless its related resolver rules are deleted. The following rules still exist for this resolver endpoint: "rslvr-rr-REDACTED"
```

**Comment by ekristen** [comment]
Please try the fork https://github.com/ekristen/aws-nuke -- if you still have this issue open an issue over there.

----

Please see the copy of the notice from the README about the deprecation of this project. Sven was kind enough to grant me access to help triage and close issues and pull requests that have already been addressed in the actively maintained fork. Some additional information is located in the [welcome issue](https://github.com/ekristen/aws-nuke/issues/276) for more information. 

> [!CAUTION]
> This repository for aws-nuke is no longer being actively maintained. We recommend users to switch to the actively maintained fork of this project at [ekristen/aws-nuke](https://github.com/ekristen/aws-nuke).
> We appreciate all the support and contributions we've received throughout the life of this project. We believe that the fork will continue to provide the functionality and support that you have come to expect from aws-nuke.
> Please note that this deprecation means we will not be addressing issues, accepting pull requests, or making future releases from this repository.
> Thank you for your understanding and support.
