### ISSUE TITLE
AWS Backup Managed Vaults, Backup Plans and Backup Selection can not be deleted

### ISSUE THREAD

**Issue by adamcousins** [rebuy-de/aws-nuke#599]
When enabling EFS automatic updates (and probably other services too), these resources are created but can not be deleted.

```
ap-southeast-2 - AWSBackupVault - arn:aws:backup:ap-southeast-2:*redacted*:backup-vault:aws/efs/automatic-backup-vault - [Name: "aws/efs/automatic-backup-vault"] - failed
--
ap-southeast-2 - AWSBackupPlan - arn:aws:backup:ap-southeast-2:*redacted:backup-plan:aws/efs/*redacted - [ID: "aws/efs/v", Name: "aws/efs/automatic-backup-plan"] - failed

ap-southeast-2 - AWSBackupSelection - aws/efs/*redacted* (aws/efs/*redacted*) - [ID: "aws/efs/*redacted*", Name: "aws/efs/automatic-backup-selection", PlanID: "aws/efs/*redacted*"] - failed
```

**Comment by deekayw0n** [comment]
Hi Adam - I too ran into this problem on a shared account and couple other data points on my end:

1. The inability to delete these backup resources actually causes aws-nuke to error out entirely (not complete) for me thus potentially not deleting other resources later in the queue
2. It seems filtering does not work for these resources, regardless of exact, contains, regex, or glob--I needed to use resource-types->excludes for AWSBackupVault, AWSBackupPlan, and AWSBackupSelection to not have the aws-nuke crash

One side note: I cannot destroy these resources even manually under the role I ran aws-nuke, so the issue may be that an Administrator set this up, will try aws-nuke on these resources with root and report back.

2nd side note [to the author and contributors]: this is a wonderful piece of software and helped me tackle 4 yrs of neglect on a large, org-wide shared sandbox account.  I'll file some additional reports in case its helpful--if I can I'll explore PRs eventually too.

**Comment by nelsonjchen** [comment]
I can't delete these manually under the console even as root. 

I think these vault and plan resources are also specially protected somehow as well: 

https://aws.amazon.com/premiumsupport/knowledge-center/efs-disable-automatic-backups/#Delete_the_recovery_point:~:text=Note%3A%20You%20can't%20delete%20the%20default%20backup%20plan%20or%20the%20backup%20vault%20automatic%2Dbackup%2Dvault.

It would be nice to know what other resources underneath AWS backup are affected. I just made an EFS resource in a sandbox account and these AWS Backup resources implicitly created themselves.

**Comment by nelsonjchen** [comment]
As a sidenote, that link I posted earlier mentions that deleting the vault is not possible, so you'll have to go into the vault and delete the recovery points yourself.

**Comment by nelsonjchen** [comment]
On that note, I just visited another fresh account which has never used AWS Backup. I noticed a "Default" vault created right at the time I first visited that part of the AWS Console.

Looking at the code, I can't see any special handling for a "Default" vault. 

Uh oh and damn, did I just medusa that account to AWS Nuke?! 

Ugh, these are (now were?) DCE accounts too.

**Comment by nelsonjchen** [comment]
The default vault (not the EFS vault prompted in this issue) can't be deleted too according to this link:

https://docs.aws.amazon.com/aws-backup/latest/devguide/gs-cleanup-resources.html#cleanup-vaults:~:text=You%20can't%20delete%20the%20default%20backup,the%20backup%20vault%20and%20choose%20Delete.

For these specially handled vaults such as `Default`, `aws/efs/automatic-backup-vault`, and probably more, I think aws-nuke would have to take off the default `Deny` policy on the vaults and delete all the restore points in them manually.

**Comment by nelsonjchen** [comment]
The `Default` vault can be "deleted". When this happens, the ARN of "Default" disappears from the vault list.

**Comment by nelsonjchen** [comment]
I've made #643 which will handle this.
