### ISSUE TITLE
Apple Silicon (arm64) not supported supported

### ISSUE THREAD

**Issue by tulik** [rebuy-de/aws-nuke#610]
**Ask for a feature:**
Apple is transitioning to its own chips. It's nice to have macOS+aarch64/arm64 release too.

**Why**
Current and future macOS users will benefit from it a lot.

**Comment by der-eismann** [comment]
You can download a binary for Apple Silicon on the release page
https://github.com/rebuy-de/aws-nuke/releases/tag/v2.15.0-rc.4
