### ISSUE TITLE
Typo in Example code

### ISSUE THREAD

**Issue by mariadb-GeorgiHarizanov** [rebuy-de/aws-nuke#611]
There is a Typo in example code. Lost couple of hours until noticing that **"account-blocklist"** should be **"account-bl**A**cklist"** .

**Comment by der-eismann** [comment]
No, this was introduced in https://github.com/rebuy-de/aws-nuke/pull/595 and is intended. You should always use the readme that matches the version you are using, so either check [this readme](https://github.com/rebuy-de/aws-nuke/blob/v2.14.0/README.md) for the last stable release or use the [latest release](https://github.com/rebuy-de/aws-nuke/releases/tag/v2.15.0-rc.4).

**Comment by mariadb-GeorgiHarizanov** [comment]
This is so confusing! Why would this even differ between versions...

**Comment by der-eismann** [comment]
Because we started with the blacklist and a master branch, but we wanted to adapt a [new terminology](https://tools.ietf.org/id/draft-knodel-terminology-00.html#rfc.section.1.2). At some point you gotta do breaking changes.
