### ISSUE TITLE
Simple AD Directory Service and Amazon Workdocs Site cannot be deleted if associated, resulting in error

### ISSUE THREAD

**Issue by deekayw0n** [rebuy-de/aws-nuke#623]
If I create a new Amazon Workdocs Site in the AWS Console w/ either the default Quick Start options or selects "Create Simple AD" in the standard setup when setting up a Directory in step 1, neither the Workdocs Site or the Amazon Directory Service associated with it can be deleted by aws-nuke. This will also prevent deletion of associated network resources:
```
us-west-2 - DirectoryServiceDirectory - d-92670cb648 - failed
ERRO[0055] ClientException: Cannot delete the directory because it still has authorized applications. : RequestId: 4b123c13-9771-43f4-90e5-1ce6224e51a3
{
  RespMetadata: {
    StatusCode: 400,
    RequestID: "4b123c13-9771-43f4-90e5-1ce6224e51a3"
  },
  Message_: "Cannot delete the directory because it still has authorized applications. : RequestId: 4b123c13-9771-43f4-90e5-1ce6224e51a3",
  RequestId: "4b123c13-9771-43f4-90e5-1ce6224e51a3"
} 
```

if I now delete the workdocs site associated to this Directory Service in the AWS Console, aws-nuke deletion of the Simple AD Directory Service and associated network resources work as expected:
```
us-west-2 - DirectoryServiceDirectory - d-92670cb648 - removed
```

Sidenote: couldn't track down how to create or delete a Workdocs site via API/CLI which may make programatic deletion challenging. Also, I don't think aws-nuke reports any details about the Workdocs site entity in its logs, which could explain why it expects to be able to delete the DirectoryServiceDirectory entity as it does not know of this site depending on it. Might there be another way to gauge the existence of a Workdocs site?

**Comment by ekristen** [comment]
This might be fixed and addressed in teh fork already, there has been some additional work done around workdocs. Please check out the fork and if this is still an issue, open a new issue there. Thank you.

----

Please see the copy of the notice from the README about the deprecation of this project. Sven was kind enough to grant me access to help triage and close issues and pull requests that have already been addressed in the actively maintained fork. Some additional information is located in the [welcome issue](https://github.com/ekristen/aws-nuke/issues/276) for more information. 

> [!CAUTION]
> This repository for aws-nuke is no longer being actively maintained. We recommend users to switch to the actively maintained fork of this project at [ekristen/aws-nuke](https://github.com/ekristen/aws-nuke).
> We appreciate all the support and contributions we've received throughout the life of this project. We believe that the fork will continue to provide the functionality and support that you have come to expect from aws-nuke.
> Please note that this deprecation means we will not be addressing issues, accepting pull requests, or making future releases from this repository.
> Thank you for your understanding and support.
