### ISSUE TITLE
Amazon QuickSite created resources are not seen/reported/deleted

### ISSUE THREAD

**Issue by deekayw0n** [rebuy-de/aws-nuke#626]
Because Amazon QuickSite (https://aws.amazon.com/quicksight/) resources are not examined by aws-nuke, the tool cannot delete any associated resources created as a result of this service's use [such as network interface, subnet, routing table, and vpc]. 

After several attempts it will typically error out.

On the bright side, it looks like AWS published a variety of describe/delete APIs for this service so it might not be too difficult to understand the dependency graph to delete resources.

**Comment by ekristen** [comment]
tracking via https://github.com/ekristen/aws-nuke/issues/346

----

Please see the copy of the notice from the README about the deprecation of this project. Sven was kind enough to grant me access to help triage and close issues and pull requests that have already been addressed in the actively maintained fork. Some additional information is located in the [welcome issue](https://github.com/ekristen/aws-nuke/issues/276) for more information. 

> [!CAUTION]
> This repository for aws-nuke is no longer being actively maintained. We recommend users to switch to the actively maintained fork of this project at [ekristen/aws-nuke](https://github.com/ekristen/aws-nuke).
> We appreciate all the support and contributions we've received throughout the life of this project. We believe that the fork will continue to provide the functionality and support that you have come to expect from aws-nuke.
> Please note that this deprecation means we will not be addressing issues, accepting pull requests, or making future releases from this repository.
> Thank you for your understanding and support.
