### ISSUE TITLE
CloudFormation fails to delete because role was already deleted

### ISSUE THREAD

**Issue by nimrodkor** [rebuy-de/aws-nuke#629]
We are using CloudFormation templates with custom resources, and they are backed by lambdas.
To delete these CF templates, one needs to keep the lambdas and roles in place.

The issue is this is not the order in which aws-nuke is deleting stuff.

Would you be open to contributions in this area?

**Comment by LRuttenCN** [comment]
I think the easiest way to implement this is to add `Service: cloudformation.amazonaws.com` to the assume role policy of the role provided for running aws-nuke. Then you can specify a `--role-name` parameter when deleting stacks. Then you are independent of the order of deletion.

**Comment by LRuttenCN** [comment]
Current solution for me is create 2 config files and run nuke twice. First time only delete CFN stacks, second time everything...

**Comment by ekristen** [comment]
Tracking DAG deletion as a feature at https://github.com/ekristen/aws-nuke/issues/298

Please feel free to comment over there as to the frequency in which you run into this issue.


----

Please see the copy of the notice from the README about the deprecation of this project. Sven was kind enough to grant me access to help triage and close issues and pull requests that have already been addressed in the actively maintained fork. Some additional information is located in the [welcome issue](https://github.com/ekristen/aws-nuke/issues/276) for more information. 

> [!CAUTION]
> This repository for aws-nuke is no longer being actively maintained. We recommend users to switch to the actively maintained fork of this project at [ekristen/aws-nuke](https://github.com/ekristen/aws-nuke).
> We appreciate all the support and contributions we've received throughout the life of this project. We believe that the fork will continue to provide the functionality and support that you have come to expect from aws-nuke.
> Please note that this deprecation means we will not be addressing issues, accepting pull requests, or making future releases from this repository.
> Thank you for your understanding and support.
