### ISSUE TITLE
DNS Error

### ISSUE THREAD

**Issue by sabrehagen** [rebuy-de/aws-nuke#63]
[This is a run](https://gist.github.com/sabrehagen/d01fb2f2e05e99ad968839d0fdebf42c) with errors and private data redacted.

The DNS lookups fail at consistent intervals. I've included the full log with the errors inline such that you might be able to correlate the timing of the error with a certain part of the resource deletion sequence.

`aws-nuke` `v.1.3.0`

**Comment by svenwltr** [comment]
Hello @sabrehagen,

apparently there is [no EFS](http://docs.aws.amazon.com/general/latest/gr/rande.html#elasticfilesystem-region) in `eu-west-1`. I don't know why the AWS SDK is giving such a confusing error message. We should try to handle that error better.

**Comment by tomvachon** [comment]
This is a larger problem, It's coming up in #112 as well

**Comment by svenwltr** [comment]
This is fixed in #124 and will be part of the next release.
