### ISSUE TITLE
Feature request: Include AutoScalingGroup for more granular filter tagging

### ISSUE THREAD

**Issue by stoimendhristov** [rebuy-de/aws-nuke#630]
I can verify that right now the AutoScalingGroup resource filtering is not granular enough by simply running the aws-nuke in a dry run mode. I get an output similar to the following one:
```
[1mus-east-1[0m - [mAutoScalingGroup[0m - [1mmy-asg[0m - [34mwould remove
```

I can also check (in `v2.15.0` tag) that the following resources support tag matching:
```
~/Code/aws-nuke (b5ccc00 ✔) ᐅ ack -l 'properties.SetTag' ./resources | xargs ack --no-filename 'register\("([^"]+)",' --output='$1' | sed '/^[[:space:]]*$/d' | sort
ACMCertificate
ACMPCACertificateAuthority
ACMPCACertificateAuthorityState
APIGatewayRestAPI
APIGatewayV2API
APIGatewayV2VpcLink
APIGatewayVpcLink
AppSyncGraphqlAPI
CloudFormationStack
CodeStarNotificationRule
DynamoDBTable
EC2Address
EC2ClientVpnEndpoint
EC2DHCPOption
EC2EgressOnlyInternetGateway
EC2Image
EC2Instance
EC2InternetGateway
EC2InternetGatewayAttachment
EC2NATGateway
EC2NetworkACL
EC2NetworkInterface
EC2RouteTable
EC2SecurityGroup
EC2Subnet
EC2TGW
EC2TGWAttachment
EC2VPC
EC2VPCEndpoint
EC2VPNConnection
EC2VPNGatewayAttachment
EC2Volume
ELB
ELBv2
ELBv2TargetGroup
FSxBackup
FSxFileSystem
IAMRole
IAMRolePolicy
KMSKey
LambdaFunction
LightsailInstance
RDSDBCluster
RDSDBClusterParameterGroup
RDSDBParameterGroup
RDSDBSubnetGroup
RDSEventSubscription
RDSInstance
RDSSnapshot
S3Bucket
SNSTopic
SSMParameter
SecretsManagerSecret
TransferServer
TransferServerUser
```

An example of the EC2Instance resource when matched for a removal is:
```
[0m[1mus-east-1[0m - [mEC2Instance[0m - [1mi-0335f2421d882cd32[0m - [3m[tag:Name: "my-ec2"][0m - [34mwould remove
```

Has it been planned to include ASG resources for tag filtering as removing EC2 instances is fine but when keeping the ASG up and running new EC2s are spun up?

Thanks for your reply.

**Comment by ekristen** [comment]
Adding tags to various resources is in the backlog.

----

Please see the copy of the notice from the README about the deprecation of this project. Sven was kind enough to grant me access to help triage and close issues and pull requests that have already been addressed in the actively maintained fork. Some additional information is located in the [welcome issue](https://github.com/ekristen/aws-nuke/issues/276) for more information. 

> [!CAUTION]
> This repository for aws-nuke is no longer being actively maintained. We recommend users to switch to the actively maintained fork of this project at [ekristen/aws-nuke](https://github.com/ekristen/aws-nuke).
> We appreciate all the support and contributions we've received throughout the life of this project. We believe that the fork will continue to provide the functionality and support that you have come to expect from aws-nuke.
> Please note that this deprecation means we will not be addressing issues, accepting pull requests, or making future releases from this repository.
> Thank you for your understanding and support.
