### ISSUE TITLE
docker hangs - doesnt complete/return to unix prompt && ignores --no-dry-run

### ISSUE THREAD

**Issue by ajb1967** [rebuy-de/aws-nuke#631]
hi am running following 

*nuke.sh*

```bash
docker run \
    --rm -it \
    -a stdin -a stdout \
    -v /Users/ajb1967/aws-nuke/config/nuke-config.yml:/home/aws-nuke/config.yml \
    -v /Users/ajb1967/.aws:/home/aws-nuke/.aws \
    quay.io/rebuy/aws-nuke:v2.13.0 \
    --no-dry-run \
    --profile cards-demo \
    --config /home/aws-nuke/config.yml
```

![Screenshot 2021-04-21 at 18 03 53](https://user-images.githubusercontent.com/34161302/115593261-35870000-a2cc-11eb-9d5e-3499b0d0cec3.png)

However, 

a) command doesn't return to unix prompt (just seems to hang)
b) command seems to ignore the --no-dry-run switch

![Screenshot 2021-04-21 at 17 59 57](https://user-images.githubusercontent.com/34161302/115592860-b1347d00-a2cb-11eb-9016-e2f675377b28.png)

I have tried version 2.15.0 also

Thanks,
Andy

**Comment by ajb1967** [comment]
more information - if i continue to wait at the 'apparent' hang, then we get the following error

```bash
ERRO[0135] Listing GlobalAcceleratorEndpointGroup failed:
    RequestError: send request failed
    caused by: Post "https://globalaccelerator.us-east-1.amazonaws.com/": dial tcp 92.242.132.24:443: i/o timeout
ERRO[0137] Listing GlobalAccelerator failed:
    RequestError: send request failed
    caused by: Post "https://globalaccelerator.us-east-1.amazonaws.com/": dial tcp 92.242.132.24:443: i/o timeout
ERRO[0138] Listing GlobalAcceleratorListener failed:
    RequestError: send request failed
    caused by: Post "https://globalaccelerator.us-east-1.amazonaws.com/": dial tcp 92.242.132.24:443: i/o timeout
```

**Comment by ekristen** [comment]
This looks to be an issue with local network. Please try the fork at https://github.com/ekristen/aws-nuke, if the problem still persists, open an issue there. Thanks.

----

Please see the copy of the notice from the README about the deprecation of this project. Sven was kind enough to grant me access to help triage and close issues and pull requests that have already been addressed in the actively maintained fork. Some additional information is located in the [welcome issue](https://github.com/ekristen/aws-nuke/issues/276) for more information. 

> [!CAUTION]
> This repository for aws-nuke is no longer being actively maintained. We recommend users to switch to the actively maintained fork of this project at [ekristen/aws-nuke](https://github.com/ekristen/aws-nuke).
> We appreciate all the support and contributions we've received throughout the life of this project. We believe that the fork will continue to provide the functionality and support that you have come to expect from aws-nuke.
> Please note that this deprecation means we will not be addressing issues, accepting pull requests, or making future releases from this repository.
> Thank you for your understanding and support.
