### ISSUE TITLE
Improve README with fork / PR instructions

### ISSUE THREAD

**Issue by faermanj** [rebuy-de/aws-nuke#634]
Hello,

My attempt to fork and build faild, probably a newbie mistake due to go vendoring:

```
go: inconsistent vendoring in /Users/julio/Dev/aws-nuke:
	golang.org/x/lint@v0.0.0-20201208152925-83fdc39ff7b5: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	golang.org/x/tools@v0.1.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt

	To ignore the vendor directory, use -mod=readonly or -mod=mod.
	To sync the vendor directory, run:
		go mod vendor
make: *** [go_generate] Error 1

```
The suggested commands did not resolve.
I could build fine from main.
If you let me know how to set up a fork i would gladly contribute it to the README, and hopefully more :)

Cheers

**Comment by Imunhatep** [comment]
Same issue here.

Though docker image is building, but the way it does... 
```
ENV GOPATH=/go PATH=/go/bin:$PATH CGO_ENABLED=0 GO111MODULE=on
RUN mkdir -p ${GOPATH}/src ${GOPATH}/bin

WORKDIR /src

COPY go.mod .
COPY go.sum .
RUN go mod download

COPY . .

RUN set -x \
 && make build \
 ...
```

Doing locally only `go mod download` and `make build` leads to the same error.

Why that magic with `gopath` and application sources? 
What is wrong with `go build`?

**Comment by ekristen** [comment]
That command should definitely work if you are using go modules in your golang setup. I just forked and made changes without issue. Are you still experience issues with the latest code base @faermanj?
