### ISSUE TITLE
dateOlderThan for EC2 instances and other resource

### ISSUE THREAD

**Issue by nmiculinic** [rebuy-de/aws-nuke#640]
Maybe I've misread the docs....though I want to kill all EC2 instances older than 2h for example. (among other resources).

Can I achieve this with this tool, or is it not in the feature set.

**Comment by rbroemeling** [comment]
@nmiculinic I was trying to do something very similar today and also couldn't figure out how to do it. After spelunking in the code, I found that for EC2 instances, the `launchTime` metadata is not populated into the properties for that resource -- which means that at the moment, there doesn't appear to be any easy way to nuke EC2 instances that are >= X hours old.

Ref: https://github.com/rebuy-de/aws-nuke/blob/b5ccc0056f070379678264ccae7c88ddf8b5dfa5/resources/ec2-instances.go#L109

This looks pretty useful and easy to add, so hopefully it'll be fixed relatively easily. If I have a few moments, I might open a PR to fix it myself.

**Comment by rbroemeling** [comment]
I implemented the necessary properties to underly this behaviour and have submitted them in rebuy-de/aws-nuke#670. After that PR has been merged, this will be possible with a filter statement like this:

```
      EC2Instance:
      - property: "LaunchTime"
        type: dateOlderThan
        value: "2h"
```
