### ISSUE TITLE
Flow Logs for Default VPC

### ISSUE THREAD

**Issue by rburchill** [rebuy-de/aws-nuke#651]
Hi,

I noticed today that flow logs for the default VPC in my AWS account aren't deleted by aws-nuke.

I searched issues and the google group and couldn't see this mentioned anywhere, apologies if I have missed something.

Is this something that could be covered by aws-nuke?

Thanks,

**Comment by ekristen** [comment]
@rburchill this is an order of operations problem, it's possible for the log groups to be deleted but the VPC still has traffic, AWS then re-creates the log groups but then deletes the VPC, but since aws-nuke already nuked the log groups, it doesn't go back and do it again.
