### ISSUE TITLE
S3 bucket cannot be deleted because BucketHasAccessPointsAttached error

### ISSUE THREAD

**Issue by fridim** [rebuy-de/aws-nuke#660]
If access points are defined for an S3 bucket, aws-nuke fails to delete the Bucket.

```
aws  s3 rb s3://mybucket --force
remove_bucket failed: s3://mybucket An error occurred (BucketHasAccessPointsAttached) when calling the DeleteBucket operation: Bucket has access points attached and cannot be deleted.
```

**suggestion fix**: use s3control https://docs.aws.amazon.com/sdk-for-go/api/service/s3control/ and remove all access points before deleting the Bucket.

**Comment by ekristen** [comment]
Looks like S3AccessPoints are now supported so this should no longer be an issue.
