### ISSUE TITLE
Unable to view any IAM related information for nuke when running aws nuke on dry run

### ISSUE THREAD

**Issue by jes05** [rebuy-de/aws-nuke#666]
Hi, 

I am trying to run aws nuke for testing, below is my config file - 
regions:
- eu-north-1
- ap-south-1
- eu-west-3
- eu-west-2
- eu-west-1
- ap-northeast-3
- ap-northeast-2
- ap-northeast-1
- sa-east-1
- ca-central-1
- ap-southeast-1
- ap-southeast-2
- eu-central-1
- us-east-1
- us-east-2
- us-west-1
- us-west-2
account-blacklist:
- '12346437291'
resource-types:
  targets:
  - IAMUsers
accounts:
  '2323982320': {}

When i run aws-nuke it doesn't display anythink, irrespective of if i target IAM Roles, Iam users or policy etc. but it works perfectly if i target EC2 instance or S3 bucket. I have about 4 users and  16 roles to delete

Please help. 

Output - 
Do you want to continue? Enter account alias to continue.
> awsnuketest

Scan complete: 0 total, 0 nukeable, 0 filtered.

**Comment by jonesmac** [comment]
Looks like you might be missing `global` from your regions list.  Once I added that, I could see the IAM resources in the output.

**Comment by ga-paul-t** [comment]
> Looks like you might be missing `global` from your regions list. Once I added that, I could see the IAM resources in the output.

I had the exact same question
