### ISSUE TITLE
Update readme with --force example

### ISSUE THREAD

**Issue by matkosoric** [rebuy-de/aws-nuke#668]
I had a problem with automating aws-nuke due to interactive providing of account alias.

Solution is already written on Stackoverflow, consisted in using --force flag:
[Question](https://stackoverflow.com/questions/58439484/how-to-run-aws-nuke-without-providing-inputs-during-execution)

Still, it would be nice to have it documented directly in readme.

**Comment by jamesgeddes** [comment]
This should be returned as part of `aws-nuke --help`. I'd suggest is it is put under the heading `**Danger Zone**`.

**Comment by shibumi** [comment]
Hi, is there a way to ignore the missing alias? I have two completely different payer accounts for prod and stage... I don't want to create an alias for my stage payer account that could create problems... I don't want to touch the infra at all. I just want to nuke the resources in the accounts.

**Comment by jamesgeddes** [comment]
@shibumi Would your question be better in a separate ticket?

**Comment by shibumi** [comment]
@jamesgeddes  yes, sorry for the noise. Feel free to mark the comments as irrelevant
