### ISSUE TITLE
After running AWS Nuke multiple times, it's still not removing any of my EC2 instances S3 buckets and CFn Stacks

### ISSUE THREAD

**Issue by amith1108** [rebuy-de/aws-nuke#674]
./aws-nuke-v2.15.0-linux-amd64 -c config.yml  --access-key-id xxxxxxxxxxxxxxxxxx --secret-access-key xxxxxxxxxxxl --no-dry-run

I'm using the above command to nuke my entire AWS account, but all i see is failed in front of the above services.

Below is my Config.yml file:

> `regions:
- global
- us-east-1
- us-east-2
- us-west-1
- ap-south-1
- ap-southeast-1
- ap-southeast-2

account-blocklist:
- "999999999999" # production

accounts:
  "665977444369": # aws-nuke-example
    filters:
      IAMUser:
      - "aws-nuke"
      IAMUserPolicyAttachment:
      - "aws-nuke -> AdministratorAccess"
      IAMUserAccessKey:
      - "aws-nuke -> xxxxxxxx"`

What am i missing here?

After running the nuke i can still all the resources intact, The first time i ran this tool it deleted a couple of Users

Some of my Ec2 instances in us-east-1 got deleted after i specified the regions explicitly at the top.

But even after mentioning ap-south-1 I can still see Ec2 instances running there.

**Comment by jrdufresne** [comment]
can you provide the output after running the command?

**Comment by gtasonis** [comment]
This is a known issue with regard to EC2 and VPC's and they'll need to be cleaned up manually/scripting AFAIK. Dependencies aren't always deleted in the right order.

**Comment by svenwltr** [comment]
This issue is not known to us, but we cannot tell more without having any output.

**Comment by neolace** [comment]
I have run into the same issue, I think it's because of auto-scaling that's set up.

**Comment by ekristen** [comment]
Please try v3 at https://github.com/ekristen/aws-nuke -- if this is still an issue, let me know over there. Thanks.

----

Please see the copy of the notice from the README about the deprecation of this project. Sven was kind enough to grant me access to help triage and close issues and pull requests that have already been addressed in the actively maintained fork. Some additional information is located in the [welcome issue](https://github.com/ekristen/aws-nuke/issues/276) for more information. 

> [!CAUTION]
> This repository for aws-nuke is no longer being actively maintained. We recommend users to switch to the actively maintained fork of this project at [ekristen/aws-nuke](https://github.com/ekristen/aws-nuke).
> We appreciate all the support and contributions we've received throughout the life of this project. We believe that the fork will continue to provide the functionality and support that you have come to expect from aws-nuke.
> Please note that this deprecation means we will not be addressing issues, accepting pull requests, or making future releases from this repository.
> Thank you for your understanding and support.
