### ISSUE TITLE
Failures on resources shared with Resource Access Manager (RAM)

### ISSUE THREAD

**Issue by fgiroult321** [rebuy-de/aws-nuke#683]
The account i am trying to nuke has a Transit gateway shared with it via RAM, belonging to another account. Nuke failed because the resource is not find locally. Is there a way to ignore these resources, not from their type but on the fact they are owned by an external account ?
 
<img width="1433" alt="Capture d’écran 2021-09-10 à 14 01 42" src="https://user-images.githubusercontent.com/63405533/132851086-325db9d1-fea2-4810-897f-6f163c126b0f.png">

**Comment by ekristen** [comment]
@fgiroult321 are you comfortable with golang at all? Taking a look at the code this should be fixable. There's query parameter that can be added to limit ownership to the account being targeted.  I can walk you through the change for testing, or I can put together a PR a bit later.

**Comment by ahkai86** [comment]
> @fgiroult321 are you comfortable with golang at all? Taking a look at the code this should be fixable. There's query parameter that can be added to limit ownership to the account being targeted. I can walk you through the change for testing, or I can put together a PR a bit later.

Hi @fgiroult321 , Good Day! Able to shed some light on which golang file i should be looking into? is it ec2-tgw.go file?
Thanks so much!

**Comment by ekristen** [comment]
Tracking via https://github.com/ekristen/aws-nuke/issues/336

----

Please see the copy of the notice from the README about the deprecation of this project. Sven was kind enough to grant me access to help triage and close issues and pull requests that have already been addressed in the actively maintained fork. Some additional information is located in the [welcome issue](https://github.com/ekristen/aws-nuke/issues/276) for more information. 

> [!CAUTION]
> This repository for aws-nuke is no longer being actively maintained. We recommend users to switch to the actively maintained fork of this project at [ekristen/aws-nuke](https://github.com/ekristen/aws-nuke).
> We appreciate all the support and contributions we've received throughout the life of this project. We believe that the fork will continue to provide the functionality and support that you have come to expect from aws-nuke.
> Please note that this deprecation means we will not be addressing issues, accepting pull requests, or making future releases from this repository.
> Thank you for your understanding and support.
