### ISSUE TITLE
CloudFormationStackSet - Delete Stack

### ISSUE THREAD

**Issue by fernandohonig** [rebuy-de/aws-nuke#684]
Hi,

Is there any flag to indicate to not only delete the instance but also do not retain the stack in each account?

If that flag is available, there is no need to delete stacks in member accounts.

According to this: https://github.com/rebuy-de/aws-nuke/blob/b7b0dedc1adddb9220f6aaa5aaf035b51ac5381d/resources/cloudformation-stackset.go#L118 it's fixed to RetainStacks: true

Sorry I am not good at all with Go, otherwise I'd suggest a PR.

Thanks!

**Comment by ekristen** [comment]
@fernandohonig I'm trying to understand your problem a bit. I've read the cloudformation code and it seems like aws-nuke does this because it will separately list the stacks and nuke them, this is just a quicker way to remove the stackset by not having AWS try and tear down the stacks and instead retain them.

From your comments are you doing cross account stack sets and is this why you are asking to not retain?

**Comment by ekristen** [comment]
Please give the fork a try at https://github.com/ekristen/aws-nuke, if this is still an issue open an issue there. Thank you.

----

Please see the copy of the notice from the README about the deprecation of this project. Sven was kind enough to grant me access to help triage and close issues and pull requests that have already been addressed in the actively maintained fork. Some additional information is located in the [welcome issue](https://github.com/ekristen/aws-nuke/issues/276) for more information. 

> [!CAUTION]
> This repository for aws-nuke is no longer being actively maintained. We recommend users to switch to the actively maintained fork of this project at [ekristen/aws-nuke](https://github.com/ekristen/aws-nuke).
> We appreciate all the support and contributions we've received throughout the life of this project. We believe that the fork will continue to provide the functionality and support that you have come to expect from aws-nuke.
> Please note that this deprecation means we will not be addressing issues, accepting pull requests, or making future releases from this repository.
> Thank you for your understanding and support.
