### ISSUE TITLE
Support deletion of CodeArtifact resources

### ISSUE THREAD

**Issue by ga-paul-t** [rebuy-de/aws-nuke#688]
I have been using aws-nuke recently to factory reset (nuke) an AWS account that our developers use to carry out AWS learning and experimentation. I noticed that most CICD resources are covered, apart from CodeArtifact.

It would be great if aws-nuke could support this resource also.

I am planning on forking this repository to add that additional functionality

**Comment by abdirahmanjama** [comment]
Ah that's a good point! I'm sure a lot of engineering teams will require this!

@dfreudenberger is there any scope for us to merge in this change?
