### ISSUE TITLE
leverage AWS Cloud Control API

### ISSUE THREAD

**Issue by PatMyron** [rebuy-de/aws-nuke#692]
`ListResource` and `DeleteResource` from https://aws.amazon.com/blogs/aws/announcing-aws-cloud-control-api/ seem like an easier way to increase type coverage

**Comment by svenwltr** [comment]
We are working on this in https://github.com/rebuy-de/aws-nuke/pull/753

**Comment by der-eismann** [comment]
Closing because #753 was merged.
