### ISSUE TITLE
Misspelled/Errors neptune snapshot

### ISSUE THREAD

**Issue by chammock** [rebuy-de/aws-nuke#699]
First off, the resource `NetpuneSnapshot` is misspelled and should be `NeptuneSnapshot`.

Second, I got an error while trying to remove an automated Neptune snapshot. The error occurs because the `NeptuneSnapshot` resource is not filtering out automated snapshots, which cannot be deleted.

The following is the printout from a nuke run. The `test-manual` snapshot is expected to be removed as it is a manual snapshot but the `rds:database-1-2021-11-01-16-16` should be filtered out as it's automated.

```
> aws-nuke -c nuke.yml --no-dry-run
aws-nuke version v2.16.0 - Mon Sep  6 14:29:17 UTC 2021 - 048c4bb92e38f8a119fb5d988f548cc622fb1b26

Do you really want to nuke the account with the ID xxxxxxxxxxxx and the alias 'xxxxxx'?
Do you want to continue? Enter account alias to continue.
> xxxxxx

us-east-1 - NetpuneSnapshot - rds:database-1-2021-11-01-16-16 - would remove
us-east-1 - NetpuneSnapshot - test-manual - would remove
Scan complete: 2 total, 2 nukeable, 0 filtered.

Do you really want to nuke these resources on the account with the ID xxxxxxxxxxxx and the alias 'xxxxxx'?
Do you want to continue? Enter account alias to continue.
> xxxxxx

us-east-1 - NetpuneSnapshot - rds:database-1-2021-11-01-16-16 - failed
us-east-1 - NetpuneSnapshot - test-manual - triggered remove

Removal requested: 1 waiting, 1 failed, 0 skipped, 0 finished

us-east-1 - NetpuneSnapshot - rds:database-1-2021-11-01-16-16 - failed
us-east-1 - NetpuneSnapshot - test-manual - waiting

Removal requested: 1 waiting, 1 failed, 0 skipped, 0 finished

us-east-1 - NetpuneSnapshot - rds:database-1-2021-11-01-16-16 - failed
us-east-1 - NetpuneSnapshot - test-manual - removed

Removal requested: 0 waiting, 1 failed, 0 skipped, 1 finished

us-east-1 - NetpuneSnapshot - rds:database-1-2021-11-01-16-16 - failed

Removal requested: 0 waiting, 1 failed, 0 skipped, 1 finished

us-east-1 - NetpuneSnapshot - rds:database-1-2021-11-01-16-16 - failed

Removal requested: 0 waiting, 1 failed, 0 skipped, 1 finished

time="2021-11-01T11:17:28-05:00" level=error msg="There are resources in failed state, but none are ready for deletion, anymore."

us-east-1 - NetpuneSnapshot - rds:database-1-2021-11-01-16-16 - failed
time="2021-11-01T11:17:28-05:00" level=error msg="InvalidDBClusterSnapshotStateFault: Only manual snapshots may be deleted.\n\tstatus code: 400, request id: 8079e6f6-d461-4b96-a682"
Error: failed
```

**Comment by ekristen** [comment]
@chammock this has been fixed in the [now active managed fork of aws-nuke](https://github.com/ekristen/aws-nuke)

If you have a chance, please check it out and let us know if you run into an issues by opening an issue over on the fork.

----

Please see the copy of the notice from the README about the deprecation of this project. Sven was kind enough to grant me access to help triage and close issues and pull requests that have already been addressed in the actively maintained fork. Some additional information is located in the [welcome issue](https://github.com/ekristen/aws-nuke/issues/276) for more information. 

> [!CAUTION]
> This repository for aws-nuke is no longer being actively maintained. We recommend users to switch to the actively maintained fork of this project at [ekristen/aws-nuke](https://github.com/ekristen/aws-nuke).
> We appreciate all the support and contributions we've received throughout the life of this project. We believe that the fork will continue to provide the functionality and support that you have come to expect from aws-nuke.
> Please note that this deprecation means we will not be addressing issues, accepting pull requests, or making future releases from this repository.
> Thank you for your understanding and support.
