### ISSUE TITLE
IAM Role not detached from instance profile and not deleted

### ISSUE THREAD

**Issue by matkosoric** [rebuy-de/aws-nuke#702]
We were getting errors with IAM roles while nuking accounts:

`global - IAMRole - test-role-42021100407080948100000000d - time="2021-11-03T10:06:59Z" level=error msg="DeleteConflict: Cannot delete entity, must remove roles from instance profile first.\n\tstatus code: 409, request id: 2dabdfcb-2edb-4529-a046-542883fa9710" time="2021-11-03T10:06:59Z" level=error msg="DeleteConflict: Cannot delete entity, must remove roles from instance profile first.\n\tstatus code: 409, request id: 8098e1d0-6070-4188-8a10-f654ffddbe8e"`

As a workaround, we listed all roles, filtered relevant ones, then listed instance profiles for each role, and finally within second loop actually detached roles. Here is [gist:](https://gist.github.com/matkosoric/479c9de843c2685eabffe9d39b0a986f)

**Comment by ekristen** [comment]
@matkosoric I haven't experience this and I have roles and instance profiles that I'm cleaning up on a regular basis. The tool retries any failures anyways. Are you still seeing this issue? Can you provide the output from the tool?

**Comment by mavogel** [comment]
I am experiencing the same issue

- version: `v.2.14.0` 
- output:
```
global - IAMUser - ABC-user - failed
--
986 | time="2021-12-06T10:01:15Z" level=error msg="DeleteConflict: Cannot delete entity, must delete login profile first.\n\tstatus code: 409, request id: 02f5f96e-9834-46cd-8bf0-f9a9cf584720"
```

**Comment by ekristen** [comment]
@mavogel does the output have a listing for the instance profile? `IAMInstanceProfile` when it's trying to find all the resources to remove?

**Comment by matkosoric** [comment]
@ekristen I can not reproduce it currently since my bash workaround is working properly and I do not have access to the repo any longer. But output is in fact from the tool, only formatted a bit weirdly by GitLab.

**Comment by matkosoric** [comment]
@ekristen `IAMInstanceProfile` is not listed in logs

**Comment by ekristen** [comment]
Interesting, can you post you post your configuration.

**Comment by ekristen** [comment]
@matkosoric Feel free to sanitize account ids and the like, but try and keep it intact as much as possible. I suspect that the configuration that you ran against 2.14.0 might be omitting the instance profile in some way.

**Comment by matkosoric** [comment]
It is something along following lines; JSON is transformed to YAML. IAMRole, IAMRolePolicy, and IAMRolePolicyAttachment listed here are not the ones causing issues, but roles and instances created via Terraform. That part of the code is unavailable. 

```
filters = {
  IAMUser = [
    "000000"
  ]
  IAMUserAccessKey = [
    { property = UserName, type = regex, value = ".*0000.*"}
  ]
  IAMPolicy = [
    { type = regex, value = "policy/0000000"}
  ]
  IAMUserPolicyAttachment = [
    "0000 -> AdministratorAccess"
    "0000 -> 0000"
    "0000 -> AmazonS3FullAccess"
  ]
  IAMRole = [
    { type = regex, value = ".*0000.*" }
    "OrganizationAccountAccessRole"
    "0000"
  ]
  EC2InternetGateway = [
    { property =  DefaultForAz, value = "true" }
  ]
  EC2VPC = [
    { property = IsDefault, value = "true" }
  ]
  EC2DHCPOption = [
    { type = regex, value = ".*0000.*" }
  ]
  EC2Subnet = [
    { property = DefaultForAz, value = "true" }
  ]
  IAMRolePolicy = [
    "OrganizationAccountAccessRole -> AdministratorAccess"
    { type = regex, value = ".*0000.*" }
  ]
  IAMRolePolicyAttachment = [
    { type = regex, value = ".*0000.*" }
    "0000 -> AdministratorAccess" 
    "0000 -> AmazonRoute53FullAccess"
  ]
  S3Bucket = [
    {type = regex, value = ".*0000.*"} 
  ]
  EC2InternetGatewayAttachment = [
        "igw-00000000 -> vpc-0000"
  ]
  EC2RouteTable = [
    "rtb-0000"
  ]
  EC2InternetGateway = [
    "igw-0000"
  ]
}
```

**Comment by ekristen** [comment]
@mavogel you aren't limiting which resources the tool is run again using the `resourceTypes` part of the configuration? (ie including/excluding any resources?

**Comment by matkosoric** [comment]
this is actually the ignore list, just in JSON, everything else should be nuked

**Comment by ekristen** [comment]
Closing due to stale nature. If this is still an issue, please open an issue at https://github.com/ekristen/aws-nuke

----

Please see the copy of the notice from the README about the deprecation of this project. Sven was kind enough to grant me access to help triage and close issues and pull requests that have already been addressed in the actively maintained fork. Some additional information is located in the [welcome issue](https://github.com/ekristen/aws-nuke/issues/276) for more information. 

> [!CAUTION]
> This repository for aws-nuke is no longer being actively maintained. We recommend users to switch to the actively maintained fork of this project at [ekristen/aws-nuke](https://github.com/ekristen/aws-nuke).
> We appreciate all the support and contributions we've received throughout the life of this project. We believe that the fork will continue to provide the functionality and support that you have come to expect from aws-nuke.
> Please note that this deprecation means we will not be addressing issues, accepting pull requests, or making future releases from this repository.
> Thank you for your understanding and support.
