### ISSUE TITLE
Nuke ECS services and task-definition based on tags

### ISSUE THREAD

**Issue by bikochan** [rebuy-de/aws-nuke#707]
This is similar to the general question of using tags to filter all resources but may be a simpler and maybe more pressing use case.
ECS services and tasks may come and go quickly and maybe also have unpredictable names so using tags to identify them and exclude them from aws-nuke run would be beneficial.
Perhaps more annoyingly tho, the AWS api don't seem to return the tags by default.
`aws ecs describe-services --cluster lizard --services lexx  | jq 'del(.services[0].events) | .services[0].tags'                                                                            `
returns nothing
```
aws ecs describe-services --cluster lizard --services lexx --include TAGS | jq 'del(.services[0].events) | .services[0].tags'                                                                         

[
  {
    "key": "Parallel Universe",
    "value": "1"
  }
]
```

**Comment by ekristen** [comment]
It's on my backlog for the fork.

----

Please see the copy of the notice from the README about the deprecation of this project. Sven was kind enough to grant me access to help triage and close issues and pull requests that have already been addressed in the actively maintained fork. Some additional information is located in the [welcome issue](https://github.com/ekristen/aws-nuke/issues/276) for more information. 

> [!CAUTION]
> This repository for aws-nuke is no longer being actively maintained. We recommend users to switch to the actively maintained fork of this project at [ekristen/aws-nuke](https://github.com/ekristen/aws-nuke).
> We appreciate all the support and contributions we've received throughout the life of this project. We believe that the fork will continue to provide the functionality and support that you have come to expect from aws-nuke.
> Please note that this deprecation means we will not be addressing issues, accepting pull requests, or making future releases from this repository.
> Thank you for your understanding and support.
