### ISSUE TITLE
lookup s3-control.us-east-1.amazonaws.com: no such host

### ISSUE THREAD

**Issue by chammock** [rebuy-de/aws-nuke#708]
I'm trying to contribute and solve issue #660  by building a new resource of `S3AccessPoint`. However, when setting up the `s3control` client, it returns an error that it can't lookup the host name for the endpoint.  The `s3control` endpoints actually hit `{accountId}.s3-control.us-east-1.amazonaws.com`. Its failing because of [this line](https://github.com/rebuy-de/aws-nuke/blob/main/pkg/awsutil/session.go#L236). Any suggestions to solve this would be appreciated, thanks. 

Example logs 
```
time="9999-99-99T99:99:00-00:00" level=debug msg="lookup s3-control.us-east-1.amazonaws.com: no such host"
time="9999-99-99T99:99:00-00:00" level=warning msg="skipping request: DNS lookup failed for s3-control.us-east-1.amazonaws.com; assuming it does not exist in this region"
```

[AWS S3 Endpoints](https://docs.aws.amazon.com/general/latest/gr/s3.html#s3_region)

**Comment by svenwltr** [comment]
Hello. Please try updating the aws-sdk. This could solve the issue. Please reach back, if this does not work.

**Comment by chammock** [comment]
@svenwltr Updated to `github.com/aws/aws-sdk-go v1.42.1` and still same issue.

**Comment by svenwltr** [comment]
Hello. In this case we should add an exception to the function you posted (ideally with a comment explaining why this is necessary). If we stumble across this issue more often, we have to find a generic solution.

**Comment by chammock** [comment]
Thanks. I'll include an exception so the `s3-control` service does not perform the host lookup.

For reference here is how AWS's SDK is adding the account id before making the request.
https://github.com/aws/aws-sdk-go/blob/98741a3d5b508dc8b0b3af3b9cf0d56856cbba20/service/s3control/api.go#L3692

**Comment by chammock** [comment]
I think the root of this issue is the fact we're getting `ServiceName` from the metadata of client whereas the endpoints are now found by using the service's `EndpointsID`, which isn't exposed in the metadata.
