### ISSUE TITLE
Failed, please help. I am unable to delete using Nuke

### ISSUE THREAD

**Issue by rahmansamia** [rebuy-de/aws-nuke#724]
<img width="702" alt="failed" src="https://user-images.githubusercontent.com/34420776/146993203-a14ed381-b062-4f8e-bf0f-6d42acb4bbad.PNG">

I am unable to delete any resources in my acccount sing nuke. The account I am using have admin access. Please advise. Why I am seeing failed.

**Comment by rahmansamia** [comment]
Its not deleting any resources.

**Comment by rahmansamia** [comment]
<img width="230" alt="config file" src="https://user-images.githubusercontent.com/34420776/146995826-bf1999e2-609d-42fb-acbe-4d200da1aa37.PNG">
adding config file.

**Comment by rahmansamia** [comment]
I see similar issue listed https://github.com/rebuy-de/aws-nuke/issues/457 but dont see any solution.

**Comment by ekristen** [comment]
Please test using the [actively managed fork of aws-nuke](https://github.com/ekristen/aws-nuke).

If the issue still persists, please open an issue on the fork.

----

Please see the copy of the notice from the README about the deprecation of this project. Sven was kind enough to grant me access to help triage and close issues and pull requests that have already been addressed in the actively maintained fork. Some additional information is located in the [welcome issue](https://github.com/ekristen/aws-nuke/issues/276) for more information. 

> [!CAUTION]
> This repository for aws-nuke is no longer being actively maintained. We recommend users to switch to the actively maintained fork of this project at [ekristen/aws-nuke](https://github.com/ekristen/aws-nuke).
> We appreciate all the support and contributions we've received throughout the life of this project. We believe that the fork will continue to provide the functionality and support that you have come to expect from aws-nuke.
> Please note that this deprecation means we will not be addressing issues, accepting pull requests, or making future releases from this repository.
> Thank you for your understanding and support.
