### ISSUE TITLE
Skipping request: service 'iam' is global, but the session is not

### ISSUE THREAD

**Issue by frittatelle** [rebuy-de/aws-nuke#726]
Hi,
I'm trying to destroy my IAM policies and roles.
The configuration file is very simple:
```
regions:
  - global

accounts:
  "xxxxxxxxx": {} //myawsaccount
```
By running the aws nuke command I get "No resource to delete" even if I can clearly see them in the aws console. 
By looking at the debug logs I saw this error: "**skipping request: service 'iam' is global, but the session is not**".
Even by specifying "**global**" as the only region I still get a session in "**us-east-1**".
Please notice I specified the region also in the default credentials and config aws files. 
I also tried to specify targets in the nuke config file but nothing changed.

**Comment by IoannisKri** [comment]
Hi,

I also had the same issue. The way to solve it is by setting the regions like this:

regions:
- eu-central-1
- global

Hope this helps

**Comment by frittatelle** [comment]
> Hi,
> 
> I also had the same issue. The way to solve it is by setting the regions like this:
> 
> ```
> regions:
> - eu-central-1
> - global
> ```
> 
> Hope this helps

Thank you very much, the regions order was indeed the problem. Specifying them in the right order fixed the issue.
