### ISSUE TITLE
fix: update default controltower config in s3 to remove account-blacklist deprecation 

### ISSUE THREAD

**Issue by mavogel** [rebuy-de/aws-nuke#732]
- aws-nuke version `v2.16.0`
- config pulled at `2022-01-20-14:39` with the command
```sh
aws s3 cp s3://aws-nuke-config-retain-control-tower/aws-nuke-config.yaml .
```

```console
aws-nuke version v2.16.0 - Mon Sep  6 14:19:03 UTC 2021 - 048c4bb92e38f8a119fb5d988f548cc622fb1b26
--
63 |  
64 | time="2022-01-20T15:52:49Z" level=warning msg="deprecated configuration key 'account-blacklist' - please use 'account-blocklist' instead"
```

**Comment by der-eismann** [comment]
If I understand correctly you are pulling an aws-nuke config from some S3 bucket, which was become outdated. However that config is not provided by us, so there is nothing we can do about this.

**Comment by mavogel** [comment]
Ah ok, thanks for the clarification. I thought it comes from you folks. Then I'll take it as a baseline and build my own :)
