### ISSUE TITLE
What is the best way to run aws-nuke from inside lambda function?

### ISSUE THREAD

**Issue by ilgiznurgaliev** [rebuy-de/aws-nuke#735]
Hi.

I have an AWS Organizations and want to nuke all resources in member account from lambda function which is in master account. The lambda function already has permissions to assume admin role in member account. This admin role won't be removed, I'm going to filter it in aws-nuke. Thinking about to run lambda with python that will assume admin role in member account and use subprocess module to run aws-nuke with temporary aws creds. Will it be a good way or there is something better?

Thanks in advance.

**Comment by kanumuruwe45** [comment]
Yes this can be used, You can use launch lambda as a container and invoke lambda to nuke

**Comment by leonardoviveiros** [comment]
We we're able to run `aws-nuke` on Lambda based on Lambda Python 3.9 runtime.

```Dockerfile
FROM public.ecr.aws/lambda/python:3.9

COPY orchestrateNuke.py ${LAMBDA_TASK_ROOT}
RUN yum install -y tar xz gzip

ADD https://github.com/rebuy-de/aws-nuke/releases/download/v2.19.0/aws-nuke-v2.19.0-linux-amd64.tar.gz ${LAMBDA_TASK_ROOT}
RUN tar -zxvf aws-nuke-v2.19.0-linux-amd64.tar.gz && rm -rf aws-nuke-v2.19.0-linux-amd64.tar.gz

CMD [ "orchestrateNuke.lambda_handler" ]
```

The file `orchestrateNuke.py` is where we perform administrative tasks then run `aws-nuke`:

```python
def lambda_handler(event, context):
    ....
    file_path = os.environ['LAMBDA_TASK_ROOT']
    output = subprocess.check_output(["%s/aws-nuke-v2.19.0-linux-amd64" % file_path, "--help"], 
                                      stderr=subprocess.STDOUT, shell=False)
```

**Comment by JonHolman** [comment]
I like the idea of running this in a lambda. I'm trying to understand how the process would work. Does aws-nuke have the ability to pass a list of resources to be deleted? I'm thinking about how with terraform, you can run plan, save the plan and review it, then apply while providing the approved plan. That would prevent unintentionally deleting new resources that someone created while aws-nuke was running. If that functionality doesn't exist, I'm curious how difficult it would be to add it. Still, without that, I imagine the lambda could be just informative (send us information about new existing resources), or it could use --force which will be too aggressive for most use cases. Regardless, I love this idea.
