### ISSUE TITLE
Release 2.17.0 is missing from docker registries

### ISSUE THREAD

**Issue by z0rc** [rebuy-de/aws-nuke#738]
https://github.com/rebuy-de/aws-nuke/releases/tag/v2.17.0 isn't available at https://quay.io/repository/rebuy/aws-nuke?tag=latest&tab=tags or at https://hub.docker.com/r/rebuy/aws-nuke/tags?page=1&ordering=last_updated.

**Comment by der-eismann** [comment]
Sorry, the build sometimes fails for the armv7 architecture. Thanks for the reminder, we definitely need to fix that before the next release.
