### ISSUE TITLE
What is the best way to filter resources by creation date?

### ISSUE THREAD

**Issue by Andr3dre** [rebuy-de/aws-nuke#743]
I know not all resources can be filer by dateOlderThan but is there a way to exclude all resources that nuke finds when running it in a newly created account?

Example:  I create a new account and automation populates the account with curated resources I want to keep around.  I would run nuke and it would return a list of those resources that it can delete. Is there a way to turn that list into a config file that would represent those resources exactly?  

Maybe this can be a feature request as it can keep a golden state of an account in the case someone would just want to always revert the account as a whole.

**Comment by ekristen** [comment]
There's a concept around a baseline configuration generator that's being considered for the fork. Keep an eye out over there.
