### ISSUE TITLE
Is there any way to nuke a single vpc?

### ISSUE THREAD

**Issue by Scumble** [rebuy-de/aws-nuke#744]
I have multiple VPC's per environment on account and I'm wondering is there any option to filter and remove a single VPC instead of all at once?

**Comment by ekristen** [comment]
The tool is built to nuke everything so you'd have to write a config that excludes everything you don't want it to touch, run the tool in dry run mode (default) to validate before running for real.

**Comment by der-eismann** [comment]
Closing this issue because there is no response and it should be easy to filter one VPC with tags.
