### ISSUE TITLE
LoginProfile not deleted

### ISSUE THREAD

**Issue by TomMGWhit** [rebuy-de/aws-nuke#750]
After upgrading nuke from 1.6 to 1.7 we have started getting occasional errors when trying to delete login profiles: 

Removal requested: 0 waiting, 2 failed, 288 skipped, 34 finished
time="2022-03-02T17:16:08Z" level=error msg="DeleteConflict: Cannot delete entity, must delete login profile first.\n\tstatus code: 409, request id: 28200c0e-2fb8-4b6c-864e-5e03579a59d5"
time="2022-03-02T17:16:08Z" level=error msg="EntityTemporarilyUnmodifiable: Login Profile for User <user> cannot be modified while login profile is being created.\n\tstatus code: 409, request id: c16aefa3-8e5d-4577-899a-84f63927353f"
Error: failed

We can't see any significant changes between the versions of iam-users.go that would obviously cause this. It is not happening every time so we suspect it may be a race condition? This also makes it hard to recreate. 

The users are created via Terraform

Any help or suggestions welcome :)

**Comment by ekristen** [comment]
Please try this out in the fork at https://github.com/ekristen/aws-nuke, if this is still a problem open an issue over there. Thanks.

----

Please see the copy of the notice from the README about the deprecation of this project. Sven was kind enough to grant me access to help triage and close issues and pull requests that have already been addressed in the actively maintained fork. Some additional information is located in the [welcome issue](https://github.com/ekristen/aws-nuke/issues/276) for more information. 

> [!CAUTION]
> This repository for aws-nuke is no longer being actively maintained. We recommend users to switch to the actively maintained fork of this project at [ekristen/aws-nuke](https://github.com/ekristen/aws-nuke).
> We appreciate all the support and contributions we've received throughout the life of this project. We believe that the fork will continue to provide the functionality and support that you have come to expect from aws-nuke.
> Please note that this deprecation means we will not be addressing issues, accepting pull requests, or making future releases from this repository.
> Thank you for your understanding and support.
