### ISSUE TITLE
ComprehendDominantLanguageDetectionJob - panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by madanbs** [rebuy-de/aws-nuke#754]
Team,

aws nuke command is failing with this error. Could you please help.

us-east-1 - ComprehendDominantLanguageDetectionJob - panic: runtime error: invalid memory address or nil pointer dereference
--
1300 | [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x369b9d1]
1301 |  
1302 | goroutine 1 [running]:
1303 | github.com/rebuy-de/aws-nuke/resources.(*ComprehendDominantLanguageDetectionJob).String(0xc000d406c0, 0x55747c0, 0xc000d406c0)
1304 | /home/runner/work/aws-nuke/aws-nuke/resources/comprehend_dominant_language_detection_job.go:62 +0x11
1305 | github.com/rebuy-de/aws-nuke/cmd.Log(0xc0004053b0, 0x4edd5a4, 0x26, 0x55747c0, 0xc000d406c0, 0xc0001171e8, 0x1, 0x1, 0x0, 0x4e7743b, ...)
1306 | /home/runner/work/aws-nuke/aws-nuke/cmd/log.go:51 +0x35b
1307 | github.com/rebuy-de/aws-nuke/cmd.(*Item).Print(0xc000d5da00)
1308 | /home/runner/work/aws-nuke/aws-nuke/cmd/queue.go:36 +0x1c5
1309 | github.com/rebuy-de/aws-nuke/cmd.(*Nuke).Scan(0xc00015edc0, 0xc000118008, 0x4ec5b4c)
1310 | /home/runner/work/aws-nuke/aws-nuke/cmd/nuke.go:173 +0x41a
1311 | github.com/rebuy-de/aws-nuke/cmd.(*Nuke).Run(0xc00015edc0, 0xc00015edc0, 0x0)
1312 | /home/runner/work/aws-nuke/aws-nuke/cmd/nuke.go:61 +0x3bb
1313 | github.com/rebuy-de/aws-nuke/cmd.NewRootCommand.func2(0xc0002acf00, 0xc00011ec40, 0x0, 0x4, 0x0, 0x0)
1314 | /home/runner/work/aws-nuke/aws-nuke/cmd/root.go:90 +0x3cb
1315 | github.com/spf13/cobra.(*Command).execute(0xc0002acf00, 0xc000120010, 0x4, 0x4, 0xc0002acf00, 0xc000120010)
1316 | /home/runner/work/aws-nuke/aws-nuke/vendor/github.com/spf13/cobra/command.go:852 +0x472
1317 | github.com/spf13/cobra.(*Command).ExecuteC(0xc0002acf00, 0x0, 0x3bc2f20, 0xc000100058)
1318 | /home/runner/work/aws-nuke/aws-nuke/vendor/github.com/spf13/cobra/command.go:960 +0x375
1319 | github.com/spf13/cobra.(*Command).Execute(...)
1320 | /home/runner/work/aws-nuke/aws-nuke/vendor/github.com/spf13/cobra/command.go:897
1321 | main.main()
1322 | /home/runner/work/aws-nuke/aws-nuke/main.go:25 +0x2a

**Comment by madanbs** [comment]
Team,

Awaiting for your response.

**Comment by svenwltr** [comment]
Hello,

there seems to be a bug in the `ComprehendDominantLanguageDetectionJob` resource.

The easiest way to avoid this is to exclude the resource:

```yaml
resource-types:
  excludes:
    - ComprehendDominantLanguageDetectionJob
```

Of course this only works, if you do not actually want to delete this kind of resources. If you do you have to wait for a bug fix.

**Comment by madanbs** [comment]
@svenwltr 

Okay. Thanks for the update. Please keep me update once the fix in place.

**Comment by ekristen** [comment]
Closing due to age. Please test v3 at https://github.com/ekristen/aws-nuke and open an issue there if the problem persists.

----

Please see the copy of the notice from the README about the deprecation of this project. Sven was kind enough to grant me access to help triage and close issues and pull requests that have already been addressed in the actively maintained fork. Some additional information is located in the [welcome issue](https://github.com/ekristen/aws-nuke/issues/276) for more information. 

> [!CAUTION]
> This repository for aws-nuke is no longer being actively maintained. We recommend users to switch to the actively maintained fork of this project at [ekristen/aws-nuke](https://github.com/ekristen/aws-nuke).
> We appreciate all the support and contributions we've received throughout the life of this project. We believe that the fork will continue to provide the functionality and support that you have come to expect from aws-nuke.
> Please note that this deprecation means we will not be addressing issues, accepting pull requests, or making future releases from this repository.
> Thank you for your understanding and support.
