### ISSUE TITLE
Output and input nuke plan

### ISSUE THREAD

**Issue by jamesgeddes** [rebuy-de/aws-nuke#755]
How do you output a (terraform style) nuke plan? How do you then use that nuke plan as the input for what to nuke?

This would be helpful when warning people what will be nuked _x_ hours before actually executing the nuke.

**Comment by fergoid** [comment]
I usually output to a text file when I am dry running but of course there may be additional resources that will be picked up later when you come to do it for real after checking etc.

**Comment by jamesgeddes** [comment]
It would be great to be able to guarantee that the boxes one says will be nuked are the ones that are actually nuked. This is only possible if the previously output dry-run plan is taken as the input for the `--no-dry-run`. As you say @fergoid, recalculation at a different time can lead to different results.

**Comment by ekristen** [comment]
I love the idea of a nuke plan, I even have it listed for request for comment on this fork. I'm closing this issue now to help with cleanup as this repo is now deprecated, please if you are in support of this feature head over to https://github.com/ekristen/aws-nuke/issues/85 and give it a thumbs up and leave any feedback.

----

Please see a copy of the notice from the README about the deprecation of this project. Sven was kind enough to grant me access to help triage and close issues and pull requests that have already been addressed in the actively maintained fork. Some additional information is located in the [welcome issue](https://github.com/ekristen/aws-nuke/issues/276) for more information. 

> [!CAUTION]
> This repository for aws-nuke is no longer being actively maintained. We recommend users to switch to the actively maintained fork of this project at [ekristen/aws-nuke](https://github.com/ekristen/aws-nuke).
> We appreciate all the support and contributions we've received throughout the life of this project. We believe that the fork will continue to provide the functionality and support that you have come to expect from aws-nuke.
> Please note that this deprecation means we will not be addressing issues, accepting pull requests, or making future releases from this repository.
> Thank you for your understanding and support.
