### ISSUE TITLE
Clarify dateOlderThan documentation to provide full syntax

### ISSUE THREAD

**Issue by jamesgeddes** [rebuy-de/aws-nuke#756]
How do you nuke resources that are more than 7 days old, rather than older than a fixed date?

**Comment by jamesgeddes** [comment]
https://stackoverflow.com/q/71409119/4162689

**Comment by svenwltr** [comment]
I think you have to specify the date in hours: `168h`.

Not sure why you think putting code in the `value` field would work?

**Comment by nhemchand** [comment]
Can you provide a syntax for the cleaning up EC2 instances that are 30 days or older.
Does it work with other EC2 conditions in place as well?

**Comment by rayyin-ps** [comment]
@jamesgeddes According to the docs, a value of "-7d" should work.

**Comment by nhemchand** [comment]
1. This code snippet does not seem to be working.
Im still able to delete ec2 instance of 60days old. 
######################
EC2Instance:
        - property: dateOlderThan
          value: "time.Now().AddDate(0, 0, -90d)"
######################

2. Can similar logic as above used for other 375 resources as well?
nuke resource-types | wc -l ( 375 resources )

**Comment by jamesgeddes** [comment]
Same here, I'm still getting `0 filtered` regardless of what I put in.

I have updated the ticket title accordinly

**Comment by svenwltr** [comment]
Hello. Please take a look at this answer: https://github.com/rebuy-de/aws-nuke/issues/767#issuecomment-1090185334

**Comment by jamesgeddes** [comment]
Riiiiight! Makes sense! 

It would certainly be helpful if the readme could explicitly clarify this, particularly as I am apparently not the only person to be confused 😂  Thank you in advance

**Comment by jamesgeddes** [comment]
It would also be helpful to clarify the logic that dateOlderThan is using.

For example, I now have the config of,

```yml
accounts:
  xxxxxxxxxxxx:
    filters: 
      EC2Instance:
        - property: LaunchTime
          type: dateOlderThan
          value: "100h"
      S3Bucket:
        - property: Name
          value: "foo"
```

As I understand it, if an object matches the filter, it is skipped, so here, I would expect the following to be saved
- all buckets named "foo"
- all EC2 instances that have LaunchTime of older than 100 hours.

What actually happens is that the following are saved,
 - all buckets named "foo"
- all EC2 instances that have LaunchTime of *younger* than 100 hours.

Conveniently, I wanted to save new instances anyway, however, is this behaviour counterintuitive? Equally, is it too late to change it now?

**Comment by svenwltr** [comment]
> Conveniently, I wanted to save new instances anyway, however, is this behaviour counterintuitive?

This is discussed here: https://github.com/rebuy-de/aws-nuke/pull/480

> Equally, is it too late to change it now?

Yes, this would break the filters of everyone using it.
