### ISSUE TITLE
Bucket with 16M items, stuck - running in k8s,  container dies

### ISSUE THREAD

**Issue by gfrid** [rebuy-de/aws-nuke#775]
Running aws-nuke in K8s container in jenkins/slave-jnlp, container dies in idle after several minutes 
the nuke is stuck on huge bucket sizes.

is there any workaround to this except skipping? 
how does aws-nuke with s3, does it build a table on what to delete, maybe its a problem with container storage size or compute power?

**Comment by ekristen** [comment]
Unless you need to prune specific s3 objects, simply exclude the s3 object type and just have it cleanup s3 buckets in their entirety.

```yaml
resource-types:
  excludes:
    - S3Object
```

**Comment by gfrid** [comment]
yes, that what we did
and we also wrote small boto3 to handle it
https://github.com/gfrid/expire-large-aws-s3-buckets/blob/main/boto3/expire_s3_bucket.py

**Comment by ekristen** [comment]
I'm not sure I understand. What is your goal? To delete the bucket entirely or to empty the bucket and but keep the bucket?

**Comment by gfrid** [comment]
> I'm not sure I understand. What is your goal? To delete the bucket entirely or to empty the bucket and but keep the bucket?

my goal is to empty the bucket and remove it, since programmatically deleting 16M items will take weeks (calculated) everyone advice to set expire policy. My question if the owner of this app can program such logic else the case is closed.

**Comment by ekristen** [comment]
@gfrid if you add the exclude to your config I recommended then aws nuke won't iterate the objects it'll just nuke the entire bucket and you'll be done.

**Comment by alexandrosgkesos** [comment]
@ekristen  Can this be added in the README?

`The --exclude flag prevent nuking of the specified resource types.`
,is confusing

I would never thought that by adding something there, it would still be deleted. I know, corner case, but...

**Comment by ekristen** [comment]
@alexandrosgkesos I'm not sure I follow, but if this is still an issue open an issue up on the fork please.

----

Please see the copy of the notice from the README about the deprecation of this project. Sven was kind enough to grant me access to help triage and close issues and pull requests that have already been addressed in the actively maintained fork. Some additional information is located in the [welcome issue](https://github.com/ekristen/aws-nuke/issues/276) for more information. 

> [!CAUTION]
> This repository for aws-nuke is no longer being actively maintained. We recommend users to switch to the actively maintained fork of this project at [ekristen/aws-nuke](https://github.com/ekristen/aws-nuke).
> We appreciate all the support and contributions we've received throughout the life of this project. We believe that the fork will continue to provide the functionality and support that you have come to expect from aws-nuke.
> Please note that this deprecation means we will not be addressing issues, accepting pull requests, or making future releases from this repository.
> Thank you for your understanding and support.
