### ISSUE TITLE
AWS Network Firewall not found in resources

### ISSUE THREAD

**Issue by Moeezulhaq** [rebuy-de/aws-nuke#776]
I wanted to delete AWS Network Firewall using the Nuke but I couldn't find it in the resources folder.
Does AWS Nuke support this feature or is it supposed to be created?
Thanks

**Comment by Moeezulhaq** [comment]
[svenwltr](https://github.com/svenwltr) Can you please guide me regarding this?

**Comment by svenwltr** [comment]
Hello @Moeezulhaq. aws-nuke does not yet support network firewalls. I added support in this PR: https://github.com/rebuy-de/aws-nuke/pull/777

**Comment by Moeezulhaq** [comment]
Thank you
