### ISSUE TITLE
Support for report output as json, csv 

### ISSUE THREAD

**Issue by rams3sh** [rebuy-de/aws-nuke#794]
I use aws-nuke for purpose of resource discovery across my AWS accounts. 

It would be nice if aws-nuke could support exporting the discovered resources as json or csv.

**Comment by svenwltr** [comment]
Sounds like an interesting idea. Unfortunately it will take a while until we find time implementing it.

Meanwhile you might be interested in [awsls](https://github.com/jckuester/awsls).

**Comment by oijkn** [comment]
Hello there!

I noticed the discussion here and thought it might be a good opportunity to introduce a tool I've been working on that could be relevant to this conversation. My project, `aws-nuke-exporter`, is designed to help users export `aws-nuke` logs into structured formats like **JSON** or **CSV**, making it easier to parse and analyze the output.

The tool is easy to use and can be a great asset for those who regularly work with aws-nuke and need a more streamlined way to handle the logs. It's open-source and available on PyPI for easy installation `pip install aws-nuke-exporter`.

You can find more information about it, including usage instructions, on the GitHub repository: [aws-nuke-exporter](https://github.com/oijkn/aws-nuke-exporter).

I'd love for you all to check it out and hear any feedback or suggestions you might have. If it suits your needs, feel free to use it and contribute to its development!

Thanks for considering it, and I hope it can be of help to those using aws-nuke !

**Comment by ekristen** [comment]
Tracking something like this over at https://github.com/ekristen/aws-nuke/issues/154


If you have a chance, please check it out and let us know if you run into an issues by opening an issue over on the fork.

----

Please see the copy of the notice from the README about the deprecation of this project. Sven was kind enough to grant me access to help triage and close issues and pull requests that have already been addressed in the actively maintained fork. Some additional information is located in the [welcome issue](https://github.com/ekristen/aws-nuke/issues/276) for more information. 

> [!CAUTION]
> This repository for aws-nuke is no longer being actively maintained. We recommend users to switch to the actively maintained fork of this project at [ekristen/aws-nuke](https://github.com/ekristen/aws-nuke).
> We appreciate all the support and contributions we've received throughout the life of this project. We believe that the fork will continue to provide the functionality and support that you have come to expect from aws-nuke.
> Please note that this deprecation means we will not be addressing issues, accepting pull requests, or making future releases from this repository.
> Thank you for your understanding and support.
