### ISSUE TITLE
Go panic when reaching route53resolverrule during dry run.

### ISSUE THREAD

**Issue by hugorodro** [rebuy-de/aws-nuke#795]
**Version:** aws-nuke-v2.17.0

us-east-1 - Route53ResolverRule - rslvr-autodefined-rr-internet-resolver (Internet Resolver) - [ID: "rslvr-autodefined-rr-internet-resolver", Name: "Internet Resolver"] - Filtering DomainName "."
us-east-1 - Route53ResolverRule - panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x103c5acf0]

goroutine 1 [running]:
github.com/rebuy-de/aws-nuke/resources.(*Route53ResolverRule).String(0x140009a7440, 0x105aff918, 0x140009a7440)
        /home/runner/work/aws-nuke/aws-nuke/resources/route53-resolver-rules.go:139 +0x60
github.com/rebuy-de/aws-nuke/cmd.Log(0x14000c69740, 0x103d0bb59, 0x13, 0x105aff918, 0x140009a7440, 0x1400011b1c8, 0x1, 0x1, 0x0, 0x103cf29a0, ...)
        /home/runner/work/aws-nuke/aws-nuke/cmd/log.go:51 +0x2d4
github.com/rebuy-de/aws-nuke/cmd.(*Item).Print(0x140009a7740)
        /home/runner/work/aws-nuke/aws-nuke/cmd/queue.go:36 +0x1a4
github.com/rebuy-de/aws-nuke/cmd.(*Nuke).Scan(0x1400054e000, 0xd, 0x0)
        /home/runner/work/aws-nuke/aws-nuke/cmd/nuke.go:173 +0x2d0
github.com/rebuy-de/aws-nuke/cmd.(*Nuke).Run(0x1400054e000, 0x1400054e000, 0x0)
        /home/runner/work/aws-nuke/aws-nuke/cmd/nuke.go:61 +0x2d0
github.com/rebuy-de/aws-nuke/cmd.NewRootCommand.func2(0x1400032cf00, 0x14000141120, 0x0, 0x2, 0x0, 0x0)
        /home/runner/work/aws-nuke/aws-nuke/cmd/root.go:90 +0x2d8
github.com/spf13/cobra.(*Command).execute(0x1400032cf00, 0x140001140a0, 0x2, 0x2, 0x1400032cf00, 0x140001140a0)
        /home/runner/work/aws-nuke/aws-nuke/vendor/github.com/spf13/cobra/command.go:852 +0x320
github.com/spf13/cobra.(*Command).ExecuteC(0x1400032cf00, 0x10102417c, 0x1045cf0e0, 0x14000000180)
        /home/runner/work/aws-nuke/aws-nuke/vendor/github.com/spf13/cobra/command.go:960 +0x258
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/work/aws-nuke/aws-nuke/vendor/github.com/spf13/cobra/command.go:897
main.main()
        /home/runner/work/aws-nuke/aws-nuke/main.go:25 +0x24

**Comment by WagnerTT** [comment]
Same problem here, created a new account to test aws-nuke, put all other accounts on blocklist, but aws-nuke is trying to delete some Route53ResolverRules on blocked accounts. 

Version: aws-nuke-v2.19.0
Using --assume-role-arn.

Usage:
User is in account A, aws-nuke is running against account B(assume-role to this account) and the resources(Route53ResolverRules) that aws-nuke is trying to delete are on account C.

Accounts A and C are in the blocklist, only account B is the 'nukable' account.

**Comment by airmonitor** [comment]
Hello @hugorodro.

I'm wondering if you were able to bypass this somehow?

Tom

**Comment by x2lcetins4pa** [comment]
I'm getting the same issue with version 2.25.0

**Comment by ekristen** [comment]
@hugorodro @airmonitor @x2lcetins4pa This issue has been resolved. Please see the [actively managed fork of aws-nuke](https://github.com/ekristen/aws-nuke).

If you have a chance, please check it out and let us know if you run into an issues by opening an issue over on the fork.

----

Please see the copy of the notice from the README about the deprecation of this project. Sven was kind enough to grant me access to help triage and close issues and pull requests that have already been addressed in the actively maintained fork. Some additional information is located in the [welcome issue](https://github.com/ekristen/aws-nuke/issues/276) for more information. 

> [!CAUTION]
> This repository for aws-nuke is no longer being actively maintained. We recommend users to switch to the actively maintained fork of this project at [ekristen/aws-nuke](https://github.com/ekristen/aws-nuke).
> We appreciate all the support and contributions we've received throughout the life of this project. We believe that the fork will continue to provide the functionality and support that you have come to expect from aws-nuke.
> Please note that this deprecation means we will not be addressing issues, accepting pull requests, or making future releases from this repository.
> Thank you for your understanding and support.
