### ISSUE TITLE
Missing artefact in release 2.19.0

### ISSUE THREAD

**Issue by mbevc1** [rebuy-de/aws-nuke#805]
Is something wrong missing in latest release package for Linux amd64?
```
  • Getting v2.19.0 release for rebuy-de/aws-nuke
   • Starting download of https://api.github.com/repos/rebuy-de/aws-nuke/releases/assets/65889581
25.04 MiB / 25.04 MiB [----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------] 100.00% 8.67 MiB p/s 3s
   ⨯ command failed            error=No files found in tar archive. PackagePath [aws-nuke-v2.18.1-linux-amd64]
```

**Comment by bjoernhaeuser** [comment]
Hi @mbevc1,

there is seams to be an error on your side and the title says `2.19.0` but the download link is talking about `2.18.1`.

On both asset pages the download for `linux-amd64` works fine for me:

* https://github.com/rebuy-de/aws-nuke/releases/download/v2.18.1/aws-nuke-v2.18.1-linux-amd64.tar.gz
* https://github.com/rebuy-de/aws-nuke/releases/download/v2.19.0/aws-nuke-v2.19.0-linux-amd64.tar.gz

**Comment by mbevc1** [comment]
Yeah, seems re-installing got it working. Must be some caching weirdness... Thanks!
