### ISSUE TITLE
Deleting service roles is disabled but should be allowed

### ISSUE THREAD

**Issue by wahlfeld10x** [rebuy-de/aws-nuke#807]
[AWS enabled deleting service roles in 2017.](https://aws.amazon.com/blogs/security/now-use-aws-iam-to-delete-a-service-linked-role-when-you-no-longer-require-an-aws-service-to-perform-actions-on-your-behalf/)

https://github.com/rebuy-de/aws-nuke/blob/main/resources/iam-roles.go#L71-L76

**Comment by ekristen** [comment]
Will be included in https://github.com/ekristen/aws-nuke/pull/329

----

Please see the copy of the notice from the README about the deprecation of this project. Sven was kind enough to grant me access to help triage and close issues and pull requests that have already been addressed in the actively maintained fork. Some additional information is located in the [welcome issue](https://github.com/ekristen/aws-nuke/issues/276) for more information. 

> [!CAUTION]
> This repository for aws-nuke is no longer being actively maintained. We recommend users to switch to the actively maintained fork of this project at [ekristen/aws-nuke](https://github.com/ekristen/aws-nuke).
> We appreciate all the support and contributions we've received throughout the life of this project. We believe that the fork will continue to provide the functionality and support that you have come to expect from aws-nuke.
> Please note that this deprecation means we will not be addressing issues, accepting pull requests, or making future releases from this repository.
> Thank you for your understanding and support.
