### ISSUE TITLE
Generic filtering of resources with dateOlderThan

### ISSUE THREAD

**Issue by shayfisher** [rebuy-de/aws-nuke#812]
Is there a way to provide a generic filter (e.g not a specific resource based filter) that would filter out resources that are new ?
I can filter in a context of a service as an example: EC2Instance
This would make me have an exhaustive list of all the services that I use which will make the config file quite large.
I simply wish to delete resources that are older than X days no matter what they are on a given account.
Is it possible ?
Thank you!

**Comment by ekristen** [comment]
Everything is currently resource based, however there is a Global Filters feature on the now primary fork of aws-nuke https://github.com/ekristen/aws-nuke

If you have a chance, please check it out and let us know if you run into an issues by opening an issue over on the fork.

----

Please see the copy of the notice from the README about the deprecation of this project. Sven was kind enough to grant me access to help triage and close issues and pull requests that have already been addressed in the actively maintained fork. Some additional information is located in the [welcome issue](https://github.com/ekristen/aws-nuke/issues/276) for more information. 

> [!CAUTION]
> This repository for aws-nuke is no longer being actively maintained. We recommend users to switch to the actively maintained fork of this project at [ekristen/aws-nuke](https://github.com/ekristen/aws-nuke).
> We appreciate all the support and contributions we've received throughout the life of this project. We believe that the fork will continue to provide the functionality and support that you have come to expect from aws-nuke.
> Please note that this deprecation means we will not be addressing issues, accepting pull requests, or making future releases from this repository.
> Thank you for your understanding and support.
