### ISSUE TITLE
External ID support for assume-role switch

### ISSUE THREAD

**Issue by iancward** [rebuy-de/aws-nuke#817]
PR #667 added the ability to assume a role via the command line; however, it is best practice to use an external ID when assuming roles between accounts, so it would be nice to be able to do this on the command line.

Also, the assume role CLI option isn't documented in the README; it would be nice if there was some info showing that it was a feature.

**Comment by ekristen** [comment]
@iancward this was implemented on my fork of aws-nuke, which has recently become the active successor to this project. It was implemented via https://github.com/ekristen/aws-nuke/pull/52

If you should run into any issues, please open an issue over there.

----

Please see a copy of the notice from the README about the deprecation of this project. Sven was kind enough to grant me access to help triage and close issues and pull requests that have already been addressed in the actively maintained fork. Some additional information is located in the [welcome issue](https://github.com/ekristen/aws-nuke/issues/276) for more information. 

> [!CAUTION]
> This repository for aws-nuke is no longer being actively maintained. We recommend users to switch to the actively maintained fork of this project at [ekristen/aws-nuke](https://github.com/ekristen/aws-nuke).
> We appreciate all the support and contributions we've received throughout the life of this project. We believe that the fork will continue to provide the functionality and support that you have come to expect from aws-nuke.
> Please note that this deprecation means we will not be addressing issues, accepting pull requests, or making future releases from this repository.
> Thank you for your understanding and support.
