### ISSUE TITLE
These two keys Do not exist so how is the resolved

### ISSUE THREAD

**Issue by mdemarco1234** [rebuy-de/aws-nuke#825]
# Key not found
  # snssubscription:
  #  filters:
  #     SNSSubscription:	
  #    - type: "regex"
  #      value: Owner: 784948981822 ARN: arn:aws:sns:eu-west-1:[[:digit:]]{12}:aws-controltower-SecurityNotifications:7414efbb-b88e-4d2e-8242-ee777646d09d   # need regex for guid

  # Key not found
  #snstopic:
  #    SNSTopic:
  #    - type: "regex"
  #      value: "TopicARN: arn:aws:sns:us-east-2:[[:digit:]]{12}:aws-controltower-SecurityNotifications"

**Comment by Benson665** [comment]
354502
