### ISSUE TITLE
Filtered IAMUserPolicyAttachment detached

### ISSUE THREAD

**Issue by gargamile** [rebuy-de/aws-nuke#828]
Following the example from the README.md, the AdministratorAccess policy is always detached after deleting some resources. I need to re-attach the AWS default policy AdministratorAccess a few times to completely nuke the account. Has anyone else experienced this?

accounts:
  "000000000000": 
    filters:
      IAMUser:
      - "aws-nuke"
      IAMUserPolicyAttachment:
      - "aws-nuke -> AdministratorAccess"
      IAMUserAccessKey:
      - "aws-nuke -> ABCDEFGHIJKLMNOPQRST"

The logs show the AdministratorAccess policy being triggered to remove:
`global - IAMUserPolicyAttachment - aws-nuke -> AdministratorAccess - [PolicyArn: "arn:aws:iam::aws:policy/AdministratorAccess", PolicyName: "AdministratorAccess", UserName: "aws-nuke", tag:user:temp: "destruction"] - triggered remove`

...many resources are deleted, then the policy is detached:

`ERRO[1322] AccessDenied: User: arn:aws:iam::000000000000:user/aws-nuke is not authorized to perform: iam:ListRoles on resource: arn:aws:iam::000000000000:role/ because no identity-based policy allows the iam:ListRoles action
	status code: 403`

**Comment by mikefossa** [comment]
I'm also having an issue where a filtered IAMRolePolicy (attachment of a managed policy to a role, e.g. `OrganizationAccountAccessRole -> AdministratorAccess`) is getting nuked. could lop this into the same issue.

**Comment by ekristen** [comment]
Closing due to age. Please test v3 at https://github.com/ekristen/aws-nuke and open an issue there if the problem persists.

----

Please see the copy of the notice from the README about the deprecation of this project. Sven was kind enough to grant me access to help triage and close issues and pull requests that have already been addressed in the actively maintained fork. Some additional information is located in the [welcome issue](https://github.com/ekristen/aws-nuke/issues/276) for more information. 

> [!CAUTION]
> This repository for aws-nuke is no longer being actively maintained. We recommend users to switch to the actively maintained fork of this project at [ekristen/aws-nuke](https://github.com/ekristen/aws-nuke).
> We appreciate all the support and contributions we've received throughout the life of this project. We believe that the fork will continue to provide the functionality and support that you have come to expect from aws-nuke.
> Please note that this deprecation means we will not be addressing issues, accepting pull requests, or making future releases from this repository.
> Thank you for your understanding and support.
