### ISSUE TITLE
Trigger aws-nuke on weekly basis

### ISSUE THREAD

**Issue by fsipa** [rebuy-de/aws-nuke#848]
Hi all,

How we can trigger aws-nuke on weekly basis? 
How automated AWS-Nuke ? 

Br,

**Comment by der-eismann** [comment]
Hi @fsipa, I don't think that's an issue with the project that should be discussed here, as it is more of a general question. There are many ways like running it:
- as a cronjob on some server
- in a CI pipeline with a tool like Jenkins or GitHub Actions
- on AWS lambda
Just ask Google about that, unfortunately we can't help with such basic things.
