### ISSUE TITLE
Route53ResourceRecordSet - stuck waiting

### ISSUE THREAD

**Issue by miguels1204** [rebuy-de/aws-nuke#849]
Hey everyone,

When running the aws-nuke task, sometimes **Route53ResourceRecordSet** resources that were created by deployer (eks-cluster) are stuck in "waiting" state on deletion.

We are using most recent release (2.19.0) but this problem was appearing in older versions too.

build	06-Aug-2022 12:37:08	global - Route53ResourceRecordSet - [Name: "******.", Type: "CNAME"] - **waiting**
build	06-Aug-2022 12:37:08	global - Route53ResourceRecordSet - **************- [Name: "*******", Type: "TXT"] - **waiting**
build	06-Aug-2022 12:37:08	global - Route53ResourceRecordSet - **************. - [Name: "*********", Type: "CNAME"] - **waiting**

**Comment by ekristen** [comment]
If this is still an issue, please open an issue at https://github.com/ekristen/aws-nuke

----

Please see the copy of the notice from the README about the deprecation of this project. Sven was kind enough to grant me access to help triage and close issues and pull requests that have already been addressed in the actively maintained fork. Some additional information is located in the [welcome issue](https://github.com/ekristen/aws-nuke/issues/276) for more information. 

> [!CAUTION]
> This repository for aws-nuke is no longer being actively maintained. We recommend users to switch to the actively maintained fork of this project at [ekristen/aws-nuke](https://github.com/ekristen/aws-nuke).
> We appreciate all the support and contributions we've received throughout the life of this project. We believe that the fork will continue to provide the functionality and support that you have come to expect from aws-nuke.
> Please note that this deprecation means we will not be addressing issues, accepting pull requests, or making future releases from this repository.
> Thank you for your understanding and support.
