### ISSUE TITLE
DHCP option set are not cleaned up

### ISSUE THREAD

**Issue by tzvatot** [rebuy-de/aws-nuke#851]
DHCP option set are not identified or removed after cleanup.
Using:
aws-nuke version v2.19.0 - Wed May 18 13:02:42 UTC 2022 - 357aa44f5a04df9d1faa8c57bb5ce924871a910a

**Comment by ekristen** [comment]
@tzvatot `EC2DHCPOption` is a supported resource now. It might not have been in version 2.19.0. Please see the [actively managed fork of aws-nuke](https://github.com/ekristen/aws-nuke).

If you have a chance, please check it out and let us know if you run into an issues by opening an issue over on the fork.

----

Please see the copy of the notice from the README about the deprecation of this project. Sven was kind enough to grant me access to help triage and close issues and pull requests that have already been addressed in the actively maintained fork. Some additional information is located in the [welcome issue](https://github.com/ekristen/aws-nuke/issues/276) for more information. 

> [!CAUTION]
> This repository for aws-nuke is no longer being actively maintained. We recommend users to switch to the actively maintained fork of this project at [ekristen/aws-nuke](https://github.com/ekristen/aws-nuke).
> We appreciate all the support and contributions we've received throughout the life of this project. We believe that the fork will continue to provide the functionality and support that you have come to expect from aws-nuke.
> Please note that this deprecation means we will not be addressing issues, accepting pull requests, or making future releases from this repository.
> Thank you for your understanding and support.
