### ISSUE TITLE
Support for tag in Medialive, MediaPackage and add support for MediaConnect

### ISSUE THREAD

**Issue by kevinmcrofts** [rebuy-de/aws-nuke#853]
Is it possible to add tag support also to Medialive and MediaPackage?
Support for MediaConnect is not available in the codebase at the moment - could this be added?
Thanks
Kevin

**Comment by ad-m-ss** [comment]
> Support for MediaConnect is not available in the codebase at the moment - could this be added?

Could you try to use CloudControl for that? The implementation should be pretty straightforward: https://github.com/rebuy-de/aws-nuke/blob/e36ec1a91854e457d2a0b8790a0b09b279facbd8/resources/cloudcontrol.go#L24-L37

**Comment by ekristen** [comment]
This is on my backlog for the fork.

----

Please see the copy of the notice from the README about the deprecation of this project. Sven was kind enough to grant me access to help triage and close issues and pull requests that have already been addressed in the actively maintained fork. Some additional information is located in the [welcome issue](https://github.com/ekristen/aws-nuke/issues/276) for more information. 

> [!CAUTION]
> This repository for aws-nuke is no longer being actively maintained. We recommend users to switch to the actively maintained fork of this project at [ekristen/aws-nuke](https://github.com/ekristen/aws-nuke).
> We appreciate all the support and contributions we've received throughout the life of this project. We believe that the fork will continue to provide the functionality and support that you have come to expect from aws-nuke.
> Please note that this deprecation means we will not be addressing issues, accepting pull requests, or making future releases from this repository.
> Thank you for your understanding and support.
