### ISSUE TITLE
deletion protection prevents RDS nuke

### ISSUE THREAD

**Issue by jayunit100** [rebuy-de/aws-nuke#856]
Looks like maybe need to do something w/ deletion protection to disable it before nuking DBs ?

![image](https://user-images.githubusercontent.com/826111/193463356-f3b789e0-5c73-4d1b-84bf-71405f5492e9.png)

**Comment by bjoernhaeuser** [comment]
You need to enable [disable deletion protection](https://github.com/rebuy-de/aws-nuke#feature-flags). That should do the trick.

**Comment by jayunit100** [comment]
thanks !
