### ISSUE TITLE
Too Many Resource Types Un-Deleted

### ISSUE THREAD

**Issue by GmoshkoACM** [rebuy-de/aws-nuke#858]
The Resource Types that does not been deleted are:
EC2Instance 
EC2NATGateaways
RDSDBClusterParameterGroup
RDSDBParameterGroup
RDSOptionGroup

![ResourcesList](https://user-images.githubusercontent.com/88616792/194269082-fb43f959-9995-4c27-85ae-1d8a85932d35.png)
![aws-nuke-config](https://user-images.githubusercontent.com/88616792/194267021-25d98e25-c10c-42e8-91ca-7f9e9f0bd69e.png)
![ScanResult](https://user-images.githubusercontent.com/88616792/194267025-51bfc559-a8ab-488e-938a-c9e9dc6055c4.png)

**Comment by bjoernhaeuser** [comment]
@GmoshkoACM please share complete output of aws-nuke, with the verbose option.

**Comment by ekristen** [comment]
No further information has been provided by the OP, closing.
