### ISSUE TITLE
Infinite loop at apprunner CloudWatchLogsLogGroup 

### ISSUE THREAD

**Issue by CGarces** [rebuy-de/aws-nuke#862]
Hi.

I need to delete several accounts with apprunner demos.
All accounts have the same problem, the process wait for CloudWatchLogsLogGroup deletion and never stops.

```
eu-west-1 - CloudWatchLogsLogGroup - /aws/apprunner/foo/bar/service - waiting
us-east-1 - CloudWatchLogsLogGroup - /aws/apprunner/foo/bar/service - waiting
```

If I finish aws-nuke and re-run again over the same account the log groups are removed without problem.
Also the logs can be removed manually and not raise any error.

I'm using aws-nuke version v2.19.0

**Comment by martivo** [comment]
https://github.com/rebuy-de/aws-nuke/issues/500 This seems to be the same issue?

**Comment by CGarces** [comment]
Duplicate of #500
