### ISSUE TITLE
Can I delete all resources based on a single "name" filter?

### ISSUE THREAD

**Issue by jmvbxx** [rebuy-de/aws-nuke#866]
We have a shared development account where I would like to delete all resources based on the name string. For example, delete any resource with the name string, "*blarg*". I have to be careful because I can't delete resources owned by other team members.

Is this supported by the current version? Thanks so much!

**Comment by pwuersch** [comment]
Is there an update on this use-case? I'd be interested in a similar functionality. Just looking for filtering all resources by tags effectively...

**Comment by ekristen** [comment]
The fork https://github.com/ekristen/aws-nuke has a Global Filters feature that you can try and write a single filter to filter out everything on, but that assumes all resources have the exact same property or tag, etc.

Please give it a try, feel free to open an issue over there.

----

Please see the copy of the notice from the README about the deprecation of this project. Sven was kind enough to grant me access to help triage and close issues and pull requests that have already been addressed in the actively maintained fork. Some additional information is located in the [welcome issue](https://github.com/ekristen/aws-nuke/issues/276) for more information. 

> [!CAUTION]
> This repository for aws-nuke is no longer being actively maintained. We recommend users to switch to the actively maintained fork of this project at [ekristen/aws-nuke](https://github.com/ekristen/aws-nuke).
> We appreciate all the support and contributions we've received throughout the life of this project. We believe that the fork will continue to provide the functionality and support that you have come to expect from aws-nuke.
> Please note that this deprecation means we will not be addressing issues, accepting pull requests, or making future releases from this repository.
> Thank you for your understanding and support.
