### ISSUE TITLE
Error when removing events rule with targets

### ISSUE THREAD

**Issue by Octogonapus** [rebuy-de/aws-nuke#877]
When trying to remote an events rule with targets, you will get an error like `An error occurred (ValidationException) when calling the DeleteRule operation: Rule can't be deleted since it has targets.`.
This project already has support for removing targets via `CloudWatchEventsTarget` and rules via `ListCloudWatchEventsRules`. Is there a way to impose an ordering between these two resources? i.e. remove all targets first, then all rules. Otherwise, maybe these two resources could be combined?

**Comment by ekristen** [comment]
@Octogonapus appreciate the feedback, a larger effort is being looked at for DAG operations, but for now I'm closing this as we are moving to the new fork.

----

Please see the copy of the notice from the README about the deprecation of this project. Sven was kind enough to grant me access to help triage and close issues and pull requests that have already been addressed in the actively maintained fork. Some additional information is located in the [welcome issue](https://github.com/ekristen/aws-nuke/issues/276) for more information. 

> [!CAUTION]
> This repository for aws-nuke is no longer being actively maintained. We recommend users to switch to the actively maintained fork of this project at [ekristen/aws-nuke](https://github.com/ekristen/aws-nuke).
> We appreciate all the support and contributions we've received throughout the life of this project. We believe that the fork will continue to provide the functionality and support that you have come to expect from aws-nuke.
> Please note that this deprecation means we will not be addressing issues, accepting pull requests, or making future releases from this repository.
> Thank you for your understanding and support.
