### ISSUE TITLE
Infinite loop with elasticbeanstalk s3 bucket

### ISSUE THREAD

**Issue by CGarces** [rebuy-de/aws-nuke#897]
I have a infinite loop waiting for the deletion of a S3 bucket.

I have cloudtrail enabled so I can see the API calls done by aws-nuke (by user name)

![image](https://user-images.githubusercontent.com/6617155/207892506-b653da94-9ac0-4728-b02b-c20e0cb3dcf1.png)

I see that the bucket is deleted but created again 3 minutes 

aws-nuke is calling S3 apis in a infinite loop, until I remove the s3 by hand.

```
eu-west-1 - S3Bucket - s3://elasticbeanstalk-eu-west-1-xxx- [CreationDate: "2022-12-14 19:05:16 +0000 UTC", Name: "elasticbeanstalk-eu-west-1-xxx"] - waiting
eu-west-1 - S3Bucket - s3://elasticbeanstalk-eu-west-1-xxx- [CreationDate: "2022-12-14 19:05:16 +0000 UTC", Name: "elasticbeanstalk-eu-west-1-xxx"] - waiting
eu-west-1 - S3Bucket - s3://elasticbeanstalk-eu-west-1-xxx- [CreationDate: "2022-12-14 19:05:16 +0000 UTC", Name: "elasticbeanstalk-eu-west-1-xxx"] - waiting

```

Under witch scenarios  CreateBucket API is called? some cloudformation rollback?

**Comment by optplx** [comment]
Hello @CGarces ,

I am fairly new to aws-nuke, but here are my 2 cents on this: going through the code base I did not see any occurrence of `CreateBucket`. It doesn't look like an aws-nuke thing to create resources :p 

Is it happening for this specific bucket only? As you may know, this bucket is created by ElasticBeanstalk as described [here](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/AWSHowTo.S3.html) , so I am wondering if there is a mechanism AWS side to keep it alive.

It could probably help if you provide your aws-nuke configuration and version

**Comment by ekristen** [comment]
Closing due to age. Please test v3 at https://github.com/ekristen/aws-nuke and report any issues there.


----

Please see the copy of the notice from the README about the deprecation of this project. Sven was kind enough to grant me access to help triage and close issues and pull requests that have already been addressed in the actively maintained fork. Some additional information is located in the [welcome issue](https://github.com/ekristen/aws-nuke/issues/276) for more information. 

> [!CAUTION]
> This repository for aws-nuke is no longer being actively maintained. We recommend users to switch to the actively maintained fork of this project at [ekristen/aws-nuke](https://github.com/ekristen/aws-nuke).
> We appreciate all the support and contributions we've received throughout the life of this project. We believe that the fork will continue to provide the functionality and support that you have come to expect from aws-nuke.
> Please note that this deprecation means we will not be addressing issues, accepting pull requests, or making future releases from this repository.
> Thank you for your understanding and support.
