### ISSUE TITLE
Filter out default resources

### ISSUE THREAD

**Issue by mangled-data** [rebuy-de/aws-nuke#951]
Is there an easy way to filter out all default resources ? My accounts are under AWS Organization (so it comes with default policies and roles, apart from default VPCs etc). My goal is to delete the resources so it looks like a new account - but not cleanup everything in the account.

**Comment by rquadling** [comment]
I'm about to do the same to one of our Orga accounts. We also have SSO roles/policies to deal with. Fortunately, we have a lot under Terraform control, but not sure if everything is (or can be).

 The process I'm going with is first identification. From that, I'm hoping to be able to filter out specific resources that we know are managed elsewhere and required.
 
 It may be enough.

**Comment by mangled-data** [comment]
Thinking more, I think if we have a universal filter (don't remove anything that has name/tag containing *default*), it would be super useful. Much the same way, *prod* string is used to filter production accounts.  I worry if any of the defaults gets deleted and needed a support ticket to reinstate. Long back if you delete default VPC, it needed a ticket with AWS. Thankfully, now there's an API

**Comment by optplx** [comment]
I have a similar workflow, I have added a `ignore-nuke` tag on all my base resources and ignore this in my conf. It could be nice to have this directly in the code as a feature indeed (something like a configurable default filter)

**Comment by mangled-data** [comment]
@optplx If possible, could you please share the conf/changes ? Would help me avoid reinventing the wheel a bit

**Comment by ekristen** [comment]
There's no universal way to know what is default in an account unfortunately. It can also vary per organization depending on how the organization is setup. AWS Nuke is designed to wipe everything. If you manage to cook up a configuration that filters default resources, happy to host it in the docs for the active fork now being maintained.

----

Please see the copy of the notice from the README about the deprecation of this project. Sven was kind enough to grant me access to help triage and close issues and pull requests that have already been addressed in the actively maintained fork. Some additional information is located in the [welcome issue](https://github.com/ekristen/aws-nuke/issues/276) for more information. 

> [!CAUTION]
> This repository for aws-nuke is no longer being actively maintained. We recommend users to switch to the actively maintained fork of this project at [ekristen/aws-nuke](https://github.com/ekristen/aws-nuke).
> We appreciate all the support and contributions we've received throughout the life of this project. We believe that the fork will continue to provide the functionality and support that you have come to expect from aws-nuke.
> Please note that this deprecation means we will not be addressing issues, accepting pull requests, or making future releases from this repository.
> Thank you for your understanding and support.
