### ISSUE TITLE
Upgrading to latest version fails due to missing mock files

### ISSUE THREAD

**Issue by hbastosc** [rebuy-de/aws-nuke#955]
When using aws-nuke as a library, if I try to update to the latest version resources fails because mock files are missing.
```
 ✗ go mod tidy
go: downloading github.com/golang/mock v1.6.0
go: finding module for package github.com/rebuy-de/aws-nuke/v2/mocks/mock_cloudformationiface
go: downloading github.com/rebuy-de/aws-nuke v2.10.0+incompatible
github.com/McK-Internal/CNT_MCO-sandbox_asset/pkg/aws-nuke/cmd imports
        github.com/rebuy-de/aws-nuke/v2/resources tested by
        github.com/rebuy-de/aws-nuke/v2/resources.test imports
        github.com/rebuy-de/aws-nuke/v2/mocks/mock_cloudformationiface: module github.com/rebuy-de/aws-nuke/v2@latest found (v2.21.2), but does not contain package github.com/rebuy-de/aws-nuke/v2/mocks/mock_cloudformationiface
```

Seems this is used on some test files and that are inside resources and causing this issue. Is this something that can be moved somewhere else to avoid this error.

**Comment by andreadecorte** [comment]
Facing the issue too. To fix this, mocks should be committed to the repository. There is no real consensus on it, but the go documentation seems to push towards it for easier usage (see this [blog post](https://halyph.github.io/blog/2023/2023-01-17-commit-go-gen-mock/) for some references)

**Comment by iuliancristea** [comment]
Hi @svenwltr @der-eismann,

Any ideas here? Could this be addressed? Shouldn't be a big change
