### ISSUE TITLE
RDS Cluster removal fails due to stopped instances

### ISSUE THREAD

**Issue by Zethex** [rebuy-de/aws-nuke#967]
https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/USER_DeleteCluster.html#USER_Deletion_Stopped_Cluster

Is it feasible (or functionality even wanted) to make Nuke start any RDS Cluster DB Instances before terminating if it detects any  instance in a stopped state?

**Comment by ekristen** [comment]
There are other feature flags in the tool that disable termination protection and things of that nature, I don't see why it couldn't be added to start an RDS instance, it would be a specialized operating mode like the CloudFormation stack deletion protection.

**Comment by ekristen** [comment]
tracked via https://github.com/ekristen/aws-nuke/issues/347
