### ISSUE TITLE
Hard-coded check for presence of "prod" string in account alias is too restrictive

### ISSUE THREAD

**Issue by krishnan-mani** [rebuy-de/aws-nuke#997]
As documented in the [README](https://github.com/rebuy-de/aws-nuke/blob/58736c8eb2778a345bc28fc0735a492550abab79/README.md?plain=1#L33), `aws-nuke` refuses to run as soon as it detects the presence of the (substring) `prod` in the AWS account alias.

However, it is also not uncommon to use a string such as `nonprod` (!) in the alias for accounts that *not* in production use, and these are precisely the kinds of accounts one may want to use `aws-nuke` against, as they are used for experimentation.

Rather than be forced to fork the repo (to make a trivial change to remove the hard-coding), we are requesting that the user be allowed to specify a choice for this kind of safeguard.

This is currently an impediment to our intended use of `aws-nuke`

**Comment by ikarlashov** [comment]
We have the same issue that OP described. It's not possible to nuke `nonprod` accounts. Also all accounts that have `productivity` or `producer` in the name won't be nuked.

**Comment by ekristen** [comment]
@krishnan-mani @sstoops @ikarlashov 

A feature called [Bypass Alias Check](https://ekristen.github.io/aws-nuke/features/bypass-alias-check/) has been implemented in the [now active managed fork of aws-nuke](https://github.com/ekristen/aws-nuke). 

Unfortunately at the moment, `prod` is still hard-coded, but I believe there is likely room to discuss making a change here.

If you have a chance, please check it out and let us know if you run into an issues by opening an issue over on the fork.

----

Please see the copy of the notice from the README about the deprecation of this project. Sven was kind enough to grant me access to help triage and close issues and pull requests that have already been addressed in the actively maintained fork. Some additional information is located in the [welcome issue](https://github.com/ekristen/aws-nuke/issues/276) for more information. 

> [!CAUTION]
> This repository for aws-nuke is no longer being actively maintained. We recommend users to switch to the actively maintained fork of this project at [ekristen/aws-nuke](https://github.com/ekristen/aws-nuke).
> We appreciate all the support and contributions we've received throughout the life of this project. We believe that the fork will continue to provide the functionality and support that you have come to expect from aws-nuke.
> Please note that this deprecation means we will not be addressing issues, accepting pull requests, or making future releases from this repository.
> Thank you for your understanding and support.
