### ISSUE TITLE
Cloudformation: child stacks never deleted if parent is gone. 

### ISSUE THREAD

**Issue by BigDwarf** [rebuy-de/aws-nuke#999]
When parent stack is removed, there are still child stacks left if their deletion has failed while removing parent. 

Do not see what issue was fixed by https://github.com/rebuy-de/aws-nuke/pull/761 , WDYT about reverting it?

**Comment by Sufian22** [comment]
+1. As @BigDwarf mentioned, the #761 blocks the ability of deleting a **nested CFS** and there's no way to explicitly delete this type of resource.

**Comment by bh1cqx** [comment]
#761 says "A nest stack will be taken care of when the parent stack is cleaned up.". It's not always the case. If child stack deletion has failed once, e.g., during parent stack rollback, it seems it won't be retried when user tries to the parent stack again.

IMHO we probably should either 1) delete parent stack first, and then check existence of child stacks and delete them if needed; or 2) at least make it configurable.

**Comment by ekristen** [comment]
@BigDwarf @Sufian22 @bh1cqx 

This issue has been fixed! I'm happy to say this plagued me for a long while and it is now in the [actively managed fork of aws-nuke](https://github.com/ekristen/aws-nuke).

Orphaned nested stacks whose parent has been removed will now be nuked! 

----

Please see the copy of the notice from the README about the deprecation of this project. Sven was kind enough to grant me access to help triage and close issues and pull requests that have already been addressed in the actively maintained fork. Some additional information is located in the [welcome issue](https://github.com/ekristen/aws-nuke/issues/276) for more information. 

> [!CAUTION]
> This repository for aws-nuke is no longer being actively maintained. We recommend users to switch to the actively maintained fork of this project at [ekristen/aws-nuke](https://github.com/ekristen/aws-nuke).
> We appreciate all the support and contributions we've received throughout the life of this project. We believe that the fork will continue to provide the functionality and support that you have come to expect from aws-nuke.
> Please note that this deprecation means we will not be addressing issues, accepting pull requests, or making future releases from this repository.
> Thank you for your understanding and support.
